### ISSUE TITLE
Splash screen image takes a moment to appear

### ISSUE THREAD

**Issue by rajinsyed** [jonbhanson/flutter_native_splash#100]
In apps like youtube and instagram the splash image is instantly shown in the middle but for my app the image takes a moment to appear. Tried in release mode with iphone.

**Comment by jonbhanson** [comment]
Can you give steps to reproduce?  When I test a release Flutter app on iPhone, performance is similar to Youtube app load.

**Comment by jonbhanson** [comment]
Also, what is the size of your image?  Perhaps if it is very large, the resampling would introduce a delay.

**Comment by jonbhanson** [comment]
Was not able to reproduce.  Feel free to reopen with steps to reproduce.
