### ISSUE TITLE
Invalid value: Not in inclusive range 2..3: 4

### ISSUE THREAD

**Issue by abdullahalamodi** [jonbhanson/flutter_native_splash#110]
this error occur when I change the image and try to rerun **flutter pub pub run flutter_native_splash:create**

PS C:\Users\abdullahalamodi\Documents\git projects\slaon-app> flutter pub pub run flutter_native_splash:create
Precompiling executable...
Precompiled flutter_native_splash:create.
[Android] Creating splash images
[Android] Updating launch_background.xml with splash image path
[Android] Updating colors.xml with color for splash screen background
[Android] Updating styles.xml with full screen mode setting
Unhandled exception:
RangeError (end): Invalid value: Not in inclusive range 2..3: 4
#0      RangeError.checkValidRange (dart:core/errors.dart:357:9)
#1      List.sublist (dart:core-patch/growable_array.dart:84:38)
#2      new HexColor (package:color/hex_color.dart:22:33)
#3      _generatePrimaryColorDarkFromColor (package:flutter_native_splash/android.dart:48:45) 
#4      createSplash (package:flutter_native_splash/android.dart:42:34)
<asynchronous suspension>
<asynchronous suspension>
#6      main (file:///C:/Users/abdullahalamodi/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-0.1.9/bin/create.dart:5:3)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)      
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)     
pub finished with exit code 255

**Comment by jonbhanson** [comment]
Can you share your `flutter_native_splash` settings from your `pubspec.yaml` or `flutter_native_splash.yaml`?  That would help in diagnosis.

**Comment by jonbhanson** [comment]
@abdullahalamodi this problem can't be diagnosed without the config information.  Feel free to reopen the issue with the config information.
