### ISSUE TITLE
Configure the start time

### ISSUE THREAD

**Issue by pulstar** [jonbhanson/flutter_native_splash#124]
**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
I would like to configure the amount of time the image is displayed. It could be a bit faster.

**Describe alternatives you've considered**
I did test other alternatives to flutter_native_splash, but they are not good as it.

**Additional context**
None.

**Comment by jonbhanson** [comment]
@pulstar do you mean that you would like the splash screen to display for a shorter period of time?

**Comment by awarmfastbear** [comment]
I would also like this, my app loads too fast where I cannot even see the splash screen. Is there any way to purposely slow down the splash screen where it waits for a function or sleep function to finish?

**Comment by pulstar** [comment]
Yes. Is it possible?

Em sáb, 30 de jan de 2021 16:26, jonbhanson <notifications@github.com>
escreveu:

**Comment by jonbhanson** [comment]
Unfortunately this is not possible.  This splash screen displays while the native OS is loading the flutter platform, which depends entirely on the speed of the device running the app.  The native splash screen does not add any delay.  You could add a second splash screen within the flutter framework that displays while the rest of your app is loaded.

**Comment by pulstar** [comment]
Thank you for the clarification.

Em sáb, 30 de jan de 2021 17:50, jonbhanson <notifications@github.com>
escreveu:
