### ISSUE TITLE
Could not find bin/remove.dart in package flutter_native_splash when run "flutter pub run flutter_native_splash:remove"

### ISSUE THREAD

**Issue by ToeyPonlawat** [jonbhanson/flutter_native_splash#126]

**Comment by ToeyPonlawat** [comment]
![image](https://user-images.githubusercontent.com/42737755/106843163-f9360180-66d7-11eb-9fce-d4c8551bbb16.png)

**Comment by jonbhanson** [comment]
There is not a `remove` command for this package.  Was there some reason you expected this command to exist, or you just making a guess?

**Comment by mrverdant13** [comment]
I guess it is because you commented "Follow 97 for resolution." in issues regarding splash removal.

**Comment by jonbhanson** [comment]
This command has been added in the latest update.
