### ISSUE TITLE
Flutter App Can't launch after the splash screen is shown when there is no internet connection

### ISSUE THREAD

**Issue by husseinYY** [jonbhanson/flutter_native_splash#131]
**Describe the bug**
Flutter App Can't launch after the splash screen is shown when there is no internet connection... When I have internet connection everything is working... But when I shut down the Wifi and Mobile Data. Flutter doesn't print the first screen.

**To Reproduce**
1. Make a flutter app as shown in the documentation
2.Shut the internet down
3. Run the app

**Expected behavior**
Fade the splash screen out even if there is no internet connection and start the app;

**Device (please complete the following information):**
 - Device: Samsung Galaxy A51
 - OS: Android 10

**Flutter doctor**
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.22.6 at F:\Flutter\flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\H.Abbas\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: F:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at F:\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

**Comment by bdlukaa** [comment]
What are your depedencies?

**Comment by jonbhanson** [comment]
Hello,
I took the steps to reproduce as advised, but I was not able to reproduce.  Can you send me a project that has the problem?

**Comment by husseinYY** [comment]
You can mark this as closed as the problem wasn't with the package

Thank you and sorry for my mistake

**Comment by jonbhanson** [comment]
No worries.  Glad you found the solution! 👍🏻

**Comment by gautam-menon** [comment]
> You can mark this as closed as the problem wasn't with the package
> 
> Thank you and sorry for my mistake

Hey, I have the same issue, how did you end up solving it?

**Comment by svbala99** [comment]
Even I face the same issue. When the internet connection is not there, the app freezes at the splash screen. I'm running Flutter web. How do we resolve this? @jonbhanson

**Comment by jonbhanson** [comment]
This native_flutter_splash package only configures the splash screen that is already present in Flutter apps.  It does not add any code to your package, which is why it is a `dev_dependancy` instead of a `dependancy`.  So, I do not see any way that the splash screen could freeze your app.  It is likely that this problem is caused by something in your app that prevents the loading of your app, so the splash screen remains. To test this, make a test where your `main()` returns a `Container(color: Colors.black);`. If the splash goes away with this simple app, it shows that something in your app is preventing loading.

**Comment by YDA93** [comment]
From my experience with this package, this is related to another problems in the code not related to this package at all.

Example: Async functions with await keyword that are not returning anything.

**Comment by jonbhanson** [comment]
Agreed @YDA93. Closed due to inactivity.  Feel free to reopen if you still have a problem.
