### ISSUE TITLE
Conflict with Firebase Messaging

### ISSUE THREAD

**Issue by sushilbalami** [jonbhanson/flutter_native_splash#132]
```
E/flutter ( 4382): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'toRawHandle' was called on null.
E/flutter ( 4382): Receiver: null
E/flutter ( 4382): Tried calling: toRawHandle()
```
After I installed the native_splash_screen package it conflicts with firebase messaging and shows this error.
if I remove native_splash_screen error goes away.
Note: I had followed properly steps of firebase messaging  and works without native_splash_screen package

**Comment by jonbhanson** [comment]
@sushilbalami can you post the code that is triggering the error?  Or can you send me some code that I can use to reproduce the problem?

**Comment by sushilbalami** [comment]
```
  firebase_core: ^0.7.0
  firebase_crashlytics: 0.1.3
  firebase_messaging: "^6.0.13"
  firebase_dynamic_links: ^0.7.0+1
```

these should be list of versions....

**Comment by jonbhanson** [comment]
@sushilbalami I tried to replicate your error, but was not able to.  You will have to supply the code for me to help solve this problem.

**Comment by jonbhanson** [comment]
I am closing this ticket due to inactivity, but feel free to reopen with steps to replicate.
