### ISSUE TITLE
White splash screen appears before colored splash screen

### ISSUE THREAD

**Issue by brobee** [jonbhanson/flutter_native_splash#134]
I setup the plugin and I want to use colored splash screen with a logo. However before my configured colored splash screen, a white screen pops up then switches to my picked color. 

My config:

flutter_native_splash:
  color: "#30ffd9"
  image: assets/splash.png
  color_dark: "#1a1a1a"
  image_dark: assets/splash.png
  android: true
  ios: true

 - Device: IOS Simulator

**Flutter doctor** - However it's android version related error, but I use IOS simulator.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-2.0.pre.64, on Mac OS X 10.14.6 18G3020
    darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2018.3.5)
[✓] VS Code (version 1.53.2)

**Comment by jonbhanson** [comment]
Please try uninstalling your app, powering off your emulated device, power back on, and then try reinstalling.

**Comment by AgustinV08** [comment]
This workaround works, this issue can be closed

**Comment by jonbhanson** [comment]
Hope this fixed it for you, @brobee.  Feel free to reopen if you still have a problem.
