### ISSUE TITLE
Bad state: No element error while running flutter pub run flutter_native_splash:create

### ISSUE THREAD

**Issue by MariiaS** [jonbhanson/flutter_native_splash#136]
**Describe the bug**
I'm trying to run flutter_native_splash:create. The yaml file consist only color setting:

`flutter_native_splash:
  color: "#489FB5"`

**Expected behavior**
Expected that the splash is generated for both platforms

**Device (please complete the following information):**
 - Android Simulator

**Additional context**
Error stacktrace:

`Restoring Flutter's default white native splash screen...
[Android] Updating android/app/src/main/res/drawable/launch_background.xml with splash image path
[Android] Updating android/app/src/main/res/values/colors.xml with color for splash screen background
[Android] Updating styles.xml with full screen mode setting
[iOS] Updating LaunchScreen.storyboard with width, and height
Unhandled exception:
Bad state: No element
#0      Iterable.firstWhere (dart:core/iterable.dart:516:5)
#1      _updateLaunchScreenStoryboard (package:flutter_native_splash/ios.dart:139:63)
#2      _applyLaunchScreenStoryboard (package:flutter_native_splash/ios.dart:107:12)
#3      _createiOSSplash (package:flutter_native_splash/ios.dart:66:9)
<asynchronous suspension>
#4      tryCreateSplashByConfig (package:flutter_native_splash/supported_platform.dart:61:5)
<asynchronous suspension>
#5      tryRemoveSplash (package:flutter_native_splash/supported_platform.dart:33:3)
<asynchronous suspension>
#6      removeSplash (package:flutter_native_splash/flutter_native_splash.dart:27:3)
<asynchronous suspension>
pub finished with exit code 255
`

**Comment by jonbhanson** [comment]
What version of the package are you running?

Are you sure that you ran the command `flutter pub run flutter_native_splash:create`?  Is it possible that you mistakenly ran `flutter pub run flutter_native_splash:remove`?

**Comment by yanivshaked** [comment]
Same issue here. I am running version 0.3.0 since I'm still on flutter 1.22.4. Output is:

```
PS C:\dev\12Tech12\git\client\tw_app> flutter pub run flutter_native_splash:create
[Android] Updating android/app/src/main/res/drawable/launch_background.xml with splash image path
[Android] No android/app/src/main/res/values/colors.xml file found in your Android project
[Android] Creating android/app/src/main/res/values/colors.xml file and adding it to your Android project
[Android] No android/app/src/main/res/drawable-night/launch_background.xml file found in your Android project
[Android] Creating android/app/src/main/res/drawable-night/launch_background.xml file and adding it to your Android project
[Android] No android/app/src/main/res/values-night/colors.xml file found in your Android project
[Android] Creating android/app/src/main/res/values-night/colors.xml file and adding it to your Android project
[Android] Updating styles.xml with full screen mode setting
[Android] Only 1 style in styles.xml. Flutter V2 embedding has 2 styles by default.  Full screen mode not supported in Flutter V1 embedding.  Skipping update of styles.xml with fullscreen mode
[iOS] Updating LaunchScreen.storyboard with width, and height
Unhandled exception:
Bad state: No element
#0      Iterable.firstWhere (dart:core/iterable.dart:578:5)
#1      _updateLaunchScreenStoryboard (package:flutter_native_splash/ios.dart:139:63)
#2      _applyLaunchScreenStoryboard (package:flutter_native_splash/ios.dart:107:12)
#3      _createiOSSplash (package:flutter_native_splash/ios.dart:66:9)
<asynchronous suspension>
#4      tryCreateSplashByConfig (package:flutter_native_splash/supported_platform.dart:61:11)
<asynchronous suspension>
#5      tryCreateSplash (package:flutter_native_splash/supported_platform.dart:27:9)
<asynchronous suspension>
#6      createSplash (package:flutter_native_splash/flutter_native_splash.dart:17:9)
#7      main (file:///c:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-0.3.1+1/bin/create.dart:5:3)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

Attaching my LaunchScreen.storyboard file.

[LaunchScreen.zip](https://github.com/jonbhanson/flutter_native_splash/files/6084388/LaunchScreen.zip)

**Comment by jonbhanson** [comment]
@yanivshaked I see that in your LaunchScreen.storyboard, the `resources` include an image named `NewLaunchImage` where the default name is `LaunchImage`.  Do you know why the name is different than the default?

**Comment by jonbhanson** [comment]
I will add a better error message so it is clear that the problem is that the `LaunchImage` is not found.

**Comment by yanivshaked** [comment]
You are correct - I renamed the launch image name to solve iOS spring board caching issues. I will rename it back and post the results.

**Comment by yanivshaked** [comment]
After renaming back to `LaunchImage` - works as expected!

![image](https://user-images.githubusercontent.com/13107481/110236082-91741000-7f3c-11eb-993b-db7e827467ad.png)
