### ISSUE TITLE
Dart SDK too old

### ISSUE THREAD

**Issue by justTOBBI** [jonbhanson/flutter_native_splash#138]
**Describe the bug**
I wanted to use the package, but when I say flutter pub get, it says The current Dart SDK version is 2.10.5.

Because MYAPP depends on flutter_native_splash >=1.0.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.

**To Reproduce**
1. Go to 'console'
2. Type in 'flutter pub get'
3. See that it isn't working
4. Type in 'dart --version'
4. See an error

**Expected behavior**
It should work 👉🏻 👈🏻 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47004621/110102538-33f98b00-7da5-11eb-840c-b4924f77d73c.png)

**Device (please complete the following information):**
 - Device: Lenovo IdeaPad 330s
 - OS: Windows 10 Home Edition/ Flutter: 1.22.6 / Dart: 2.10.5

**Flutter doctor**
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.844], locale de-DE)
    • Flutter version 1.22.6 at C:\Coding\flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Tobi\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio4\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Tobi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Additional context**
I recently downgraded from Flutter 2.0 to 1.22.6 because there were some heavy package issues

**Comment by jonbhanson** [comment]
If you are not using Flutter 2.0, you should use `flutter_native_splash: ^0.3.2`.

**Comment by justTOBBI** [comment]
Oh okay thanks. 
I didnt knew this :)
