### ISSUE TITLE
Cannot open file, path = 'web/splash/style.css'

### ISSUE THREAD

**Issue by johnareid54** [jonbhanson/flutter_native_splash#141]
Using Flutter 2.0.2  - it reports the error that it cannot find the style file. 
If I create the file by hand then the code runs OK

**Comment by jonbhanson** [comment]
I was not able to reproduce, but I will make an update to create the file before writing to it.  Hopefully this fixes your problem.  I will push the update and close this ticket.  Feel free to reopen if you still experience the trouble.
