### ISSUE TITLE
 Cannot open file, path = 'android/app/src/main/res/drawable-night-v21/background.png' 

### ISSUE THREAD

**Issue by M123-dev** [jonbhanson/flutter_native_splash#142]
```
Unhandled exception:
FileSystemException: Cannot open file, path = 'android/app/src/main/res/drawable-night-v21/background.png' (OS Error: Das System kann den angegebenen Pfad nicht finden.
, errno = 3)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _createBackground (package:flutter_native_splash/ios.dart:258:10)
#4      _createAndroidSplash (package:flutter_native_splash/android.dart:64:3)
#5      tryCreateSplashByConfig (package:flutter_native_splash/supported_platform.dart:52:5)
#6      tryCreateSplash (package:flutter_native_splash/supported_platform.dart:27:3)
#7      createSplash (package:flutter_native_splash/flutter_native_splash.dart:17:3)
#8      main (file:///D:/111Programming/Flutter/SDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-1.1.1/bin/create.dart:5:3)
#9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
pub finished with exit code 255
```
Translated: The System can't find the specified path.

**Settings**
```
flutter_native_splash:
  color: "#42a5f5"
  image: assets/temp/Logo.png
  image_dark: assets/temp/Logo.png
  color_dark: "#ffffff"
```

![FNSP](https://user-images.githubusercontent.com/39344769/111332572-35af3280-8672-11eb-8f41-976ba38654e3.PNG)
When deleting everything in res before running:
![new](https://user-images.githubusercontent.com/39344769/111334488-e5d16b00-8673-11eb-9fe2-bbf25cc9c46d.PNG)

**Flutter doctor**

<details>
  <summary>Flutter doctor</summary>
  [√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.867], locale de-DE)
    • Flutter version 2.0.2 at D:\111Programming\Flutter\SDK\flutter
    • Framework revision 8962f6dc68 (5 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\marvi\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: E:\Programme\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at E:\Programme\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.2)
    • VS Code at C:\Users\marvi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.50

• No issues found!

</details>

**Comment by jonbhanson** [comment]
Sorry, this was introduced in the last update.  I'll push a correction.

**Comment by M123-dev** [comment]
Thanks fixed it
