### ISSUE TITLE
app works fine but the splash screen take longer time to load app

### ISSUE THREAD

**Issue by samwhitedove** [jonbhanson/flutter_native_splash#145]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Flutter doctor**
Please paste the results of the `flutter doctor -v` here

**Additional context**

**Comment by jonbhanson** [comment]
What platform?  What is the difference in time with/without the native splash?  What resolution graphics are you using?

**Comment by samwhitedove** [comment]
Works fine, I think it should be the normal time app wait to initialize
