### ISSUE TITLE
pub finished with exit code 255

### ISSUE THREAD

**Issue by sahmirzali** [jonbhanson/flutter_native_splash#146]
**When I run flutter_native_splash: create this error happen**. can you help me ?

Bug: - > 

shahmirzali@Shahmirzalis-MacBook-Pro quran_app-master % flutter pub run flutter_native_splash:create
[iOS] Creating splash images
[iOS] Updating LaunchScreen.storyboard with width, and height
Unhandled exception:
NoSuchMethodError: The getter 'children' was called on null.
Receiver: null
Tried calling: children
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _updateLaunchScreenStoryboard (package:flutter_native_splash/ios.dart:139:30)
#2      _applyLaunchScreenStoryboard (package:flutter_native_splash/ios.dart:107:12)
#3      _createiOSSplash (package:flutter_native_splash/ios.dart:66:9)
<asynchronous suspension>
#4      tryCreateSplashByConfig (package:flutter_native_splash/supported_platform.dart:61:11)
#5      tryCreateSplash (package:flutter_native_splash/supported_platform.dart:27:9)
<asynchronous suspension>
#6      createSplash (package:flutter_native_splash/flutter_native_splash.dart:17:9)
#7      main (file:///Users/shahmirzali/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-0.3.2/bin/create.dart:5:3)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255

**Device **
 - Device: iPhone 11 pro SIMULATOR macOS
 - OS:  iOS14.4

**Flutter doctor**

shahmirzali@Shahmirzalis-MacBook-Pro quran_app-master % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.3 20D91 darwin-x64, locale en-AZ)
    • Flutter version 1.22.6 at /Users/shahmirzali/Development/flutter
    • Framework revision 9b2d32b605 (8 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/shahmirzali/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

**Comment by jonbhanson** [comment]
Can you post the contents of ios/Runner/Base.lproj/LaunchScreen.storyboard?

**Comment by sahmirzali** [comment]
<img width="1775" alt="Screen Shot 2021-03-18 at 16 38 29" src="https://user-images.githubusercontent.com/40922460/111627442-7d67c280-8808-11eb-8a89-2d70d41fab77.png">

**Comment by sahmirzali** [comment]
<img width="1775" alt="Screen Shot 2021-03-18 at 16 40 42" src="https://user-images.githubusercontent.com/40922460/111627639-b142e800-8808-11eb-9b1d-20f4b2f2bf34.png">

**Comment by jonbhanson** [comment]
Sorry, I should have been more specific.  Can you post the XML contents of ios/Runner/Base.lproj/LaunchScreen.storyboard?  If you open it with Android Studio, you can copy the XML contents.

**Comment by sahmirzali** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="17701" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" launchScreen="YES" colorMatched="YES" initialViewController="01J-lp-oVM">
    <device id="retina6_1" orientation="portrait" appearance="light"/>
    <dependencies>
        <deployment identifier="iOS"/>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="17703"/>
        <capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>
    </dependencies>
    <scenes>
        
        <scene sceneID="EHf-IW-A2E">
            <objects>
                <viewController id="01J-lp-oVM" sceneMemberID="viewController">
                    <layoutGuides>
                        <viewControllerLayoutGuide type="top" id="Ydg-fD-yQy"/>
                        <viewControllerLayoutGuide type="bottom" id="xbc-2k-c8Z"/>
                    </layoutGuides>
                    <view key="view" multipleTouchEnabled="YES" contentMode="center" id="Ze5-6b-2t3">
                        <rect key="frame" x="0.0" y="0.0" width="414" height="896"/>
                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                        <color key="backgroundColor" white="1" alpha="1" colorSpace="custom" customColorSpace="genericGamma22GrayColorSpace"/>
                        <color key="tintColor" white="1" alpha="1" colorSpace="custom" customColorSpace="genericGamma22GrayColorSpace"/>
                    </view>
                </viewController>
                <placeholder placeholderIdentifier="IBFirstResponder" id="iYj-Kq-Ea1" userLabel="First Responder" sceneMemberID="firstResponder"/>
            </objects>
            <point key="canvasLocation" x="76.811594202898561" y="251.11607142857142"/>
        </scene>
    </scenes>
</document>
`

**Comment by jonbhanson** [comment]
Your LaunchScreen.storyboard has been modified from the default created by Flutter.  This package is designed to update the default version and it cannot handle some changes.  You should be able to run the package if you revert to the Flutter default LaunchScreen.storyboard:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="12121" systemVersion="16G29" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" launchScreen="YES" colorMatched="YES" initialViewController="01J-lp-oVM">
    <dependencies>
        <deployment identifier="iOS"/>
        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="12089"/>
    </dependencies>
    <scenes>
        <!--View Controller-->
        <scene sceneID="EHf-IW-A2E">
            <objects>
                <viewController id="01J-lp-oVM" sceneMemberID="viewController">
                    <layoutGuides>
                        <viewControllerLayoutGuide type="top" id="Ydg-fD-yQy"/>
                        <viewControllerLayoutGuide type="bottom" id="xbc-2k-c8Z"/>
                    </layoutGuides>
                    <view key="view" contentMode="scaleToFill" id="Ze5-6b-2t3">
                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                        <subviews>
                            <imageView opaque="NO" clipsSubviews="YES" multipleTouchEnabled="YES" contentMode="center" image="LaunchImage" translatesAutoresizingMaskIntoConstraints="NO" id="YRO-k0-Ey4">
                            </imageView>
                        </subviews>
                        <color key="backgroundColor" red="1" green="1" blue="1" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>
                        <constraints>
                            <constraint firstItem="YRO-k0-Ey4" firstAttribute="centerX" secondItem="Ze5-6b-2t3" secondAttribute="centerX" id="1a2-6s-vTC"/>
                            <constraint firstItem="YRO-k0-Ey4" firstAttribute="centerY" secondItem="Ze5-6b-2t3" secondAttribute="centerY" id="4X2-HB-R7a"/>
                        </constraints>
                    </view>
                </viewController>
                <placeholder placeholderIdentifier="IBFirstResponder" id="iYj-Kq-Ea1" userLabel="First Responder" sceneMemberID="firstResponder"/>
            </objects>
            <point key="canvasLocation" x="53" y="375"/>
        </scene>
    </scenes>
    <resources>
        <image name="LaunchImage" width="168" height="185"/>
    </resources>
</document>
```

**Comment by sahmirzali** [comment]
thanks a lot :) it's work
