### ISSUE TITLE
[android] Multiple tag in styles.xml

### ISSUE THREAD

**Issue by ekasetiawans** [jonbhanson/flutter_native_splash#147]
**Describe the bug**

<img width="587" alt="image" src="https://user-images.githubusercontent.com/20693888/111637056-a64d7f00-882b-11eb-9bf6-c21083b179b2.png">

**To Reproduce**
that tag added every generate splash screen

**Comment by jonbhanson** [comment]
Thanks for finding this.  I will push an update that fixes. 👍🏻
