### ISSUE TITLE
Full day saved. Here's to you!

### ISSUE THREAD

**Issue by ScottWallace** [jonbhanson/flutter_native_splash#148]
**Is your feature request related to a problem? Please describe.**
You just saved me a full day's effort, which has real monetary value to me. Please create a method for dropping you a few bucks.

**Describe the solution you'd like**
Many options are available for casual giving.

**Additional context**
Awesome job, you saved me time, which is valuable to me, and I want to drop something your way!

**Comment by jonbhanson** [comment]
I think this is my favorite issue so far!  🤣  I'm very pleased that the package was helpful enough for you to consider gifting me.  How about PayPal: [paypal.me](https://paypal.me/jonbhanson?locale.x=en_US)?  Thanks for your generosity!

Now go finish building something awesome! 💪 You rock! 🤘🤩
