### ISSUE TITLE
Resize and grey screen before loading of the app

### ISSUE THREAD

**Issue by ADARSHAGNIHOTRI** [jonbhanson/flutter_native_splash#153]
**Describe the bug**
Splash screen seems to resize and rebuild again and also some time crash(grey screen) just before resize(zoom)
**To Reproduce**

**Expected behavior**
No grey screen or resize should be appear.

**Screenshots**

https://user-images.githubusercontent.com/51204005/112459016-646c8d80-8d83-11eb-8c20-a8421464c8f2.mp4

**Device (please complete the following information):**

**Flutter doctor**
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.1 20D75 darwin-x64, locale en-GB)
    • Flutter version 2.0.0 at /Users/rootinfosolutions/Documents/flutter1.22.6/flutter
    • Framework revision 60bd88df91 (3 weeks ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/rootinfosolutions/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio copy.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio copy.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

**Additional context**

**Comment by jonbhanson** [comment]
This is Android, right?  Can you post the contents of your android/app/src/main/AndroidManifest.xml (Strip out API keys if you have any) and android/app/src/main/res/values/styles.xml file?

**Comment by ADARSHAGNIHOTRI** [comment]
@jonbhanson Right. This is android.
Here my manifest below --------->>>>>>
<uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="xxxxx"
        android:usesCleartextTraffic="true"
        android:allowBackup="false"
        android:requestLegacyExternalStorage="true"
        android:icon="@mipmap/ic_launcher">
        <meta-data android:name="com.google.android.geo.API_KEY" android:value=""/>
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>

        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

And here my style.xml -------->>>
<?xml version="1.0" encoding="utf-8"?>
<resources>

    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
        <item name="android:windowFullscreen">false</item>
    </style>
</resources>

**Comment by jonbhanson** [comment]
The problem is that a parameter has been removed from your AndroidManifest.xml.  Place this inside your `<activity>` tag:

```xml
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
```

**Comment by ADARSHAGNIHOTRI** [comment]
@jonbhanson  Might it be a reason for crash?

**Comment by jonbhanson** [comment]
I doubt this is related to the crash.  I don't think the crashes are related to this package.

**Comment by ADARSHAGNIHOTRI** [comment]
ok, thanks a lot @jonbhanson . The thing is the crash occurs rarely without any logs on logcat .So i need to check every possibility.
closing this issue.
