### ISSUE TITLE
Creating splash screen fails when background_image is used and color is omitted.

### ISSUE THREAD

**Issue by maxcotech** [jonbhanson/flutter_native_splash#154]
**To Reproduce**

When writing configurations for the splash screen 
Omitting the color and including only background image throws an error saying that the configuration does not have a color property.

**Expected behavior**

I expected the background_image to work without the color since according to the docs only one of them can be used.

**Comment by jonbhanson** [comment]
Can you post your `flutter_native_splash` config?

**Comment by maxcotech** [comment]
flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#42a5f5"
  background_image: "assets/background.png"

**Comment by maxcotech** [comment]
`flutter_native_splash:
  background_image: "assets/background.png"
  background_image_dark: "assets/background.png"`

**Comment by maxcotech** [comment]
```
> flutter_native_splash: 
>    background_image: "assets/background.png" 
>    background_image_dark: "assets/background.png"
```

**Comment by jonbhanson** [comment]
@maxcotech did you mean to close this ticket?  Is the problem solved?

**Comment by maxcotech** [comment]
Not really it was a mistake

**Comment by jonbhanson** [comment]
@maxcotech can you post the error you received?

The config you posted above has the lines:
```yaml
  color: "#42a5f5"
  background_image: "assets/background.png"
```

This will cause a problem because you have both a color and background_image.  You can only have one of these parameters.

**Comment by maxcotech** [comment]
That's the problem , according to the docs, I can only use either background_image or color and not both. But when I decide to use only background_image,  I get this error  `your flutter_native_splash config does not contain a color property`

**Comment by jonbhanson** [comment]
@maxcotech what version of `flutter_native_splash` is listed in `pubspec.yaml`?

**Comment by maxcotech** [comment]
0.3.2

**Comment by jonbhanson** [comment]
The `background_image` feature is only available in the latest version.  For 0.3.2, please use the [0.3.2 readme](https://pub.dev/packages/flutter_native_splash/versions/0.3.2).

**Comment by maxcotech** [comment]
Wooow, I guess I missed that. I guess I ll have to migrate to flutter 2.0 then to be eligible to use it. Anyways, thanks alot @jonbhanson  you have been a tremendous help and I deeply appreciate this wonderful package. 

Am so sorry for the inconveniences this may have brought you. Am closing this issue now.
