### ISSUE TITLE
Release apk splash screen app stuck at splash screen and not navigaing to home screen

### ISSUE THREAD

**Issue by vedprakashsah1998** [jonbhanson/flutter_native_splash#156]
Found issues related
after removing this dependency app still stuck at the splash screen and become problem for my live app

after completely removing this dependency

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

Solution:
` buildTypes {
        debug {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            shrinkResources false
            useProguard true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }`
just add to build.gradle file and works it but the this dependency not working in release build apk

**Comment by jonbhanson** [comment]
I'm sorry, but you will have to describe more clearly because I do not understand.

**Comment by khalifa007** [comment]
same in ios stuck at the splash screen

**Comment by jonbhanson** [comment]
You will need to provide a clear explanation of the problem so I can understand and then help.

**Comment by jonbhanson** [comment]
If you still have an issue, please reopen a ticket using the ticket template and a clear description of the problem.

**Comment by amebrahimi** [comment]
I have this issue too, It gets stuck on the splash screen.

**Comment by jonbhanson** [comment]
@amebrahimi I don't think this package could cause the problem you are describing.  Can you make a quick test and replace your main() function with a simple one that returns a 'hello world' app and see if the app still gets stuck?

**Comment by amebrahimi** [comment]
@jonbhanson sorry my friend you were right. for some reason, I have to build my application with `--no-shrink` flag and it had nothing to do with this package. sorry for taking your time

**Comment by zmm2tysu** [comment]
same stuck in ios, but I don't know how to reproduce it. I had to remove the plugin to solve the problem
