### ISSUE TITLE
Splash screen generated for web even though web:false in flutter_native_splash.yaml

### ISSUE THREAD

**Issue by mjcarlin** [jonbhanson/flutter_native_splash#159]
1. In my flutter_native_splash.yaml file I have web:false to disable generating a splash screen for web use.
2. I run flutter pub run flutter_native_splash:create and everything is good so far.
3. Next I run flutter pub run flutter_native_splash:remove and a style.css and a splash folder gets created and index.html is updated in the web folder even though I set web: false.

Basically, the remove operation is not honoring the web:false setting in flutter_native_splash.yaml. If no style.css exists the removal should not create one and index.html should not be modified.

**Comment by jonbhanson** [comment]
I will push an update to fix this soon.
