### ISSUE TITLE
Flavor support?

### ISSUE THREAD

**Issue by EinatK** [jonbhanson/flutter_native_splash#160]
Do you have flavor support? 
Expected behavior similar to the launcher icons where I name different files and run the command with a custom file name. 
I tried that here but failed because it couldn't find the flutter_native_splash section.
Is there another way to do it?

**Comment by jonbhanson** [comment]
@EinatK @pablodenadai @Rameshv @r8 @raymondddenny what platform(s) are you looking for flavor support?

**Comment by billowapp** [comment]
Plus one here, we're looking to flavor Android and iOS only at this point.

**Comment by jamesmoore255** [comment]
Any update on this?

**Comment by lyledean1** [comment]
I've done a PR for this https://github.com/jonbhanson/flutter_native_splash/pull/180 @jonbhanson

**Comment by jonbhanson** [comment]
Thanks for your contribution, @lyledean1, I appreciate it!  However, I am not sure that the PR you contributed will provide what the users are looking for.  Although your PR allows users to select different **input** configurations, it does not redirect the **outputs** accordingly.  In Android, for example, the image files for splash screens of different flavors will reside in different directories.  This plugin needs to adjust for the different paths of each flavor.  [flutter_launcher_icons](https://github.com/fluttercommunity/flutter_launcher_icons) gives a good example of flavor support.  I have not taken the time to investigate how iOS would implement flavor support, but I assume it is something similar.

**Comment by chainchelliah** [comment]
I also looking for this. PR got merged? Would be really helpful if it goes live. 
Thanks.

**Comment by jonbhanson** [comment]
@chainchelliah the PR was merged and is live, but it only added the ability to select the config file with a command line argument.

**Comment by mellowcello77** [comment]
I have spent 3 days trying to implement a splash for an iOS flavor, looks like the storyboard are compulsory for iOS now. The problem I find is that you are limited to one storyboard per target in Xcode. Does anyone have suggestions, I am imagining that a target/flavor is needed for each launchscreen, not just a scheme. 

For schemes only, you can change the "Asset Catalog Launch Image Set Name" in build settings, but this is deprecated now, it would have been an easier solution but I understand why its deprecated. I cant even get another target in iOS to launch my app. To build a launchimage package to support flavors sounds like a challenge. Does anyone have any ideas?

Cheers

**Comment by mellowcello77** [comment]
I did some more searching and found this to be useful - https://stackoverflow.com/a/66165654/11865941

**Comment by EA-YOUHOU** [comment]
To achieve that we need for each target a info.plist (copy the original one and dupplicate for each target). Despite of launch icon, xcode use the same launchScreen for each target. so we need a specifiq plist to select the right one.

**Comment by elhe26** [comment]
@jonbhanson, any updates? Thanks for the awesome package.

**Comment by ntfnd404** [comment]
Has anyone found a way to solve this problem on ios ?

**Comment by qusaieilouti99** [comment]
@jonbhanson do you have plans to add this feature soon? Thanks.

**Comment by jonbhanson** [comment]
I don't have any plans to add this feature, but PRs are always welcome.

**Comment by jonbhanson** [comment]
Flavor support has been added in the latest version, which I will push soon.  Thanks [Vladimir](https://github.com/vlazdra) for PR [316#](https://github.com/jonbhanson/flutter_native_splash/pull/316)!

**Comment by CodeDoctorDE** [comment]
Can we open another issue for tracking Windows, Linux and Web support?

**Comment by CodeDoctorDE** [comment]
One issue or per platform?

**Comment by jonbhanson** [comment]
I think one issue should be enough.
