### ISSUE TITLE
Question: After running the command `flutter pub run flutter_native_splash:remove`, a white screen will still appear when running the app on the iOS simulator

### ISSUE THREAD

**Issue by realkimmy** [jonbhanson/flutter_native_splash#162]
After running the command `flutter pub run flutter_native_splash:remove`, a white screen will still appear when running the app on the iOS simulator, but it will not appear when running on a real device. Is this normal?

**Comment by jonbhanson** [comment]
The default for a Flutter app is to have a white screen while the app loads the Flutter framework.  If you are not seeing it on a real device, it is probably because the app is cached or the phone is fast enough that the white screen is not seen.  TLDR: I would consider this normal.
