### ISSUE TITLE
cannot copy dark-backgorund.png android

### ISSUE THREAD

**Issue by fredgrott** [jonbhanson/flutter_native_splash#163]
does not create the android dark background image for splash, my terminal output is:
PS D:\fredgrttsstuff\GithubProjects\base_getx> flutter pub run flutter_native_splash:create
[Android] Updating android/app/src/main/res/drawable/launch_background.xml with splash image path
Unhandled exception:
FileSystemException: Cannot copy file to 'android/app/src/main/res/drawable-night/background.png', path = 'assets/dark/background.png' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      _createBackground (package:flutter_native_splash/ios.dart:273:37)
#3      _createAndroidSplash (package:flutter_native_splash/android.dart:57:3)
#4      tryCreateSplashByConfig (package:flutter_native_splash/supported_platform.dart:77:5)
#5      tryCreateSplash (package:flutter_native_splash/supported_platform.dart:28:3)
#6      createSplash (package:flutter_native_splash/flutter_native_splash.dart:17:3)
#7      main (file:///D:/fluttersdk/myfluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-1.1.7+1/bin/create.dart:5:3)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
pub finished with exit code 255
PS D:\fredgrttsstuff\GithubProjects\base_getx>

**Comment by jonbhanson** [comment]
Hello @fredgrott.  In your title the name is _dark-backgorund.png_ with a dash, but in the error message the filename is _background.png_ without the dash.  Is it possible the filename in pubspec.yaml is different from the filename of the file?

**Comment by baguskto** [comment]
I have the same issue for dark mode. The system says OS Error: The system cannot find the path specified. I have to make sure the name path is correct. But it still can't copy my dark image.

**Comment by Morena96** [comment]
same issue any solutions?

**Comment by jonbhanson** [comment]
@baguskto @Morena96 are you running Android Studio on Windows?

**Comment by baguskto** [comment]
Nope, I running Android Studio on Linux

**Comment by jonbhanson** [comment]
@baguskto @Morena96 can you paste your error output?

**Comment by baguskto** [comment]
[Android] Creating splash images
[Android] Updating android/app/src/main/res/drawable/launch_background.xml with splash image path
Unhandled exception:
FileSystemException: Cannot copy file to 'android/app/src/main/res/drawable-night/background.png', path = 'assets/images/splash_background_dark.png' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.copySync (dart:io/file_impl.dart:340:5)
#2      _createBackground (package:flutter_native_splash/ios.dart:273:37)
#3      _createAndroidSplash (package:flutter_native_splash/android.dart:57:3)
#4      tryCreateSplashByConfig (package:flutter_native_splash/supported_platform.dart:77:5)
#5      tryCreateSplash (package:flutter_native_splash/supported_platform.dart:28:3)
#6      createSplash (package:flutter_native_splash/flutter_native_splash.dart:17:3)
#7      main (file:///home/baguskto/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-1.1.7+1/bin/create.dart:5:3)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
pub finished with exit code 255
@jonbhanson
