### ISSUE TITLE
Splash screen extends outside safe area and overlays menu at top of screen

### ISSUE THREAD

**Issue by betapro** [jonbhanson/flutter_native_splash#164]
Is there is a way to keep the splash screen from extending outside the safe area and overlaying the menu at the top of the screen?

**Comment by jonbhanson** [comment]
I think `fullscreen: false` in your `pubspec.yaml` is what you are looking for.

**Comment by betapro** [comment]
Thank you for your reply. However, this does not work. The splash screen momentarily does not overlay the menu, but then does (even with 'fullscreen' explicitly set to true or false, or not set at all (default = false).

**Comment by jonbhanson** [comment]
@betapro can you post a video that shows what you mean?

**Comment by Fcode4** [comment]
Have you solved this problem? Also met

> Thank you for your reply. However, this does not work. The splash screen momentarily does not overlay the menu, but then does (even with 'fullscreen' explicitly set to true or false, or not set at all (default = false).

**Comment by jonbhanson** [comment]
On what platform is this occurring?  Also, if you could provide a video it would be helpful.

**Comment by jonbhanson** [comment]
I tried a test, but I did not see the splash screen overlaying the status bar:
https://user-images.githubusercontent.com/32202698/116881586-6f6fd480-abf1-11eb-95c3-7e65fe1db6af.mp4

**Comment by betapro** [comment]
Hi Jon

 

I'm talking about the black bar in Step 2 below being overlayed! 

 

Thanks, Mike.

 

---------------------------------------------------------------------------------------------------------------------------

Step 1 - Before the app starts running.



 

---------------------------------------------------------------------------------------------------------------------------

Step 2 - App starts running and the black bar (shown below) should remain black throughout the life of the app. The safe area would be below the black bar, and not include it.



 

---------------------------------------------------------------------------------------------------------------------------

Step 3 - The black bar is now overlayed with the light blue color from the splash screen.



 

---------------------------------------------------------------------------------------------------------------------------

Step 4 - What should still be a black bar at the top of the screen (as shown in Step 2) is again overlayed, this time with the dark blue color of the Flutter Demo Home Page.



 

Setting a safe area should not overlay anything text or color over the black bar!

**Comment by jonbhanson** [comment]
The reason it appears that Flutter is not respecting the safe area in step 2 is because Flutter is rendering the status bar as partially transparent; thus the background color shows through.
Unfortunately, the transparency is [hard coded](https://github.com/flutter/engine/blob/5e50f4bad3d5f39997b43e69d176e0abc3f668d9/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L526) in the Android Flutter implementation.  There is an [open issue](https://github.com/flutter/flutter/issues/64001) on Flutter regarding this status bar color change.  Please give a thumbs up on that ticket to give it more visibility.

**Comment by betapro** [comment]
Closing issue - see above comment by jonbhanson.
