### ISSUE TITLE
pub get error

### ISSUE THREAD

**Issue by vptcnt** [jonbhanson/flutter_native_splash#166]
**Describe the bug**
The plugin `flutter_native_splash` doesn't have a main class defined in /Users/vince/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-1.1.8+3/android/src/main/java/net/jonhanson/flutter_native_splash/FlutterNativeSplash.java or /Users/vince/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-1.1.8+3/android/src/main/kotlin/net/jonhanson/flutter_native_splash/FlutterNativeSplash.kt. This is likely to due to an incorrect `androidPackage: net.jonhanson.flutter_native_splash` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile. 

**To Reproduce**
1. Add flutter_native_splash: ^1.1.8+3 to dev_dependencies
2. flutter pub get

**Device (please complete the following information):**
 - Device: Mac

**Flutter doctor**
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.0.5 at /Users/vince/fvm/versions/stable
    • Framework revision adc687823a (4 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /Users/vince/Library/Android/sdk
    • Platform android-30, build-tools 31.0.0-rc1
    • ANDROID_HOME = /Users/vince/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/vince/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)

**Comment by zezo357** [comment]
same problem

**Comment by jonbhanson** [comment]
Sorry, I pushed out a bad update this afternoon.  It should be resolved now.  Just to be safe, run a `flutter clean` before you `pub get`.
