### ISSUE TITLE
White Flash in between splash screens

### ISSUE THREAD

**Issue by Jamesfleming1** [jonbhanson/flutter_native_splash#170]
I set up the native splash screen and my own simple custom splash screen.
When the native splash screen runs it flashes white and then it runs my custom splash screen. I made the splash screen the same image and it is not white so the flash is quite noticeable and jarring for a first user experience. 

**To Reproduce**

My custom splash screen is quite basic 

 Widget splash(BuildContext context) {
    return FutureBuilder(
        future: Future.delayed(Duration(seconds: 3)),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return Scaffold(
              body: Image.asset(
                'images/mountain.png',
                fit: BoxFit.cover,
                height: double.infinity,
                width: double.infinity,
              ),
            );
          } else {
            return isLoggedIn ? NavigationContainer() : LoginScreen();
          }
        });

**Expected behavior**
I would have expected the splash screens to seamlessly roll into one another 

**Device (please complete the following information):**
 - Device: Iphone 12 max simulator

**Comment by jonbhanson** [comment]
Please try uninstalling your app, powering off your emulated device, power back on, and then try reinstalling.
[Reference](https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update)

**Comment by Jamesfleming1** [comment]
I have tried all of that and there is still a very noticeable white flash in-between the native splash screen and my secondary splash screen. There is no white before the native splash screen, but I'm wondering if there is anyway to remove the white inbetween the two splash screens. Its as if my flutter splash screen is not loading quickly enough. My splash screen is an image covering the full screen.

**Comment by jonbhanson** [comment]
Can you provide a video of this white flash event?

**Comment by jonbhanson** [comment]
> Its as if my flutter splash screen is not loading quickly enough.

I would recommend making a test where your `main()` returns a `Container(color: Colors.black);`. If the white flash goes away, it will show that your splash screen is not loading fast enough.

**Comment by Jamesfleming1** [comment]
Okay I ran the test where my secondary splash screen is just a black container. There was no flash if my main directly returned this. However even if I just returned a black container in my splash screen there was a white flash. Meaning that it is  not a problem of loading the image, but problem that my splash screen is not the very first thing returned by my app.

**Comment by Jamesfleming1** [comment]
I also use https://pub.dev/packages/animated_splash_screen I think its actually the problem is there splash page creates the white flash, thanks for the help tho.

**Comment by jonbhanson** [comment]
Good luck. 👍🏻
