### ISSUE TITLE
On real iOS device, shows white screen momentarily before showing desired splash screen.

### ISSUE THREAD

**Issue by jabedamin** [jonbhanson/flutter_native_splash#172]
Description:
When running my flutter app on a real iOS device, initially a white screen appears before showing the configured splash screen. Behaviour meanwhile on a real Android device works as expected. 

**To Reproduce**
1. install flutter_native_splash package
2. add the following code in pubspec.yaml:
flutter_native_splash:
  color: "#00d1a9"
  image: assets/images/logo.png
  android: true
  ios: true

3. from terminal run > flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
2. run flutter app on a real iOS device

**Expected behavior**
Immediately show splash screen with configured color and logo, which does not happen for iOS, instead a white screen appears before.

**Screenshots**

**Device**
 - Device: iPhone XS
 - OS: iOS 14.4.2

**Flutter doctor**
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)
    • Flutter version 2.0.1 at /Users/jamin/Documents/FUTURE/JABI/Engineering/Flutter/SDK/flutter
    • Framework revision c5a4b4029c (10 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jamin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • SM A107F (mobile) •               • android-arm    • Android 10 (API 29)
    • Jabed XS (mobile) • ios            • iOS 14.4.2
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

**Comment by jonbhanson** [comment]
Please try uninstalling your app, powering off your emulated device, power back on, and then try reinstalling.
[Reference](https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update)
