### ISSUE TITLE
pub finished with exit code 64

### ISSUE THREAD

**Issue by alpha0304** [jonbhanson/flutter_native_splash#176]
kung fu panda@DESKTOP-F6U2SBD MINGW64 ~/Desktop/basic assets for apps/splashscreen/splashscreen
$ flutter pub run flutter_native_splash:create
Unhandled exception:
type 'Null' is not a subtype of type 'Map<dynamic, dynamic>'
#0      getConfig (package:flutter_native_splash/flutter_native_splash.dart:125:13)  
#1      createSplash (package:flutter_native_splash/flutter_native_splash.dart:20:16)
#2      main (file:///C:/src2/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-1.1.8+4/bin/create.dart:5:3)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
pub finished with exit code 255

**Comment by jonbhanson** [comment]
Please post your config.

**Comment by jonbhanson** [comment]
Feel free to reopen with the requested config info if you still have this problem.
