### ISSUE TITLE
The logo doesn't fit nicely on android as it does on IOS

### ISSUE THREAD

**Issue by nneemmrr** [jonbhanson/flutter_native_splash#177]
**Describe the bug**!
Splash screen works perfectly on IOS but doesn't work on android as it should!
**To Reproduce**
When Opening the App on IOS it just works, But in Android it looks like my logo is fit to the screen.

**Expected behavior**
it should work on both as expected 

**Screenshots**
![WhatsApp Image 2021-05-31 at 3 39 57 PM (1)](https://user-images.githubusercontent.com/60761933/120214130-57ad5f80-c234-11eb-88e2-bedcc49a979f.jpeg)

**Devices
- works perfectly on Iphone 7 IOS 14.5 and Simulator Iphone 12 Pro Max IOS 14.5
- Doesn't work as shown in screenshots on Mi note 10 lite , android 11
**Flutter doctor**
- i will share doctor log of my pc which i ran the app on the android phone from:

 [√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
   • Flutter version 2.0.6 at C:\src\flutter
   • Framework revision 1d9032c7e1 (5 weeks ago), 2021-04-29 17:37:58 -0700
   • Engine revision 05e680e202
   • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Macgyver\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\Macgyver\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 91.0.864.37

• No issues found!

- this is also doctor log of my mac but i don't use android on it

[✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F71 darwin-arm, locale en-EG)
    • Flutter version 2.2.0 at /Users/omarelnemr/flutter
    • Framework revision b22742018b (2 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/omarelnemr/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[!] Connected device
    ! Error: neemmrr is not connected. Xcode will continue when neemmrr is connected. (code -13)

! Doctor found issues in 2 categories.

**Comment by jonbhanson** [comment]
@nneemmrr please post your config.

**Comment by nneemmrr** [comment]
> @nneemmrr please post your config.

what config?

**Comment by jonbhanson** [comment]
Your `flutter_native_splash` section from `pubspec.yaml` or `flutter_native_splash.yaml`

**Comment by nneemmrr** [comment]
i used flutter_native_splash.yaml and this is the file : 
```
flutter_native_splash:
  image: assets/images/splashscreen.png
  color: "FAFAFA"
  fill: true
  android: true
  ios: true
```

**Comment by nneemmrr** [comment]
> i used flutter_native_splash.yaml and this is the file :
> 
> ```
> flutter_native_splash:
>   image: assets/images/splashscreen.png
>   color: "FAFAFA"
>   fill: true
>   android: true
>   ios: true
> ```

i also made fill to false and rerun it to generate native splash screen and it still doesn't work

**Comment by jonbhanson** [comment]
The `fill` parameter has been deprecated and replaced with `android_gravity` and `ios_content_mode`, which you can read about in the documentation.  What you are experiencing is the exact reason why there are two separate parameters for Android and iOS, because they do not have the same options for sizing an image.

**Comment by nneemmrr** [comment]
Thanks !
