### ISSUE TITLE
background image size for different devices

### ISSUE THREAD

**Issue by johnareid54** [jonbhanson/flutter_native_splash#179]
**Is your feature request related to a problem? Please describe.**
I am using a background image, but the image looks terrible on either the iPhone or iPad depending on size on image used.

**Describe the solution you'd like**
Option to use different images depending on device i.e. phone or tablet.

**Comment by jonbhanson** [comment]
Please post your `flutter_native_splash` config in your `pubspec.yaml` file.  What is the resolution of the image that you are using?  What you say it looks terrible, what does that mean?  Is the image pixilated or stretched or aliased or something else?

**Comment by johnareid54** [comment]
Hi, 

Yaml file:
**flutter_native_splash.ymal**

flutter_native_splash:

  background_image: "assets/system/background.png"


The image is: width: 400 pixel, height: 486 pixel 
![image](https://user-images.githubusercontent.com/53974881/121036450-ac0d8d80-c7a6-11eb-885b-d13efacfbaf0.png)

It looks fine on the phone, but on the iPad the image is stretched.  If I resize for the iPad (i.e. wider picture) then it looks bad o the phone.

I guess one solution is to use some abstract image rather than a real photo.

**Comment by jonbhanson** [comment]
Check the `ios_content_mode` option, which sets iOS's [content mode](https://developer.apple.com/documentation/uikit/uiview/contentmode) and determines how the image is displayed.  I think a different mode will give you better results.

**Comment by johnareid54** [comment]
Thanks @jonbhanson 

Will have a play around with it this week!

**Comment by alexanderbelokon-mway** [comment]
What is the best practice here? We still have very poor quality on iPad

**Comment by jonbhanson** [comment]
@alexanderbelokon-mway what is the resolution of your source image?  Can you post a screenshot of the splash screen?

**Comment by ArturoRen** [comment]
What is the best practice here?
