### ISSUE TITLE
 AAPT: error: style attribute 'android:attr/windowSplashScreenBackground' not found.

### ISSUE THREAD

**Issue by anilbhomi** [jonbhanson/flutter_native_splash#181]
**Describe the bug**
 AAPT: error: style attribute 'android:attr/windowSplashScreenBackground' not found.

**To Reproduce**
1. Add flutter_native_splash dependency
2. Add flutter_native_splash.yaml
3. enable android12
4. Run the application

**Expected behavior**
windowSplashScreenBackground attr on style class should be imported

**Screenshots**
![image](https://user-images.githubusercontent.com/34730899/121779931-c936c780-cbbd-11eb-8629-51c2dbf05696.png)

**Comment by jonbhanson** [comment]
Did you follow the step described in [Set up the Android 12 SDK](https://developer.android.com/about/versions/12/setup-sdk)?

**Comment by jonbhanson** [comment]
I am closing this due to missing feedback.  Feel free to reopen with a response to the question above if you are still having a problem.
