### ISSUE TITLE
Different splash image for tablets?

### ISSUE THREAD

**Issue by gadgetreviews** [jonbhanson/flutter_native_splash#182]
This plugin works good for vertical devices such as phones. But if you use it on a horizontal device such as a tablet, splash screen is stretched to tablet size and it is not what I want.

I guess there should be horizontal device image option.

**Comment by jonbhanson** [comment]
The native splash is limited to the respective options for the native platform that you are using.  Check out the `android_gravity`, `ios_content_mode`, and `web_image_mode` parameters for the options on your platform.

**Comment by jonbhanson** [comment]
Feel free to reopen if you have more feedback or questions.

**Comment by BLB-EN438** [comment]
@gadgetreviews did found a solution for tablet screen?

**Comment by jonbhanson** [comment]
FYI there is a new parameter `android_screen_orientation` that would allow you to set the orientation to horizontal.

**Comment by BLB-EN438** [comment]
Can we do this programmatically ? Based on screen size.

**Comment by jonbhanson** [comment]
> Working but image looks blur. Can we do this programmatically ? Based on screen size.

Unfortunately this is not possible.

**Comment by fizz-viva** [comment]
> Working but image looks blur. Can we do this programmatically ? Based on screen size.

@BLB-EN438 did you find any way around for blurry splash logo in Tablet?
