### ISSUE TITLE
white screen, between splash screen and app

### ISSUE THREAD

**Issue by sahmirzali** [jonbhanson/flutter_native_splash#183]
**Describe the bug**

there is have a white screen, between splash screen and app. how can I solve this problem? 

  

**Expected behavior**
I don't want to this white screen

**Screenshots**

https://user-images.githubusercontent.com/40922460/123523899-f44e0a80-d6d7-11eb-8bab-354c3f7609ef.mov

**Device (please complete the following information):**
 - Device: [e.g. iPhone611]
 - OS: [e.g. iOS 14.5 simulator]

**Flutter doctor**
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F71 darwin-x64, locale en-AZ)
    • Flutter version 2.2.0 at /Users/shahmirzali/Development/flutter
    • Framework revision b22742018b (6 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/shahmirzali/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • BEA3DE1D-CF21-4F28-8BF3-DE9A90E56C0E • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      91.0.4472.114

• No issues found!

**Comment by sahmirzali** [comment]
flutter_native_splash:
 
  color: "#17698F"
  #background_image: "assets/scr1.png"
  
  ios_content_mode: scaleToFill
 
  image: assets/scr1.png
  android: true
  ios: true

**Comment by jonbhanson** [comment]
I have two suggestions:
1. It may be caused by an [iOS splash caching bug](https://stackoverflow.com/questions/33002829/ios-keeping-old-launch-screen-and-app-icon-after-update), which can be solved by uninstalling your app, powering off your device, power back on, and then try reinstalling.
2. It may be caused by the delay due to initialization in your app.  To test this, make a test where your `main()` returns a `Container(color: Colors.black);`. If the white flash goes away, it will show that your content is not loading fast enough.  You could solve this by creating a [secondary splash screen](https://pub.dev/packages/flutter_native_splash#secondary-splash-screen) or loading a barebones version of your app with placeholders, and then populate the placeholders as content loads.

**Comment by sahmirzali** [comment]
yes you are right, i have this async process in main() .  

`Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  runApp(
    ProviderScope(
      child: MyApp(),
    ),
  );
}`

if i use also secondary splash screen  the white screen is disappar or ?

**Comment by sahmirzali** [comment]
also i have question about native splash screen duration , is there have option for that ?

**Comment by jonbhanson** [comment]
These questions are both answered in the [readme](https://pub.dev/packages/flutter_native_splash).

**Comment by sahmirzali** [comment]
Okay, thanks a lot! i'm trying

**Comment by sahmirzali** [comment]
https://user-images.githubusercontent.com/40922460/123525559-ac80b080-d6e2-11eb-8c2b-ead0baef0c89.mov

**Comment by sahmirzali** [comment]
```
`import 'dart:io';

import 'package:araf/home/entry_screen.dart';
import 'package:araf/pages/auth/login.dart';
import 'package:araf/pages/daily_prayer/daily_pray_page.dart';
import 'package:araf/pages/daily_prayer/streak_board_page.dart';
import 'package:araf/pages/main_pages/listen_page.dart';
import 'package:araf/pages/main_pages/see_all_page.dart';
import 'package:araf/pages/player/player_text.dart';
import 'package:araf/pages/player/playlist_page.dart';
import 'package:araf/pages/settings/setting_main.dart';
import 'package:araf/service/firebase_notification_service/firebase_notification.dart';
import 'package:araf/utils/local_datas/shared_prefs.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:pixel_perfect/pixel_perfect.dart';
import 'package:responsive_framework/responsive_wrapper.dart';

import 'utils/constants.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  runApp(
    ProviderScope(
      child: MyApp(),
    ),
  );
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  FirebaseNotifications firebaseNotifications = FirebaseNotifications();
  void initState() {
    context.read(sharedPrefsProvider).getFirstTimeValue();
    context.read(sharedPrefsProvider).getSecondTimeValue();
    print('init ${SharedPrefs().first}   ----   ${SharedPrefs().second}');
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      firebaseNotifications.setupFirebase(context);
    });
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: Future.delayed(Duration(seconds: 3)),
      builder: (context, AsyncSnapshot snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return MaterialApp(home: Splash());
        } else {
          // Loading is done, return the app:
          return MaterialApp(
            color: Colors.blue,
            //   theme: Theme.of(context).copyWith(
            // appBarTheme: Theme.of(context)
            //     .appBarTheme
            //     .copyWith(brightness: Brightness.light)),

            builder: (context, child) {
              return ResponsiveWrapper.builder(
                child,
                maxWidth: 1200,
                minWidth: 480,
                defaultScale: true,
                breakpoints: [
                  // ResponsiveBreakpoint.autoScaleDown(300, name: MOBILE, scaleFactor: 0.57),
                  ResponsiveBreakpoint.resize(
                    480,
                    name: MOBILE,
                    scaleFactor: 1.5,
                  ),
                  ResponsiveBreakpoint.resize(
                    600,
                    name: TABLET,
                    scaleFactor: 1.2,
                  ),
                  ResponsiveBreakpoint.resize(
                    800,
                    name: TABLET,
                    scaleFactor: 1.3,
                  ),
                  ResponsiveBreakpoint.resize(
                    1000,
                    name: TABLET,
                    scaleFactor: 1.5,
                  ),
                  ResponsiveBreakpoint.autoScale(
                    1000,
                    name: DESKTOP,
                    scaleFactor: 1.5,
                  ),
                ],
                //  background: ,
              );
            },

            debugShowCheckedModeBanner: false,
            title: Constants.appName,
            theme: ThemeData.light().copyWith(
              pageTransitionsTheme: PageTransitionsTheme(
                builders: {
                  TargetPlatform.android: CupertinoPageTransitionsBuilder(),
                  TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
                },
              ),
              appBarTheme: AppBarTheme.of(context).copyWith(
                textTheme: GoogleFonts.openSansTextTheme(),
              ),
              textTheme: GoogleFonts.openSansTextTheme(),
            ),
            // home: PixelPerfect(
            //   scale: 1.72,
            //   assetPath: 'assets/images/modul.png',
            //   child: EntryScreen(),
            // ),

            home: ListenPage(),
          );
        }
      },
    );
  }
}

class Splash extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.indigoAccent,
      body: Center(
        child: Icon(
          Icons.apartment_outlined,
          size: MediaQuery.of(context).size.width * 0.785,
        ),
      ),
    );
  }
}
`
````import 'dart:io';

import 'package:araf/home/entry_screen.dart';
import 'package:araf/pages/auth/login.dart';
import 'package:araf/pages/daily_prayer/daily_pray_page.dart';
import 'package:araf/pages/daily_prayer/streak_board_page.dart';
import 'package:araf/pages/main_pages/listen_page.dart';
import 'package:araf/pages/main_pages/see_all_page.dart';
import 'package:araf/pages/player/player_text.dart';
import 'package:araf/pages/player/playlist_page.dart';
import 'package:araf/pages/settings/setting_main.dart';
import 'package:araf/service/firebase_notification_service/firebase_notification.dart';
import 'package:araf/utils/local_datas/shared_prefs.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:pixel_perfect/pixel_perfect.dart';
import 'package:responsive_framework/responsive_wrapper.dart';

import 'utils/constants.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  runApp(
    ProviderScope(
      child: MyApp(),
    ),
  );
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  FirebaseNotifications firebaseNotifications = FirebaseNotifications();
  void initState() {
    context.read(sharedPrefsProvider).getFirstTimeValue();
    context.read(sharedPrefsProvider).getSecondTimeValue();
    print('init ${SharedPrefs().first}   ----   ${SharedPrefs().second}');
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      firebaseNotifications.setupFirebase(context);
    });
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: Future.delayed(Duration(seconds: 3)),
      builder: (context, AsyncSnapshot snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return MaterialApp(home: Splash());
        } else {
          // Loading is done, return the app:
          return MaterialApp(
            color: Colors.blue,
            //   theme: Theme.of(context).copyWith(
            // appBarTheme: Theme.of(context)
            //     .appBarTheme
            //     .copyWith(brightness: Brightness.light)),

            builder: (context, child) {
              return ResponsiveWrapper.builder(
                child,
                maxWidth: 1200,
                minWidth: 480,
                defaultScale: true,
                breakpoints: [
                  // ResponsiveBreakpoint.autoScaleDown(300, name: MOBILE, scaleFactor: 0.57),
                  ResponsiveBreakpoint.resize(
                    480,
                    name: MOBILE,
                    scaleFactor: 1.5,
                  ),
                  ResponsiveBreakpoint.resize(
                    600,
                    name: TABLET,
                    scaleFactor: 1.2,
                  ),
                  ResponsiveBreakpoint.resize(
                    800,
                    name: TABLET,
                    scaleFactor: 1.3,
                  ),
                  ResponsiveBreakpoint.resize(
                    1000,
                    name: TABLET,
                    scaleFactor: 1.5,
                  ),
                  ResponsiveBreakpoint.autoScale(
                    1000,
                    name: DESKTOP,
                    scaleFactor: 1.5,
                  ),
                ],
                //  background: ,
              );
            },

            debugShowCheckedModeBanner: false,
            title: Constants.appName,
            theme: ThemeData.light().copyWith(
              pageTransitionsTheme: PageTransitionsTheme(
                builders: {
                  TargetPlatform.android: CupertinoPageTransitionsBuilder(),
                  TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
                },
              ),
              appBarTheme: AppBarTheme.of(context).copyWith(
                textTheme: GoogleFonts.openSansTextTheme(),
              ),
              textTheme: GoogleFonts.openSansTextTheme(),
            ),
            // home: PixelPerfect(
            //   scale: 1.72,
            //   assetPath: 'assets/images/modul.png',
            //   child: EntryScreen(),
            // ),

            home: ListenPage(),
          );
        }
      },
    );
  }
}

class Splash extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.indigoAccent,
      body: Center(
        child: Icon(
          Icons.apartment_outlined,
          size: MediaQuery.of(context).size.width * 0.785,
        ),
      ),
    );
  }
}
`

**Comment by sahmirzali** [comment]
`import 'dart:io';

import 'package:araf/home/entry_screen.dart';
import 'package:araf/pages/auth/login.dart';
import 'package:araf/pages/daily_prayer/daily_pray_page.dart';
import 'package:araf/pages/daily_prayer/streak_board_page.dart';
import 'package:araf/pages/main_pages/listen_page.dart';
import 'package:araf/pages/main_pages/see_all_page.dart';
import 'package:araf/pages/player/player_text.dart';
import 'package:araf/pages/player/playlist_page.dart';
import 'package:araf/pages/settings/setting_main.dart';
import 'package:araf/service/firebase_notification_service/firebase_notification.dart';
import 'package:araf/utils/local_datas/shared_prefs.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:pixel_perfect/pixel_perfect.dart';
import 'package:responsive_framework/responsive_wrapper.dart';

import 'utils/constants.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  runApp(
    ProviderScope(
      child: MyApp(),
    ),
  );
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  FirebaseNotifications firebaseNotifications = FirebaseNotifications();
  void initState() {
    context.read(sharedPrefsProvider).getFirstTimeValue();
    context.read(sharedPrefsProvider).getSecondTimeValue();
    print('init ${SharedPrefs().first}   ----   ${SharedPrefs().second}');
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      firebaseNotifications.setupFirebase(context);
    });
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: Future.delayed(Duration(seconds: 3)),
      builder: (context, AsyncSnapshot snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return MaterialApp(home: Splash());
        } else {
          // Loading is done, return the app:
          return MaterialApp(
            color: Colors.blue,
            //   theme: Theme.of(context).copyWith(
            // appBarTheme: Theme.of(context)
            //     .appBarTheme
            //     .copyWith(brightness: Brightness.light)),

            builder: (context, child) {
              return ResponsiveWrapper.builder(
                child,
                maxWidth: 1200,
                minWidth: 480,
                defaultScale: true,
                breakpoints: [
                  // ResponsiveBreakpoint.autoScaleDown(300, name: MOBILE, scaleFactor: 0.57),
                  ResponsiveBreakpoint.resize(
                    480,
                    name: MOBILE,
                    scaleFactor: 1.5,
                  ),
                  ResponsiveBreakpoint.resize(
                    600,
                    name: TABLET,
                    scaleFactor: 1.2,
                  ),
                  ResponsiveBreakpoint.resize(
                    800,
                    name: TABLET,
                    scaleFactor: 1.3,
                  ),
                  ResponsiveBreakpoint.resize(
                    1000,
                    name: TABLET,
                    scaleFactor: 1.5,
                  ),
                  ResponsiveBreakpoint.autoScale(
                    1000,
                    name: DESKTOP,
                    scaleFactor: 1.5,
                  ),
                ],
                //  background: ,
              );
            },

            debugShowCheckedModeBanner: false,
            title: Constants.appName,
            theme: ThemeData.light().copyWith(
              pageTransitionsTheme: PageTransitionsTheme(
                builders: {
                  TargetPlatform.android: CupertinoPageTransitionsBuilder(),
                  TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
                },
              ),
              appBarTheme: AppBarTheme.of(context).copyWith(
                textTheme: GoogleFonts.openSansTextTheme(),
              ),
              textTheme: GoogleFonts.openSansTextTheme(),
            ),
            // home: PixelPerfect(
            //   scale: 1.72,
            //   assetPath: 'assets/images/modul.png',
            //   child: EntryScreen(),
            // ),

            home: ListenPage(),
          );
        }
      },
    );
  }
}

class Splash extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.indigoAccent,
      body: Center(
        child: Icon(
          Icons.apartment_outlined,
          size: MediaQuery.of(context).size.width * 0.785,
        ),
      ),
    );
  }
}
`

**Comment by sahmirzali** [comment]
I tried but the white screen not disappear 😔😞

**Comment by sahmirzali** [comment]
also i did flutter clean , pub get ...

**Comment by sahmirzali** [comment]
i think it's for responsive_framework, i got you, thanks for supporting, you can close , if I have question I will ask in here

**Comment by jonbhanson** [comment]
OK, good luck.  👍🏻

**Comment by jabirmayar** [comment]
> 
> 
> i think it's for responsive_framework package, i got you, thanks for supporting, you can close , if I have question I will ask in here

hello, how did you solve the issue?

**Comment by sahmirzali** [comment]
@jabirmayar  I removed responsive_framework package

**Comment by jabirmayar** [comment]
> 
> 
> @jabirmayar I removed responsive_framework package

have you used any alternative for it?

**Comment by sahmirzali** [comment]
@jabirmayar no. I make responsive myself. Mediaquery :D

**Comment by jabirmayar** [comment]
> 
> 
> @jabirmayar no. I make responsive myself. Mediaquery :D

ahh ok, thank you for your time.
