### ISSUE TITLE
Second Splash Screen Size issue

### ISSUE THREAD

**Issue by DarkHeros09** [jonbhanson/flutter_native_splash#186]
Hi Jon

First of all thank you for your great work, i really appreciate your effort for creating and maintaining this package.

Now, following your example on the second splash screen the image always appears a little bit bigger than the image in the first native splash screen.
is there a way to know what's the size of the loaded image of the first splash screen to scale the second one accordingly?

Thank you.

**Comment by jonbhanson** [comment]
@DarkHeros09 what platform does your question apply to?

**Comment by DarkHeros09** [comment]
@jonbhanson Android.

**Comment by jonbhanson** [comment]
Give this a try:

```dart
class Splash extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Image.asset(
          'assets/splash.png',
          scale: getClosestAndroidPixelRadio(context),
        ),
      ),
    );
  }
}

double getClosestAndroidPixelRadio(BuildContext context) {
  double pixelRatio = MediaQuery.of(context).devicePixelRatio;
  if (pixelRatio < 1.25) return 1;
  if (pixelRatio < 1.75) return 1.5;
  if (pixelRatio < 2.5) return 2;
  if (pixelRatio < 3.5) return 3;
  return 4;
}
```

**Comment by DarkHeros09** [comment]
@jonbhanson sadly it didn't work, the closest thing i got is to multiply by .710, but i don't know if it'll work on the screen sizes perfectly.

**Comment by jonbhanson** [comment]
@DarkHeros09 what is the device model?

**Comment by DarkHeros09** [comment]
Oneplus 6T.

**Comment by jonbhanson** [comment]
OK, @DarkHeros09, here is a different method that may work for you, using [resolution-aware image assets](https://flutter.dev/docs/development/ui/assets-and-images#resolution-aware).

In your `android/app/src/main/res/drawable-mdpi` folder, you will have a `splash.png`.  This is your 1x image.  ([reference](https://developer.android.com/training/multiscreen/screendensities))  Copy that to your app's assets folder.  Then copy the `splash.png` in `android/app/src/main/res/drawable-hdpi` to a subfolder in your app's assets folder named `1.5x`.  Do the same for the rest of the folders.  The mapping should be:

mdpi -> assets
hdpi -> assets/1.5x
xhdpi -> assets/2.0x
xxhdpi -> assets/3.0x
xxxhdpi -> assets/4.0x

Finally, in flutter display your image like this:
```dart
Image.asset('assets/splash.png')
```

Please let me know if it works.

**Comment by DarkHeros09** [comment]
@jonbhanson yeah it worked perfectly, although my app size increased a little bit due to duplication of assets, none of the less thank you for your time helping.

sorry for my late reply, again thank you.

**Comment by jonbhanson** [comment]
Glad it worked for you.  Best of luck!

**Comment by dvagala** [comment]
Just point out you can basically just divide splash.png size by 4. (At least working for me, tested on 6 devices Android/iOS)

E.g.: if splash.png 600px wide, in your second splash screen:

```
 Center(
                child: Image.asset(
                  'assets/splash.png',
                  width: 600 / 4,
                ),
              ),
```
