### ISSUE TITLE
error when run

### ISSUE THREAD

**Issue by MohammedSalehelShazly** [jonbhanson/flutter_native_splash#187]
Task :app:processDebugResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> Android resource linking failed
C:\Users\user\AndroidStudioProjects\clock_app\android\app\src\main\res\values-v31\styles.xml:4:5-7:13: AAPT: error: style attribute 'android:attr/windowSplashScreenBackground' not found.

**Comment by jonbhanson** [comment]
Are you using the Android 12 beta?  If so, did you [set up the Android 12 SDK](https://developer.android.com/about/versions/12/setup-sdk)?

**Comment by noskap** [comment]
Same issue. Android S x86_64

**Comment by jonbhanson** [comment]
> AAPT: error: style attribute 'android:attr/windowSplashScreenBackground' not found.

This attribute is only found in Android S, so if you are getting this error, it means your project is not fully set up for Android S.  Did you [update your app's build configuration](https://developer.android.com/about/versions/12/setup-sdk#config)?

**Comment by jonbhanson** [comment]
Closing ticket due to inactivity.  Feel free to reopen if you are still having a problem.
