### ISSUE TITLE
Add option to specify splash screen orientations

### ISSUE THREAD

**Issue by TheGrinch00** [jonbhanson/flutter_native_splash#188]
**Is your feature request related to a problem? Please describe.**
I noticed that when I open my app while holding my phone in landscape, the splashscreen shows also in landscape while the app is forced to be in portrait (Only tested in Android, not iOS)

**Describe the solution you'd like**
It would be awsome if in the `pubspec.yaml` I could specify a set of orientations allowed for the splashscreen

**Comment by jonbhanson** [comment]
I am not sure if there is enough demand to justify adding this option.  Anyone feel free to thumbs up this issue if you'd like to see it.  In the meantime, here is how you force the splash screen to portrait: In your `andoid/app/src/main/AndroidManifest.xml` file, you can set the `screenOrientation` to `portrait `. It would look something like this in the XML:

```xml
<activity
    android:name=".MainActivity"
    android:[screenOrientation](https://developer.android.com/guide/topics/manifest/activity-element#screen)="portrait">
    ...
</activity>
```

This will lock the screen orientation for both the splash screen and the entire application.

**Comment by jonbhanson** [comment]
There doesn't seem to be much demand for this feature.

**Comment by erperejildo** [comment]
Any plans to add this @jonbhanson ? My app is used just in landscape and displaying the splashscreen in portrait doesn't look good

**Comment by jonbhanson** [comment]
@erperejildo I don't have plans to add this.  It would require someone else to code the feature and make a pull request.
