### ISSUE TITLE
Error on building android when using jpg background

### ISSUE THREAD

**Issue by crizant** [jonbhanson/flutter_native_splash#190]
**Describe the bug**
I see the following error when building android:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > Android resource compilation failed
        /Users/xxx/Documents/my_app/android/app/src/main/res/drawable/background.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.

        /Users/xxx/Documents/my_app/android/app/src/main/res/drawable/background.png: AAPT: error: file failed to compile.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > Android resource compilation failed
        /Users/xxx/Documents/my_app/android/app/src/main/res/drawable-v21/background.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.

        /Users/xxx/Documents/my_app/android/app/src/main/res/drawable-v21/background.png: AAPT: error: file failed to compile.
```

**To Reproduce**
1. Use a jpg image as splash image
2. Setup `pubspec.yaml` and run the command of this package
3. Run "flutter build apk"

I think the error comes from the package directly copies the image and renames to `background.png` without really converting it into a `.png` file.

**Comment by jonbhanson** [comment]
@crizant the JPG file format is not supported by this package.

**Comment by crizant** [comment]
oh thanks, then I suggest adding a check before copying

**Comment by jonbhanson** [comment]
@crizant thanks for the suggestion.

**Comment by jonbhanson** [comment]
In order to find out what file formats are most needed by the community, I have opened a single ticket to capture all image format requests.  Please visit (this ticket)[https://github.com/jonbhanson/flutter_native_splash/issues/245] to vote for the image format you need.
