### ISSUE TITLE
Error when setting PNG for splash screen and running 'flutter pub run flutter_native_splash:create'

### ISSUE THREAD

**Issue by devrobbey** [jonbhanson/flutter_native_splash#192]
```
Unhandled exception:
FileSystemException: Cannot copy file to 'web/splash/img/light-background.png', path = 'assets/background.png' (OS Error: No such file or directory, errno = 2)

```
Error was gone after creating an 'img' directory in web/splash.

[✓] Flutter (Channel master, 2.3.0-17.0.pre.411, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-GB)

**Comment by jonbhanson** [comment]
@devrobbey what version of this package are you using?

**Comment by devrobbey** [comment]
Most current version :)

Jon Hanson ***@***.***> schrieb am Do. 22. Juli 2021 um 13:49:

**Comment by jonbhanson** [comment]
Was there a line number associated with this error?

**Comment by devrobbey** [comment]
1.2.0

Jon Hanson ***@***.***> schrieb am Do. 22. Juli 2021 um 21:35:

**Comment by jonbhanson** [comment]
Thanks, I think I tracked down the source of this error and the next update will fix it.

**Comment by devrobbey** [comment]
Thanks for taking it into account that fast!! :)
