### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by rohitchaurasiya151** [jonbhanson/flutter_native_splash#196]
![Screenshot 2021-08-04 at 3 14 22 PM](https://user-images.githubusercontent.com/43794211/128159858-7c69cc5c-74cb-463d-b597-b8b1eac65624.png)
When I upload the build on the server after the launch of the app I am getting this issue.

 **/splash/img/light-background.png 404**

and when I try to put a custom image with the same name it's showing two images on the splash.  
![Screenshot 2021-08-04 at 3 15 37 PM](https://user-images.githubusercontent.com/43794211/128160426-edff726c-75f2-48a8-ba68-e65cadb0db44.png)

**Comment by jonbhanson** [comment]
Is the `light-background.png` in the `web/splash/img` folder on your dev machine?  Is it also present on the server?

**Comment by jonbhanson** [comment]
Feel free to reopen if you are still having trouble.

**Comment by Techno-Disaster** [comment]
This is still a issue, there is no light-background.png or dark-background.png generated

**Comment by jonbhanson** [comment]
What version of the package are you using?

**Comment by Techno-Disaster** [comment]
> What version of the package are you using?

tested on 1.2.2 and 1.2.1

**Comment by jonbhanson** [comment]
Is the `light-background.png` in the `web/splash/img` folder on your dev machine?  Is it also present on the server?

**Comment by Techno-Disaster** [comment]
> Is the `light-background.png` in the `web/splash/img` folder on your dev machine? Is it also present on the server?

nope, as I said, it wasn't generated.

**Comment by jonbhanson** [comment]
Is there any error message that appears when you run `flutter pub run flutter_native_splash:create`?

**Comment by jonbhanson** [comment]
Also, can you add your `flutter doctor` output?

**Comment by Techno-Disaster** [comment]
> Is there any error message that appears when you run `flutter pub run flutter_native_splash:create`?

Looks like it occurs because I don't set `background_image` but I use  color so I can't use `background_image` with it.

**Comment by Techno-Disaster** [comment]
> Is there any error message that appears when you run `flutter pub run flutter_native_splash:create`?

Nope

```
[Android] Creating splash images
[Android] Updating android/app/src/main/res/drawable/launch_background.xml with splash image path
[Android] Updating android/app/src/main/res/drawable-night/launch_background.xml with splash image path
[Android] Updating android/app/src/main/res/drawable-v21/launch_background.xml with splash image path
[Android] Updating android/app/src/main/res/drawable-night-v21/launch_background.xml with splash image path
[Android] Updating styles.xml with full screen mode setting
[Android] Updating styles.xml with full screen mode setting
[iOS] Creating splash images
[iOS] Updating LaunchScreen.storyboard with width, and height
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
[Web] Creating images
[Web] Creating images
[Web] Creating CSS
[Web] Updating index.html
```

**Comment by Techno-Disaster** [comment]
> flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on Pop!_OS 21.04 5.13.13-051313-generic, locale en_IN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by jonbhanson** [comment]
Thanks.  One more thing, can you post your config?

**Comment by Techno-Disaster** [comment]
> Thanks. One more thing, can you post your config?

```
flutter_native_splash:
  image: assets/images/splash.png
  color: "#ffffff"
  color_dark: "#252a31"
  ```

**Comment by jonbhanson** [comment]
OK, I found the source of this 404 and I will push out an update soon.
