### ISSUE TITLE
Error when run flutter pub run flutter_native_splash:create

### ISSUE THREAD

**Issue by pedicini** [jonbhanson/flutter_native_splash#197]
When run **flutter pub run flutter_native_splash:create** command from the terminal, it returns the following error:

**Your `flutter_native_splash` section cannot not contain both a `color` and `background_image`.
pub finished with exit code 1**

My pubspec.yaml

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  flutter_appauth: ^2.0.0-dev.2
  http: ^0.13.3
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.2.1
  flutter_launcher_icons: ^0.9.1

flutter_native_splash:
  color: "#000000"
  background_image: "assets/images/logo.png"
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

Thanks in advance

**Comment by jonbhanson** [comment]
The `image_path` parameters sets the splash image.  Behind your splash image, you can have either a solid color or a background image that is stretched over the entire screen, such as a gradient background.  In your case it looks like you want a solid black background so remove the `background_image` parameter.

**Comment by jonbhanson** [comment]
Let me know if you have any additional questions.
