### ISSUE TITLE
Waiting too long at splash screen

### ISSUE THREAD

**Issue by themayk** [jonbhanson/flutter_native_splash#200]
It waits for about 7 seconds on the splash page, is it possible to shorten it?

**Comment by pulstar** [comment]
Sometimes my app halt in the splash screen and doesn't load. I need to close it from the system and open it again, then it works.

**Comment by jonbhanson** [comment]
Hope this was helpful for solving your problem.  Feel free to reopen if you are still having trouble.

**Comment by pulstar** [comment]
> @pulstar have you tried my recommendation above?

Not yet. I will try it. Thank you!
