### ISSUE TITLE
Room for customizations

### ISSUE THREAD

**Issue by edkluivert** [jonbhanson/flutter_native_splash#203]
**Is your feature request related to a problem? Please describe.**
There isn't room for customizations of the splash screen

**Describe the solution you'd like**
Being able to design one's own splash screen, I mean letting one building their own splash screen design or you can let one be able to use an animated file like Lottie or animated SVG as their background image

**Describe alternatives you've considered**
Tried altering the android module of the flutter project for the splash screen but the result was what I wanted

**Additional context**
That's it

**Comment by jonbhanson** [comment]
Hello @edkluivert.  Can you explain in more detail what kind of customization you would like to do?

**Comment by edkluivert** [comment]
Hello boss, I edited the issue already. I noticed the library allowed just a background image and background color, there could be more to that. Maybe a room for title text or animating the background image or text. Also there's this thing with the second splash screen, is there a way to resolve that so someone doesn't need to do a secondary splash screen?. Personally I've been trying to implement a splash screen lately, one that has a native feel and I didn't succeed so far. That's all though

**Comment by jonbhanson** [comment]
@edkluivert unfortunately I don't have the bandwidth at the moment to add these types of customizations to the package, but I always welcome PRs!

**Comment by jonbhanson** [comment]
In order to find out what file formats are most needed by the community, I have opened a single ticket to capture all image format requests.  Please visit (this ticket)[https://github.com/jonbhanson/flutter_native_splash/issues/245] to vote for the image format you need.
