### ISSUE TITLE
issue with it resizing the splash screen from flutter_native_splash

### ISSUE THREAD

**Issue by mattjslaton** [jonbhanson/flutter_native_splash#205]
Plugin works great but used responsive plugin and it resizes the splash screen, not sure if there is a way of fixing that

**Comment by jonbhanson** [comment]
What is the platform and can you give a link to ￼the responsive plug-in ?

**Comment by mattjslaton** [comment]
Yes! it seems to be only affecting flutter web, since it thinks the device is smaller, it uses the lowest resolution splash png, so it is smaller, and lower quality, which makes sense if the device was that size. Thanks for taking a look at it

**Comment by jonbhanson** [comment]
There is an update in the latest version that may solve what you are seeing. Try updating to version `1.2.3`, run `flutter pub get`, run `flutter pub run flutter_native_splash:create`, and see if the problem still remains.

**Comment by mattjslaton** [comment]
Unfortunately still the same issue. Apparently the resize issue is a known issue with flutter web, maybe I can figure out a work around or only use the splash on mobile.

**Comment by jonbhanson** [comment]
Here is something to try:
In your `web/index.html`, if your body tag is simply `<body>`, try changing it to:
```html
<body style="position: fixed; inset: 0px; overflow: hidden; padding: 0px; margin: 0px; user-select: none; touch-action: none; font: 14px sans-serif; color: red;">
```

**Comment by mdeandrea-mrmilu** [comment]
When use `<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>` Flutter throw a warning:

WARNING: found an existing <meta name="viewport"> tag. Flutter Web uses its own viewport configuration for better compatibility with Flutter. This tag will be replaced.
