### ISSUE TITLE
A splash screen was provided to Flutter, but this is deprecated.

### ISSUE THREAD

**Issue by jesselpereira** [jonbhanson/flutter_native_splash#207]
**The warning**
W/FlutterActivityAndFragmentDelegate( 7041): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.

**When it appeared**
Since Flutter 2.5

Any ideas about this notice?

**Comment by jonbhanson** [comment]
This question is answered in the FAQ in the readme. 👍🏻

**Comment by jesselpereira** [comment]
> This question is answered in the FAQ in the readme. 👍🏻

Thank you.

**Comment by jesselpereira** [comment]
Hi, removing this piece of code throws an exception that crashes the app (#89813). After putting back the code, the app works normally.

**Comment by fredgrott** [comment]
as far s Iknow you remove the meta tag for splash in the manifest not any code. The flutter create run beofer  the 2.5 update would have created a meta entry for splash in the android manifest which is why you only need to remover that meta splash entry in the manifest to fix it.

**Comment by fredgrott** [comment]
I was slightly worn hereis the correct way to fix things:
MainActivity.kt hs to be this:
```kotlin
package io.github.fredgrott.suggested_layout_arch

import android.os.Build
import android.os.Bundle
import androidx.core.view.WindowCompat
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        // Aligns the Flutter view vertically with the window.
        WindowCompat.setDecorFitsSystemWindows(window, false)

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            // Disable the Android splash screen fade out animation to avoid
            // a flicker before the similar frame is drawn in Flutter.
            splashScreen.setOnExitAnimationListener { splashScreenView -> splashScreenView.remove() }
        }

        super.onCreate(savedInstanceState)
    }
}
```

and both 31 xmls values and vlause-night in res:
comment out this line
<item name="android:windowSplashScreenBackground">@drawable/launch_background</item>

Once you do that everything compiels fine and works

**Comment by nyck33** [comment]
so just ignore it?

**Comment by jonbhanson** [comment]
Hi @jesselpereira, is it safe to assume that your issue has been solved?

**Comment by jesselpereira** [comment]
> Hi @jesselpereira, is it safe to assume that your issue has been solved?

Yes.
