### ISSUE TITLE
Dart 2.12.3 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.

### ISSUE THREAD

**Issue by jijkbird** [jonbhanson/flutter_native_splash#208]
flutter pub run flutter_native_splash:remove
Dart 2.12.3 is incompatible with your dependencies' SDK constraints. Please run "pub get" again.
pub finished with exit code 65

**Comment by jonbhanson** [comment]
I am not able to reproduce.  Can you provide your flutter doctor?

**Comment by jonbhanson** [comment]
Feel free to reopen if you still have a problem.
