### ISSUE TITLE
transparency decrease

### ISSUE THREAD

**Issue by SteveSuv** [jonbhanson/flutter_native_splash#210]
When the splash disappears, the transparency will slowly decrease, resulting in the exposure of the middle picture. Can I directly make the page disappear without the transition of transparency

![Screenshot_2021-09-12-11-58-17-368_com.example.fluster.jpg](https://user-images.githubusercontent.com/35391006/132971552-d0477d98-d83f-4090-9e3f-f5975a0fba96.jpg)

**Comment by jonbhanson** [comment]
There is an example that removes the fade effect on [Flutter's splash screen documentation](https://flutter.dev/docs/development/ui/advanced/splash-screen?tab=android-splash-alignment-java-tab#android-s).

**Comment by jonbhanson** [comment]
Feel free to reopen if you still have a problem.
