### ISSUE TITLE
White screen as well as splash??

### ISSUE THREAD

**Issue by KudaCoder** [jonbhanson/flutter_native_splash#211]
I've read a lot online that this is an issue and was just wondering if there was a solution you could help me with?

At the moment my splash screen shows and looks great (thanks!! :) but after the splash screen finishes there is a white screen which shows for a couple of seconds and really ruins the experience.  I have tried to implement the solution provided by the plugin i.e. manually create the splash screen with a delay to cover the white screen however, the splash screen shows for the length of delay I set and then shows the white screen anyway!?

Is there a method to remove this white screen or am I stuck with it?  I have attached a video to show the issue and can upload my flutter code and any other resources if you require.

Much appreciated

https://user-images.githubusercontent.com/74623557/132983800-6634e28e-64ab-41fe-b308-f3534a622f89.mp4

**Comment by jonbhanson** [comment]
I suspect the problem stems from your app loading content that is delaying the display of the app.  See number 2 in the [FAQ question](https://pub.dev/packages/flutter_native_splash#i-see-a-white-screen-between-splash-screen-and-app).

**Comment by jonbhanson** [comment]
Feel free to reopen if you still have a problem.
