### ISSUE TITLE
Can not install pwa while add splash

### ISSUE THREAD

**Issue by hmbenhaim** [jonbhanson/flutter_native_splash#212]
Option to install pwa on flutter web disable d when add splash screen

1. Click on the 3 dot in chrome
2. See the option add to home screen instead of install app

**Expected behavior**
Should show install app on flutter web in chrome when app deployed

**Screenshots**
Should be like in the screenshot below that the install option available (this is app without splash screen generated)
![Screenshot_20210913-171358.png](https://user-images.githubusercontent.com/59261503/133100179-323f55cb-dd64-461c-96b9-a23a50a41dc0.png)

app with splash screen generated. You can only add to home screen which is performing poorly compare to installed apps
![Screenshot_20210913-171249.png](https://user-images.githubusercontent.com/59261503/133100214-95991db9-9350-476f-b224-adbca317bfb7.png)

**Device (please complete the following information):**
 - Device: pixel 4a
 - OS: android 11

**Comment by jonbhanson** [comment]
I checked my existing PWA which has a splash screen and confirmed that it has the "Install app" option.  Can you provide any more details?

**Comment by hmbenhaim** [comment]
I just updated the package version and flutter to 2.5 is working as you said.
