### ISSUE TITLE
Flutter 2.5 issue, A splash screen was provided to Flutter, but this is deprecated

### ISSUE THREAD

**Issue by zaid17** [jonbhanson/flutter_native_splash#213]
After flutter 2.5 "io.flutter.embedding.android.SplashScreenDrawable" and "provideSplashScreen" are deprecated.

 error: A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.

"Previously, Android Flutter apps would either set io.flutter.embedding.android.SplashScreenDrawable in thier application manifest, or implement provideSplashScreen within their Flutter Activity. This would be shown momentarily in between the time after the Android launch screen is shown and when Flutter has drawn the first frame. This is no longer needed and is deprecated – Flutter now automatically keeps the Android launch screen displayed until Flutter has drawn the first frame. Developers should instead remove usage of these APIs."
quoted from flutter.dev/go/android-splash-migration.

I appreciate your hard work, this package is very useful, Thanks.

**Comment by jonbhanson** [comment]
Check the [FAQ](https://pub.dev/packages/flutter_native_splash#i-got-the-error-a-splash-screen-was-provided-to-flutter-but-this-is-deprecated) for an answer.
