### ISSUE TITLE
Secondary splash screen widget

### ISSUE THREAD

**Issue by YDA93** [jonbhanson/flutter_native_splash#214]
This will be extra handful If we can have out of the box splash widget based on flutter_native_splash.yaml settings.

Thanks for your hard working and efforts!

**Comment by LucaDillenburg** [comment]
In the meantime, I tried to reproduce the secondary splash screen example, but it didn't work. The image in the native splash screen and the imagine in the Flutter Scaffold have different sizes. Is there any way to get around that?

**Comment by iliser** [comment]
Spent some time to extract this code from my template and organize it. 
Check it [the_splash](https://pub.dev/packages/the_splash)

**Comment by jonbhanson** [comment]
As of version 2.0.1+1 of this package, this feature has been added.  Check out the `removeAfter` method in the docs.

**Comment by stact** [comment]
Hi @jonbhanson the method `removeAfter` is deprecated now, do we have a way to display the FlutterNativeSplash from a screen? For eg: we have auth check after login, want display the auth check loading with your FlutterNativeSplash.

Thanks for your lights!

**Comment by jonbhanson** [comment]
@stact `removeAfter` has been replaced with `remove`.
