### ISSUE TITLE
flutter pub run flutter_native_splash:remove doesn't work

### ISSUE THREAD

**Issue by haziqkamel** [jonbhanson/flutter_native_splash#217]
**Describe the bug**
I want to remove the current image in splash screen with flutter pub run flutter_native_splash:remove but it doesn't work.

**To Reproduce**
In terminal,
1. flutter clean
2. flutter pub get
3. flutter pub run flutter_native_splash:remove
4. re-run the app
5. two splash screens were created with one from the previous splash screen and the second one is a white screen.

**Expected behavior**
The previous splash screen should be totally removed and only one splash screen with white generated with flutter pub run flutter_native_splash:remove command.

**Device (please complete the following information):**
 - Device: Pixel 4 API 30
 - OS: Android Emulator

**Flutter doctor**
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version
    10.0.19042.1237], locale en-US)
    • Flutter version 2.5.0 at C:\Users\user\Desktop\Projects\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (2 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.1)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 93.0.961.52

• No issues found!

**Comment by jonbhanson** [comment]
Do you have the following code in your `AndroidManifest.xml`?  If so, it should be removed based on [changes](flutter.dev/go/android-splash-migration) in Flutter 2.5.

```xml
<meta-data
 android:name="io.flutter.embedding.android.SplashScreenDrawable"
 android:resource="@drawable/launch_background"
 />
```

**Comment by haziqkamel** [comment]
> Do you have the following code in your `AndroidManifest.xml`? If so, it should be removed based on [changes](flutter.dev/go/android-splash-migration) in Flutter 2.5.
> 
> ```
> <meta-data
>  android:name="io.flutter.embedding.android.SplashScreenDrawable"
>  android:resource="@drawable/launch_background"
>  />
> ```

For now, the currently known workaround I have discovered is I have to terminate and restart the Android Simulator. Then it work as expected. Yes, I have the code mention in my AndroidManifest.xml.

**Comment by jonbhanson** [comment]
That is interesting that terminating/restarting the simulator fixes the problem.  I wonder if rebooting would have the same effect?  So it sounds that the problem is resolved, so this ticket can be closed?
