### ISSUE TITLE
Can I change the duration of the splash screen?

### ISSUE THREAD

**Issue by chatchaisuriyon** [jonbhanson/flutter_native_splash#220]
Can I change the duration of the splash screen? I know  that delaying the user experience is a poor design decision. but I want to show my app logo for users to remember
, Please take this advice into consideration. Either way, I will respect your decision,

**Comment by jonbhanson** [comment]
It is not possible to change the duration of the native splash screen.  If you want to force a delay, you would have to do it in a second splash screen, like in the package's example.
