### ISSUE TITLE
A lot of messages after adding the splash screen.

### ISSUE THREAD

**Issue by intercretasyo** [jonbhanson/flutter_native_splash#221]
**Describe the bug**
More than a hundred of these lines are found:
I/ViewRootImpl@50e8af1[MainActivity]( 3602): [DP] cancelDraw io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$2@5fb73dc  isViewVisible: true

**Device (please complete the following information):**
 - Device: Samsung Galaxy S10e
 - Android 11

**Flutter doctor**
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
    • Flutter version 2.5.1 at /Users/myPC/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (10 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/myPC/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • SM G970F (mobile) • RF8M620YCCW • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 93.0.4577.82

• No issues found!

**Additional context**
When I removed this code, the issue is happening.
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />

**Comment by puze** [comment]
I am also having the same problem.

**Comment by jonbhanson** [comment]
Is anyone still experiencing this problem?  It seems there was a rash of these in October, and then no more.  Maybe it was related to a Flutter update that had a problem and was subsequently patched?

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having a problem.

**Comment by haslinger** [comment]
@jonbhanson I can confirm, that I see these messages now with my app [Encrateia](https://github.com/3schweinehunde/encrateia/tree/upgrade-2021-project) that I am currently updating, after having removed meta-data as above from the Android.manifest.

I am developing using flutter installed via snap within Ubuntu;
`flutter doctor -v` outputs:
```
[✓] Flutter (Channel stable, 2.10.1, on Ubuntu 20.04.4 LTS 5.4.0-104-generic, locale en_US.UTF-8)
    • Flutter version 2.10.1 at /home/stefan/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (4 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /home/stefan/Android/Sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /snap/android-studio/119/android-studio
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7808
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.1)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM T510 (mobile) • R52MC17S20J • android-arm    • Android 11 (API 30)
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by dk-crazydiv** [comment]
Facing the same issue on Samsung M31, API31. The issue isn't reproducible on pixel devices. Reading the comments above, adding the deprecated metadata to AndroidManifest.xml manually shows a deprecation warning

> W/FlutterActivityAndFragmentDelegate( 1202): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.

and removes the message
> I/ViewRootImpl@3aca0ba[MainActivity]( 6153): [DP] cancelDraw null isViewVisible: true
