### ISSUE TITLE
Secondary splash screen image size

### ISSUE THREAD

**Issue by royvangeel** [jonbhanson/flutter_native_splash#236]
Hey guys, how to make sure the secondary splash screen looks exactly the same as the native splash screen that's created using this package? Currently my secondary splash screen is: Scaffold - Center - Image.asset('path_to_logo') 
The image shown in the secondary splash screen is much bigger :)

**Comment by jonbhanson** [comment]
To make the images the same size, you will need to add different pixel densities in your flutter (secondary) splash.  The sample in this package does this, so check it out if you need more info.

**Comment by royvangeel** [comment]
maybe I'm missing something, but I don't see any pixel densities in the example?

**Comment by jonbhanson** [comment]
Take a look in the assets folder: You will find 1.5x, 2.0x, 3.0x, and 4.0x folders with images of different pixel densities, with the 1.0x pixel density files directly in the assets folder.  You can copy these files from android/app/src/main/res/drawable folders: hdpi, xhdpi, xxhdpi, and xxxhdpi respectively, with mdpi as the 1.0x pixel density.

**Comment by royvangeel** [comment]
got it, thanks!
