### ISSUE TITLE
fade transition for Flutter web

### ISSUE THREAD

**Issue by nyck33** [jonbhanson/flutter_native_splash#238]
I ran the example and it is slightly abrupt, not like the demo screens on the package page running on mobile.

**Comment by jonbhanson** [comment]
The behavior of the transition between the native splash and the app is set by Flutter, not by this package.  In the example, I used a secondary splash screen to give an idea of how app loading could take place in an app, and the transition between this secondary splash and the app could be faded by using the [FadeTransition class](https://api.flutter.dev/flutter/widgets/FadeTransition-class.html).

**Comment by nyck33** [comment]
Thanks, I should have thought of that.
