### ISSUE TITLE
hi dear

### ISSUE THREAD

**Issue by saeedalizade2012** [jonbhanson/flutter_native_splash#242]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by saeedalizade2012** [comment]
hi dear
how set loader gif or write something text in flutter_native_splash package?

**Comment by jonbhanson** [comment]
GIFs are not supported at this time.  If you need to write text, you can place your text within the image itself.

**Comment by jonbhanson** [comment]
In order to find out what file formats are most needed by the community, I have opened a single ticket to capture all image format requests.  Please visit (this ticket)[https://github.com/jonbhanson/flutter_native_splash/issues/245] to vote for the image format you need.
