### ISSUE TITLE
the web run on mobile browser

### ISSUE THREAD

**Issue by acgleader** [jonbhanson/flutter_native_splash#246]
**Describe the bug**
browse the web on the mobile browser, the logo will small first, and then become fullscreen, it should always fullscreen i think

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Flutter doctor**
Please paste the results of the `flutter doctor -v` here

**Additional context**

**Comment by jonbhanson** [comment]
I don't understand your description of the bug.  Can you supply a video?

**Comment by jonbhanson** [comment]
Closing this ticket due to inactivity.  Feel free to reopen with more information if you are still having a problem.

**Comment by acgleader** [comment]
this is a video that show issue
https://user-images.githubusercontent.com/4629162/146679440-c93d2fb0-fb9f-4f4a-9f21-292f5a0ae239.mp4
