### ISSUE TITLE
White Screen Before Splash Screen

### ISSUE THREAD

**Issue by oguncan** [jonbhanson/flutter_native_splash#251]
![image](https://user-images.githubusercontent.com/23150924/146335954-c9ae6150-cadf-4d7d-ac05-d2556e571b60.png)

As shown in the picture, such a screen opens before the Splash Screen is loaded and stays for a short time and then redirects to the Splash Screen.

**Comment by jonbhanson** [comment]
What OS version are you using for the device?  Please include your Flutter doctor output.

**Comment by oguncan** [comment]
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-TR)
    • Flutter version 2.5.3 at /Users/oguncankaya/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/oguncankaya/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • ANE LX1 (mobile)                   • 89UDU18724000657                     • android-arm64  • Android 9 (API 28)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 10 (API 29) (emulator)
    • iPhone 13 Pro (mobile)             • B9DEBD91-C464-4ACE-BF93-15D5CCA2027F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!

**Comment by oguncan** [comment]
I work both on the emulator and on my own device.

**Comment by oguncan** [comment]
API 28 and API 29 as u can see. Thank you.
