### ISSUE TITLE
When adding colors with an alpha seems that breaks the color parser

### ISSUE THREAD

**Issue by simplekjl** [jonbhanson/flutter_native_splash#254]
**Describe the bug**
try to use this color in the configuration "#05001EFF"

**To Reproduce**
1. add color: #05001EFF
2. run command `flutter pub run flutter_native_splash:create`
3. check logs

**Expected behavior**
Should work 

**Screenshots**

**Device (please complete the following information):**

**Flutter doctor**
```
Unhandled exception:
Exception: Invalid color value
#0      parseColor (package:flutter_native_splash/flutter_native_splash.dart:218:3)
#1      createSplashByConfig (package:flutter_native_splash/flutter_native_splash.dart:30:15)
#2      createSplash (package:flutter_native_splash/flutter_native_splash.dart:23:3)
#3      main.<anonymous closure> (file:///Users/josesanchez/Desktop/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-1.3.2/bin/create.dart:8:50)
#4      Parser.parse.<anonymous closure> (package:args/src/parser.dart:106:15)

```

**Additional context**

**Comment by jonbhanson** [comment]
I am not aware of any reason to support an alpha channel color.  What would be behind the splash screen to show through?
