### ISSUE TITLE
Branding on Splash Screen Missing

### ISSUE THREAD

**Issue by Faiizii** [jonbhanson/flutter_native_splash#256]
Currently, this lib does not support branding option on splash screen [Please Read](https://developer.android.com/reference/android/R.attr#windowSplashScreenBrandingImage).Adding an option for branding image which usually appears at the bottom of the splash screen, will help the developers to show powered by logos at the bottom of the screen.

**Comment by jonbhanson** [comment]
@Faiizii thanks for the PR.  Great work!

**Comment by Faiizii** [comment]
thanks @jonbhanson.
