### ISSUE TITLE
White before splash screen shows

### ISSUE THREAD

**Issue by mark8044** [jonbhanson/flutter_native_splash#261]
My splash screen background is a solid blue as defined in the `color` setting

As the app loads (expands from the app icon to the splash screen) it is actually white, and then after the app icon 'expands' to become full screen, the full screen becomes blue to fill with the splash screen.

After the full blue splash screen is shown it correctly goes into the app.

So what's happening is I'm getting white before the splash screen is shown, although very very brief its noticeable since you are seeing white flash to blue.

This is happening on iOS 15 simulator
This is NOT happening on Android 12 physical device or Android 11 device simulator

**Comment by jonbhanson** [comment]
Take a look at [this](https://pub.dev/packages/flutter_native_splash#i-see-a-flash-of-the-wrong-splash-screen-on-ios] question in the FAQ.

**Comment by mark8044** [comment]
> Take a look at [this](https://pub.dev/packages/flutter_native_splash#i-see-a-flash-of-the-wrong-splash-screen-on-ios) question in the FAQ.

I'm a freaking idiot AND I'M LAZY.

I deleted the app and reinstall and thought that was enough.  

But I didn't read the FAQ properly and I missed the part about physically shutting off the device which in the case of the simulator means closing it and relaunching the entire simulator.

Once I did that problem solved.

Thanks x2.  I owe you!!

**Comment by jonbhanson** [comment]
lol. Yep, the iOS caching problem gets a lot of people.  Good luck!

**Comment by Flucadetena** [comment]
In my case I had to open the ios app in xcode and change the background of the "view" in the "LaunchScreen.storyboard" to the same as stated in the pubspec. Don't know why but it was white.

Even with that the package is dope. Thanks!

**Comment by jonbhanson** [comment]
> Even with that the package is dope. Thanks!

🥹👍
