### ISSUE TITLE
flutter_native_splash as Globel CLI.

### ISSUE THREAD

**Issue by lohenyumnam** [jonbhanson/flutter_native_splash#262]
Whenever I build App using flutter. I  have a few packages I will always install in my project. `flutter_native_splash` is always in my top 10 . 

I was wondering if this package can be installed as a global CLI tool. 

### Reason:
1. to use in non-flutter projects like React native, native iOS, or android

**Comment by jonbhanson** [comment]
This project wasn't designed with this use in mind, but you can make it work in this way.  You will need to have a root of your project with an ios and/or android subfolder underneath that root.  Then, you can use this command in the root of your project:

`dart /path/to/flutter_native_splash/bin/create.dart --path=path/to/config.yaml`

The `path` argument is not required if you have your config in a `pubspec.yaml` in your project root.

I will keep this in mind, and maybe I can make it a more general tool in future revisions.
