### ISSUE TITLE
BrandingImage warning

### ISSUE THREAD

**Issue by deng2573** [jonbhanson/flutter_native_splash#264]
![截屏2022-01-11 17 09 59](https://user-images.githubusercontent.com/16871760/148913760-ae89b766-2b87-44b8-9447-62e1b716d4d8.png)

**Comment by Faiizii** [comment]
please share warning details.

**Comment by deng2573** [comment]
> please share warning details.

If not set brand, iOS BrandingImage an empty folder will be created
![截屏2022-01-19 21 21 28](https://user-images.githubusercontent.com/16871760/150139022-7e408226-cfbe-4318-8be2-a83523d8f19c.png)

**Comment by antonioreyna** [comment]
I have the same warning it says BrandingImage.png does not exist

**Comment by jonbhanson** [comment]
I will soon push out an update that fixes this.
