### ISSUE TITLE
Cannot use share widget with flutter_native_splash

### ISSUE THREAD

**Issue by ffaridi1** [jonbhanson/flutter_native_splash#266]
I am writting an App which has a feature to share some content using the official Flutter Share widget which has an option to display the System Share popup (the slide up menu which normally appears when sharing any content from an App).

When I click the button to share in iOS, I see following error in xcode and nothing appears, from error it looks like somehow this widget is blocking the system UI to appear from within my App.

Runner[33620:14018467] [Presentation] Attempt to present <UIActivityViewController: 0x15602d000> on <Runner.SplashViewController: 0x153f09180> (from <Runner.SplashViewController: 0x153f09180>) which is already presenting <FlutterViewController: 0x15407ca00>.
Runner[33620:14018548] [ShareSheet] connection invalidated

I tried to remove the plugin but the remove command never worked for me. That is another issue I am facing as I am now stuck with not having any system UI to get displayed.

**Comment by jonbhanson** [comment]
The error that you are seeing is unrelated to the native_splash_screen.  However, a [google search](https://www.google.com/search?q=Attempt+to+present+on+which+is+already+presenting) shows a lot of results for this error, so I would recommend checking out those threads.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you still have a problem.
