### ISSUE TITLE
mdpi, hdpi, xhdpi, xxhdpi and xxxhdpi drawables folders are not created

### ISSUE THREAD

**Issue by alexaung** [jonbhanson/flutter_native_splash#267]
**Describe the bug**
mdpi, hdpi, xhdpi, xxhdpi and xxxhdpi drawables folders are not created.

flutter_native_splash: ^1.3.2

[https://github.com/alexaung/flutter_native_splash.git](Github Sample)

**To Reproduce**
1. flutter create --org com.mydomain mobile
2. cd mobile
3. flutter pub add flutter_native_splash
4. create assets/images folder and upload logo.png
5. flutter pub run flutter_native_splash:create --path=flutter_native_splash.yaml

**Expected behavior**
should show splash screen with logon

**Device (please complete the following information):**
 - Device: [SM N975F]

**Flutter doctor**
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-x64, locale en-GB)
    • Flutter version 2.8.0 at /Users/aungmyooo/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (5 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/aungmyooo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • SM N975F (mobile) • RF8M82Y3K9A • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
**Additional context**

**Comment by jonbhanson** [comment]
Hello @alexaung.  When I run your example, I see the same problem you are describing.  However, when I update the flutter_native_splash to the latest version, the problem goes away.  Please try the latest version and feel free to reopen if you are still having any problem.

**Comment by alexaung** [comment]
Yes, It is working now. Thanks
