### ISSUE TITLE
Grey screen except splash

### ISSUE THREAD

**Issue by PawelSzymanski89** [jonbhanson/flutter_native_splash#269]
I have properly generated splash in android resources files
![Zrzut ekranu 2022-01-21 o 07 05 06](https://user-images.githubusercontent.com/26041449/150474962-30bb2fe3-f2a2-42ca-9a3f-3485a6ff9616.png)
with following config 
![Zrzut ekranu 2022-01-21 o 07 05 45](https://user-images.githubusercontent.com/26041449/150475061-76a52494-e9d0-444c-a383-b4b115949c59.png)

and my splash is still darkgrey without image

**Device (please complete the following information):**
 - Device: POCO X3
 - OS: Android 11

**Flutter doctor**
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale pl-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.4)
[✓] Connected device (2 available)

**Comment by jonbhanson** [comment]
Hello @PawelSzymanski89 I tried to reproduce your example in the current version, but it worked fine.  Are you still having the problem in the current version?

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having a problem.
