### ISSUE TITLE
iOS @2x image wrong size

### ISSUE THREAD

**Issue by BenBaggley** [jonbhanson/flutter_native_splash#27]
@2x images are currently being generated at 1.5x, due to the divider of '2' specified in [lib/ios.dart](https://github.com/henriquearthur/flutter_native_splash/blob/master/lib/ios.dart).

Source width: 750
Generated:
- 750
- 375 (should be 500)
- 250

The source image is 3x, so 2x requires a divider of 1.5, not 2

**Comment by jonathantribouharet** [comment]
https://github.com/henriquearthur/flutter_native_splash/blob/master/lib/ios.dart#L18

For ` 'LaunchImage@2x.png'` `divider` should be 1.5 and not 2. The 2x image is not half of the 3x, it's based on the smallest image.
