### ISSUE TITLE
Bug Web Reload

### ISSUE THREAD

**Issue by nikes23** [jonbhanson/flutter_native_splash#274]
Describe the bug
The application jumps back to the "Home" screen when the page is reloaded with the splash screen. No matter where you were in the app before. Every time you reload the app, it jumps back to the home page.

To Reproduce
1. Start your App (Web)
2. Use e.g. Bottom Navigation Bar or Drawer to change dart file
3. Reload web application
4. App jumps back to start don't matter where you are before.

Expected behavior
On web reload the app should stay on this page and show it again and don't jump back to the app start screen

Device (please complete the following information):
 - Device: Chrome
 - OS: macOS 11.5.2

Flutter doctor
Please paste the results of the `flutter doctor -v` here
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.5.2 20G95 darwin-x64, locale de-DE)
    • Flutter version 2.8.1 at /Users/antonkempf/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/antonkempf/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 4CDE83F9-A18E-4EA2-8D15-3A7D9AB18CA8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 97.0.4692.99

• No issues found!

**Comment by jonbhanson** [comment]
Sorry you are having this trouble, but it is not related to this package in any way.  Try searching for "flutter save application state".  Looks like this might have your answer: [https://dev.to/pedromassango/what-is-state-restoration-and-how-to-use-it-in-flutter-5blm](https://dev.to/pedromassango/what-is-state-restoration-and-how-to-use-it-in-flutter-5blm)

**Comment by nikes23** [comment]
Ah ok thanks. I will try this out. 
Sorry I thought its important for the package
