### ISSUE TITLE
Even after Flutter has drawn the first frame, the native splash screen image still not removed.

### ISSUE THREAD

**Issue by kang86h** [jonbhanson/flutter_native_splash#275]
**Describe the bug**
Even after Flutter has drawn the first frame, the native splash screen image still not removed.

**To Reproduce**

just add these code

  flutter_native_splash: ^2.0.1+1

flutter_native_splash:
  color: '##FF00FF'
  image: assets/splash.png
  android: true
  ios: true
  web: true

and

run terminal

flutter clean && flutter pub get && flutter pub run flutter_native_splash:create

**Expected behavior**
I don't want to see the flash screen color or image, after Flutter has drawn the first frame

**Screenshots**
![splash1](https://user-images.githubusercontent.com/90103152/151695115-1262b28c-070f-43f3-ac86-2f54dbef6ff0.jpg)
this is my splash image(This is a change in the color of the splash screen for my test. Originally, it is the same blue as the background color of the image.)
and
After running the app on Chrome and increasing the size of the Chrome window, the color of the splash screen hidden behind the app appears.
![splash2](https://user-images.githubusercontent.com/90103152/151695146-e7e2fd9a-b164-4f5b-b761-bedf040a502e.jpg)
This causes serious problems when other apps run the web.
![splash3](https://user-images.githubusercontent.com/90103152/151695198-612ab92f-fd0f-40b1-b29f-b22ee387e8f5.jpg)
This screenshot shows that the flash screen that has not disappeared has invaded the transparent app screen.

**Device (please complete the following information):**
web - google chrome and edge.

**Flutter doctor**
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19044.1466], locale ko-KR)
    • Flutter version 2.8.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\kang8\AppData\Local\Android\sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32014.148
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\kang8\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.29.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1466]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 97.0.1072.69

• No issues found!

**Additional context**
If the web renderer is designated as a canvas, this phenomenon becomes more pronounced, and this phenomenon weakens a little when rendering with html.
Specifically, rendering in html does not cause a splash screen that erodes the app as in the third image above, but when changing the size of the web browser, the splash screen is still visible.

**Comment by jonbhanson** [comment]
I have added a FlutterNativeSplash.remove() method that you can call when your app opens to solve this problem.  You will need to put the latest version in dependancies (not dev_dependancies) and rerun flutter pub run flutter_native_splash:create in order to have access to this new method.
