### ISSUE TITLE
Splash Screen changes Sizes on app start running over Web on mobile

### ISSUE THREAD

**Issue by mpopolin** [jonbhanson/flutter_native_splash#276]
**Describe the bug**
The splash screen image size increases when running on Web using Android or iOS devices.

**To Reproduce**
1. Clone the repo
2. Build the app for web
3. Deploy it in any service (already deployed here if needed to test: https://laughing-lichterman-2dbaa2.netlify.app)
4. See error: image starts small and then increases size

**Expected behavior**
The image should be the same during all the splash screen

**Screenshots**
![WhatsApp Image 2022-01-30 at 20 11 57](https://user-images.githubusercontent.com/11718202/151721941-e72264c3-03aa-4b82-bdb6-9269e4d602da.jpeg)
![WhatsApp Image 2022-01-30 at 20 11 57 (1)](https://user-images.githubusercontent.com/11718202/151721945-c80bd3c4-c0ba-4201-9501-e4675407f193.jpeg)

**Device (please complete the following information):**
 - Device: any mobile device
 
**Flutter doctor**
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.2 20G314 darwin-x64, locale pt)
    • Flutter version 2.8.1 at /Users/marcelcunha/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/marcelcunha/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/marcelcunha/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6.2 20G314 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

**Additional context**
Only occurs if running on web on mobile devices. Desktop browsers are OK.

**Comment by jonbhanson** [comment]
@mpopolin can you try inserting this in the `<head>` of your `web/index.html` file:

```html
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
```

Please let me know if this solves it so I can add a fix for this package.

**Comment by mpopolin** [comment]
@jonbhanson yes, it does. Thank you!

**Comment by mdeandrea-mrmilu** [comment]
When use `<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>` Flutter throw a warning:

> WARNING: found an existing <meta name="viewport"> tag. Flutter Web uses its own viewport configuration for better compatibility with Flutter. This tag will be replaced.

**Comment by zenled** [comment]
For the `WARNING: found an existing tag...` I've come up with the following workaround (check [Flutter docs](https://docs.flutter.dev/platform-integration/web/initialization#example-display-a-progress-indicator) for more info).

I added the `splash-viewport` class to the `meta` tag. The tag can then be removed just before the Flutter engine gets initialized.

```html
<meta class="splash-viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
```

```js
// flutter_bootstrap.js

{{flutter_js}}
{{flutter_build_config}}

_flutter.loader.load({
  onEntrypointLoaded: async function(engineInitializer) {
    var splashViewport = document.getElementsByClassName('splash-viewport')[0];
    if (splashViewport != undefined) splashViewport.remove(); // splashViewport is undefined when performing hot restart

    const appRunner = await engineInitializer.initializeEngine();
    await appRunner.runApp();
  }
});
```
