### ISSUE TITLE
Macos Supoort

### ISSUE THREAD

**Issue by agreensh** [jonbhanson/flutter_native_splash#277]
https://pub.dev/packages/flutter_native_splash states it supports Macos.
Does nothing on Macos. Why say you support it?

**Comment by jonbhanson** [comment]
Because I have not figured out how to turn off the notification of support for Macos.

**Comment by vinurs** [comment]
is this will support macos、linux、windows？

**Comment by jonbhanson** [comment]
@vinurs see #168 for the answer to your question.
