### ISSUE TITLE
Change mode from app setting

### ISSUE THREAD

**Issue by mstfkhazaal** [jonbhanson/flutter_native_splash#278]
I have an app that saves the mode in app setting(flutter_secure_storage), 
how can I change the mode from app setting without going back to the system mode

**Comment by jonbhanson** [comment]
I do not understand the question.  Does your question apply to this flutter_native_splash package?

**Comment by mstfkhazaal** [comment]
I want the splash screen mode dark/light to be controlled from me inside the application not automatically related to phone mode. I will put a settings inside my application to be chosen always dark or always light regardless of phone mode condition. please can you help me?

**Comment by jonbhanson** [comment]
What you are describing is not supported by this package.
