### ISSUE TITLE
Unable to set light background colors (#fffff, #f1f5f9, etc,.) for android dark mode

### ISSUE THREAD

**Issue by prasaduu** [jonbhanson/flutter_native_splash#281]
- For light mode & dark mode, I need the same background color,
- but in my android mobiles (POCO X3, POCO M2, etc,.), I'm getting some other background which is a darker version of my color with some added tint coloring.
- It has been observed in almost all of the mobiles that I've tested on

Expected Color for both light & dark theme - #f1f5f9

**Comment by jonbhanson** [comment]
I found the source of this problem, related to [184](https://github.com/jonbhanson/flutter_native_splash/issues/184).  I will push out an update to correct this.

**Comment by Sahil-Tagline** [comment]
@prasaduu your problem solve?
