### ISSUE TITLE
Same png, one in the pubsec as image, one in the splash screen, gets different sizes.

### ISSUE THREAD

**Issue by salvolf** [jonbhanson/flutter_native_splash#289]
**Describe the bug**
Same png, one in the pubsec as image, one in the splash screen, gets different sizes.

**To Reproduce**
1. Go to pubsec.yaml
2. Add:
```
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/logo_energia_1.png
  branding_mode: "center"
```
3. Go to another screen (Another splash screen for example)
Add:
`@override
  Widget build(BuildContext context) {
    return Container(
      color: Constants.SPLASH_SCREEN_BACKGROUND,
      child: const Center(
          child: Image(
              image: AssetImage('assets/logo/logo_energia_1.png')))
    );
  }`

**Expected behavior**
Same size of both pngs

 - Device: [Android: Pixel 3 API 28]

**Flutter doctor**

[✓] Flutter (Channel stable, 2.8.1, on macOS 11.4 20F71 darwin-x64, locale en-NL)
    • Flutter version 2.8.1 at /Users/***/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (8 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/***/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 98.0.4758.80

**Comment by jonbhanson** [comment]
Rather than try to match image sizes, this package has the ability to simply keep the same splash on screen while your content loads.  Check out the readme for details.

**Comment by MuhammadEssam96** [comment]
Correct me if I'm wrong, keeping the same splash is a good solution, but not for every case. In my case, I'm using a hero animation on the logo image itself so that it provides the user with a seamless transition from the splash into the app.

Letting the user see the logo followed by the same logo again in another size is not ideal. That's why matching the sizes of the images between the native and the flutter splashes is needed.

**Comment by jonbhanson** [comment]
The solution is to add [resolution aware assets in your flutter project](https://docs.flutter.dev/development/ui/assets-and-images#resolution-aware).  If you look at an [older version](https://github.com/jonbhanson/flutter_native_splash/releases/tag/v1.3.3) of this package, the example did image size matching.

**Comment by suhail600** [comment]
I solved it by changing the resolution of the image , change the resolution of the image to a higher resolution like above 1080 , and  make use online websites for changing resolution
