### ISSUE TITLE
Black screen when launching example app on a oneplus 8T

### ISSUE THREAD

**Issue by horgag** [jonbhanson/flutter_native_splash#290]
**Describe the bug**
Black screen when launching the example app in the repo on a oneplus 8T
**To Reproduce**
Launch example app from a oneplus phone
**Expected behavior**
Expect to see white background screen on launch.

**Device (please complete the following information):**
oneplus 8T

**Flutter doctor**
✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)

**Additional context**

**Comment by BaudouinCS** [comment]
Same issue with the Poco F1, with same steps

**Flutter doctor**
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [version 10.0.19042.1288], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 3.0)
[√] VS Code (version 1.65.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by jonbhanson** [comment]
Sorry, I don't have a oneplus or poco device, so I don't have a way of diagnosing this problem.  If you find the solution, (probably by editing the android project files directly), please let me know so I can add support in this package.

**Comment by horgag** [comment]
Apologies, should of closed this. It wasn't an issue, it was just the phone was in dark mode and I hadn't handled this in the package. Thanks for this package.
