### ISSUE TITLE
Add option to not distort background-image

### ISSUE THREAD

**Issue by Glitchy-Tozier** [jonbhanson/flutter_native_splash#294]
**Is your feature request related to a problem? Please describe.**
Currently, the background-image gets squashed to fit the screen. This makes some images get distorted.

**Describe the solution you'd like**
It would be great to have an option that disables squashing the background-image by simply clipping the sides (or the top), if needed.
Is this possible?

**Describe alternatives you've considered**
I'm not sure how to answer.

**Comment by jonbhanson** [comment]
What platform are you using?  Have you tried different parameters?

```  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center
```

**Comment by jonbhanson** [comment]
For the time being, you can solve the problem by modifying your `android/app/src/main/res/drawable-*/launch_background.xml.  Find the `<bitmap android:gravity="fill" android:src="@drawable/background"/>` line and change `gravity` to `center`.

**Comment by Glitchy-Tozier** [comment]
Will try it out, thank you.

**Comment by Glitchy-Tozier** [comment]
Was there some commit that fixed this issue?
