### ISSUE TITLE
Cannot Remove old Splash screen

### ISSUE THREAD

**Issue by smile675** [jonbhanson/flutter_native_splash#295]
Hi I have added splash screen using the terminal code;

after that I did not like the image or the outcome. so i deleted the image and deleted all splash related code. and then I added splash for only title in the screen. now my app shows two splash screen. on for the image that doesnot exist anymore. and another one is the title. 

I tried to restart, clear data, flutter clean. still I am having two splash.

**Comment by jonbhanson** [comment]
Did you try uninstalling your app, powering off your device, power back on, and then try reinstalling as advised in the [FAQ](https://pub.dev/packages/flutter_native_splash#i-see-a-flash-of-the-wrong-splash-screen-on-ios)?

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you still have a problem.
