### ISSUE TITLE
Repeating Image background

### ISSUE THREAD

**Issue by juniorkibirige** [jonbhanson/flutter_native_splash#298]
Could you provide a solution to the provision of a background image behind the splash screen logo, which could be repeating behind the logo
![Group 16](https://user-images.githubusercontent.com/48098954/155809587-cea6b278-8d0d-4225-ab3e-b5e53547867b.png)

**Comment by jonbhanson** [comment]
Sorry, I will not be able to add this feature.  I suggest that you place the background into the splash image itself.
