### ISSUE TITLE
Is it possible to add web support?

### ISSUE THREAD

**Issue by Harkunwar** [jonbhanson/flutter_native_splash#30]
Every time I load my flutter web website, it shows a blank page for a few seconds until the dart code runs, any possibility for an animation?

**Comment by henriquearthur** [comment]
It can be done by using plain HTML on `index.html` and remove it when Flutter renders first frame.

I'll look into the possibility of generating this automatically and adding to the plugin.

**Comment by jonbhanson** [comment]
OK, I've added web support. 👍🏻
