### ISSUE TITLE
Best practises - do initialisation stuff in main() before runApp

### ISSUE THREAD

**Issue by WieFel** [jonbhanson/flutter_native_splash#302]
**My issue is more like a question about best practises usage of this package:**
I am very well aware that the "normal" way of using the package would be as described in the readme/examples, which is to show the splash screen on app startup, maintain it in the view with `FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);` and when ready hiding it with `FlutterNativeSplash.remove();`.

However, for a quick prototype of an app, I simply put initialisation code within the `main()` function, before the `runApp()` statement, and noticed that this achieves basically the same behaviour as described above.
Example code:
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  preferences = await SharedPreferences.getInstance();
  var userName = preferences.getString("username");

  // other initialisation code ...

  runApp(MyApp(userName: userName));
}
```

I **do** have a bad feeling doing this and am about to change it now to the "default" way of handling it. But still, I can't actually find any argument which is against handling initialisation in `main()` before running the flutter app.

Any hints on this?

**Comment by jonbhanson** [comment]
@WieFel there is nothing wrong with leaving out the `preserve()` and `remove()` calls.  They are there to keep the splash up while your app initializes, but if you initialization is fast, it is better to leave them out.

**Comment by WieFel** [comment]
@jonbhanson thanks for your opinion!

So I suppose also some network I/O code can be put into `main`!? For example, initialising firebase or similar...

What do you think?

**Comment by jonbhanson** [comment]
If you put network code in `main`, I think it would be best to `preserve` the splash screen until the network call is done.  If you have a very slow network and you `await` a network call in `main` and you don't `preserve` the splash screen, you could have a blank screen.

**Comment by WieFel** [comment]
@jonbhanson thank you very much!
