### ISSUE TITLE
After run the package, splash screen doesn't change

### ISSUE THREAD

**Issue by lambertofredricknbb** [jonbhanson/flutter_native_splash#306]
**Describe the bug**
I use emulator with android 13 (Tiramisu).
So after I run the package and open up the app, the splash screen doesn't change (still on default -> from icon app).
Any solution? 

**To Reproduce**
1. add flutter_native_splash: ^2.1.0 as a dependency in my pubspec.yaml
2. add flutter_native_splash.yaml (with config from documentation) in my root folder
3. run flutter clean && flutter pub get && flutter pub run flutter_native_splash:create --path=path/to/my/flutter_native_splash.yaml
4. Run app

**Expected behavior**
Splash screen doesn't change (still on default  -> from icon app)

**Screenshots**
<img width="1440" alt="Screen Shot 2022-03-11 at 13 06 16" src="https://user-images.githubusercontent.com/78105743/157811990-cee54820-427a-4b94-9e2c-65cd874d21be.png">

**Device (please complete the following information):**
 - Pixel 3
 - OS: Android 13 (Tiramisu)

**Flutter doctor**
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-arm, locale
    en-ID)
    • Flutter version 2.10.3 at /Users/lfnbb/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (9 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc1)
    • Android SDK at /Users/lfnbb/Library/Android/sdk
    • Platform android-31, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
      (API 32) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Additional context**

**Comment by hackgyj** [comment]
same one，android 11

**Comment by jonbhanson** [comment]
@lambertofredricknbb can you post your config.  @hackgyj please open a new ticket with full details.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.
