### ISSUE TITLE
users can tap on splash screen and it is impacted on the home screen , or the next screen after splash screen

### ISSUE THREAD

**Issue by suhail600** [jonbhanson/flutter_native_splash#308]
when splash screen loads or displays  we can touch there to register that touch on the home screen or next screen to splash , its like a bug and please solve this issue , or give a temp fix code or solution untill next update

thank u

**Comment by jonbhanson** [comment]
This would be a problem with the Flutter framework, not this package.  Please open a ticket with Flutter.
