### ISSUE TITLE
Unhandled exception when terminal splash create/remove 

### ISSUE THREAD

**Issue by barisulgen** [jonbhanson/flutter_native_splash#309]
**Describe the bug**
Error occurs when I call flutter_native_splash:create from the terminal (or :remove).

PS C:\Users\"MYPATH"> flutter pub run flutter_native_splash:create 
[Android] Creating splash images
[Android] Updating launch background(s) with splash image path...
[Android]    - android/app/src/main/res/drawable/launch_background.xml
[Android]    - android/app/src/main/res/drawable-night/launch_background.xml
[Android]    - android/app/src/main/res/drawable-v21/launch_background.xml
[Android]    - android/app/src/main/res/drawable-night-v21/launch_background.xml
[Android] Updating styles...
[Android]    - android/app/src/main/res/values-v31/styles.xml
[Android]    - android/app/src/main/res/values-night-v31/styles.xml
[Android]    - android/app/src/main/res/values/styles.xml
[Android]    - android/app/src/main/res/values-night/styles.xml
[iOS] Creating  images
[iOS] Updating LaunchScreen.storyboard with width, and height
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
Unhandled exception:
XmlParserException: Expected name at 2:2
#0      new XmlDocument.parse (package:xml/src/xml/nodes/document.dart:35:7)
#1      _updateInfoPlistFile (package:flutter_native_splash/ios.dart:443:35)
#2      _applyInfoPList (package:flutter_native_splash/ios.dart:434:5)
#3      _createiOSSplash (package:flutter_native_splash/ios.dart:141:3)
#4      createSplashByConfig (package:flutter_native_splash/cli_commands.dart:90:7)
#5      createSplash (package:flutter_native_splash/cli_commands.dart:23:3)
#6      main.<anonymous closure> (file:///C:/Users/PC/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.1.0/bin/create.dart:6:49)
#7      Parser.parse.<anonymous closure> (package:args/src/parser.dart:106:15)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#9      MapView.forEach (dart:collection/maps.dart:342:10)
#10     Parser.parse (package:args/src/parser.dart:95:22)
#11     ArgParser.parse (package:args/src/arg_parser.dart:335:42)
#12     main (file:///C:/Users/PC/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.1.0/bin/create.dart:7:10)
#13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255

**Device (please complete the following information):**
 - Device: Pixel 4 API 30
 - OS: Android 11.0 (x86)

**Flutter doctor**
flutter doctor -v
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19042.1586], locale en-US)
    • Flutter version 2.10.3 at C:\Users\PC\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (9 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\PC\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32228.430
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.65.2)
    • VS Code at C:\Users\PC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1586]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 99.0.4844.51
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 99.0.1150.36

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Additional context**
PUBSPEC.YAML FILE ->

name: myna
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  animated_toggle_switch: ^0.2.3
  bot_toast: ^4.0.1
  circular_countdown_timer: ^0.2.0
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  date_format: ^2.0.5
  decorated_icon: ^1.2.1
  direct_select: ^2.0.0
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.0
  flutter_svg: ^1.0.0
  fluttertoast: ^8.0.8
  google_fonts: ^2.2.0
  gradient_ui_widgets: ^1.0.2-nullsafety
  graphic: ^0.9.1
  http: ^0.13.4
  intl: ^0.17.0
  introduction_screen: ^3.0.0
  provider: ^6.0.2
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:

  
  color: "#f2f3f7"
  image: assets/images/MynaLogo (Small).png

  color_dark: "#222222"
  android: true
  ios: true
  web: false

  info_plist_files:
    - 'ios/Runner/Info.plist'
    - 'ios/Runner/GoogleService-Info.plist'

flutter_icons:
  image_path: "assets/images/MynaLogo (Small).png"
  android: true 
  ios: true 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/texts/
    - assets/fonts/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf

    - family: Myna
      fonts:
        - asset: assets/icons/Myna.ttf

**Comment by jonbhanson** [comment]
Can you post the content of your `ios/Runner/Info.plist` file?

**Comment by coruhsimsek** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd%22%3E
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>$(DEVELOPMENT_LANGUAGE)</string>
    <key>CFBundleDisplayName</key>
    <string>Myna</string>
    <key>CFBundleExecutable</key>
    <string>$(EXECUTABLE_NAME)</string>
    <key>CFBundleIdentifier</key>
    <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>myna_xcode</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>$(FLUTTER_BUILD_NAME)</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>CFBundleVersion</key>
    <string>$(FLUTTER_BUILD_NUMBER)</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>UILaunchStoryboardName</key>
    <string>LaunchScreen</string>
    <key>UIMainStoryboardFile</key>
    <string>Main</string>
    <key>UIStatusBarHidden</key>
    <false/>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationPortraitUpsideDown</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UIViewControllerBasedStatusBarAppearance</key>
    <false/>
</dict>
</plist>

**Comment by jonbhanson** [comment]
Your plist file seems to be corrupt.  Note the end of the second line:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
```

**Comment by coruhsimsek** [comment]
Yes you are right! Thank yuo so much

**Comment by panktiszluck** [comment]
I am getting the same issue, and here is my info.plist

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Dango</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>dango</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>https</string>
		<string>http</string>
		<string>googlechromes</string>
		<string>comgooglemaps</string>
		<string>whatsapp</string>
		<string>mailto</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>LSSupportsOpeningDocumentsInPlace</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>To take user live profile image</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>View site address in map</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>To take user profile image</string>
	<key>PermissionGroupNotification</key>
	<string>To send user notification</string>
	<key>UIFileSharingEnabled</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIStatusBarHidden</key>
	<false/>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>NSAppleMusicUsageDescription</key>
	<string>This will let you attach audio file in complaint/feedback</string>
	<key>UISupportsDocumentBrowser</key>
	<true/>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
</dict>
</plist>
```
