### ISSUE TITLE
Support of Animated Vector Drawable for Android 12

### ISSUE THREAD

**Issue by siddzankat** [jonbhanson/flutter_native_splash#312]
Any plans on supporting Animated Vector Drawable for Android 12?

something like this:
https://itnext.io/a-comprehensive-guide-to-android-12s-splash-screen-api-644609c811fa#:~:text=It%20should%20be%20within%20200dp,Use%20SVG%20or%20Drawable%20XML.

**Comment by jonbhanson** [comment]
I do not have any plans to add support at the moment, but PRs are always welcome.  If you want this format, please add a request to [this thread](https://github.com/jonbhanson/flutter_native_splash/issues/245).
