### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by abhlabs** [jonbhanson/flutter_native_splash#317]
**Describe the bug**
documentation improvement

**To Reproduce**
The first item in the FAQ says:

>This message is not related to this package but is related to a [change](https://flutter.dev/docs/development/ui/advanced/splash-screen#migrating-from-manifest--activity-defined-custom-splash-screens) in how Flutter handles splash screens in Flutter 2.5. It is caused by having the following code in your AndroidManifest.xml, which was included by default in previous versions of Flutter:

**Expected behavior**
There can be many "AndroidManifest.xml" files in the project folder.   Documentation could be improved by clarifying that this one is the one in android\app\src\main.

**Comment by jonbhanson** [comment]
@abhlabs can you make a pull request which adds this documentation and I will be happy to merge it.
