### ISSUE TITLE
Can you see this issue please

### ISSUE THREAD

**Issue by fisforfaheem** [jonbhanson/flutter_native_splash#320]
Because admin depends on flutter_native_splash >=2.0.0 which requires Flutter SDK version >=1.17.0, version solving failed.pub finished with exit code 1

**Comment by jonbhanson** [comment]
Do you have a lower version of the Flutter SDK that is causing the conflict?  What version of the Flutter SDK does your app use?

**Comment by fisforfaheem** [comment]
I have flutter 2.10

**Comment by jonbhanson** [comment]
What is your Flutter SDK version in your pubspec.yaml?

**Comment by vkammerer** [comment]
I feel for you @jonbhanson , an issue with a title like that is immediately closed with no reply in my repos.... plus the issue obviously isn't yours to fix.

**Comment by jonbhanson** [comment]
@vkammerer lol, I try to be patient, but sometimes I just can't handle it.  [Like this one](https://github.com/jonbhanson/flutter_native_splash/issues/319).

**Comment by vkammerer** [comment]
You still went through the bother of posting a link, that's nice of you!

**Comment by fisforfaheem** [comment]
Sorry if u felt bad, I dont know how to do this issue stuff, I am
learning...vincent stop trying to humiliate someone without knowing his
position.

**Comment by fisforfaheem** [comment]
I am now in the flutter beta sdk and this seems to be fixed automatically

**Comment by jonbhanson** [comment]
@fisforfaheem glad it is working for you.  OK to close this ticket?

**Comment by fisforfaheem** [comment]
Agree with you, :)
