### ISSUE TITLE
Please try to bump the xml version

### ISSUE THREAD

**Issue by hicnar** [jonbhanson/flutter_native_splash#323]
In your next release please consider bumping up the xml version to the most recent 6.0.1

**Comment by jonbhanson** [comment]
@hicnar this package is designed to be compatible with the stable channel of Flutter, which depends on collection 1.15.0 whereas xml 6.0.1 depends on collection 1.16.0.  When Flutter stable updates this dependency, I will upgrade this package's dependency.
