### ISSUE TITLE
Branding image under the bottom bangs

### ISSUE THREAD

**Issue by olegys** [jonbhanson/flutter_native_splash#325]
My config

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo.png"
  branding: "assets/images/branding.png"
  android: true
  ios: true
  web: true
  
 
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-03-30 at 17 24 04](https://user-images.githubusercontent.com/18525409/160861670-9752fe05-2956-4b90-b8e2-bbe0cd7e6cb8.png)

**Comment by jonbhanson** [comment]
@olegys the operating system sets the position, so unfortunately this positioning cannot be changed in this package.  I would suggest adding some transparent padding to the bottom of your branding image, which should push it upward.
