### ISSUE TITLE
pub finished with exit code 255 in version ^2.1.5

### ISSUE THREAD

**Issue by s99chandra** [jonbhanson/flutter_native_splash#336]
command:->
flutter pub run flutter_native_splash:create
error :-> 
[Android] Creating splash images
[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android]  - android/app/src/main/res/values/styles.xml
[iOS] Creating images
[iOS] Updating LaunchScreen.storyboard with width, and height
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
Unhandled exception:
XmlParserException: Expected </string>, but found </dict> at 65:1
#0      XmlGrammarDefinition.element.<anonymous closure> (package:xml/src/xml/grammar.dart:105:13)
#1      MapParser.parseOn (package:petitparser/src/parser/action/map.dart:38:37)
#2      ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#3      PossessiveRepeatingParser.parseOn (package:petitparser/src/parser/repeater/possessive.dart:67:31) 
#4      SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#5      ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#6      SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#7      MapParser.parseOn (package:petitparser/src/parser/action/map.dart:36:29)
#8      ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#9      PossessiveRepeatingParser.parseOn (package:petitparser/src/parser/repeater/possessive.dart:67:31) 
#10     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#11     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#12     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#13     MapParser.parseOn (package:petitparser/src/parser/action/map.dart:36:29)
#14     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#15     PossessiveRepeatingParser.parseOn (package:petitparser/src/parser/repeater/possessive.dart:67:31) 
#16     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#17     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#18     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#19     MapParser.parseOn (package:petitparser/src/parser/action/map.dart:36:29)
#20     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#21     PossessiveRepeatingParser.parseOn (package:petitparser/src/parser/repeater/possessive.dart:67:31) 
#22     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#23     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#24     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#25     MapParser.parseOn (package:petitparser/src/parser/action/map.dart:36:29)
#26     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#27     PossessiveRepeatingParser.parseOn (package:petitparser/src/parser/repeater/possessive.dart:67:31) 
#28     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#29     ChoiceParser.parseOn (package:petitparser/src/parser/combinator/choice.dart:68:34)
#30     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#31     MapParser.parseOn (package:petitparser/src/parser/action/map.dart:36:29)
#32     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#33     MapParser.parseOn (package:petitparser/src/parser/action/map.dart:36:29)
#34     SequenceParser.parseOn (package:petitparser/src/parser/combinator/sequence.dart:39:34)
#35     PickParser.parseOn (package:petitparser/src/parser/action/pick.dart:26:29)
#36     CastParser.parseOn (package:petitparser/src/parser/action/cast.dart:17:29)
#37     Parser.parse (package:petitparser/src/core/parser.dart:51:36)
#43     createSplash (package:flutter_native_splash/cli_commands.dart:23:3)
#44     main.<anonymous closure> (file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.1.5/bin/create.dart:6:49)
#45     Parser.parse.<anonymous closure> (package:args/src/parser.dart:106:15)
#46     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#47     MapView.forEach (dart:collection/maps.dart:342:10)
#48     Parser.parse (package:args/src/parser.dart:95:22)
#49     ArgParser.parse (package:args/src/arg_parser.dart:335:42)
#50     main (file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_splash-2.1.5/bin/create.dart:7:10)
#51     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)     
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255

This is the error I'm stuck in there.  how can solve this and can't understand where are error

_Originally posted by @s99chandra in https://github.com/jonbhanson/flutter_native_splash/issues/3#issuecomment-1098399705_

**Comment by jonbhanson** [comment]
It looks like there could be an error in your ios/Runner/Info.plist XML.

**Comment by s99chandra** [comment]
> It looks like there could be an error in the XML of your ios/Runner/Info.plist.
please send error message properly
i can't figure out where it's problem only show 255 exit code

**Comment by jonbhanson** [comment]
Did you find the problem?

I think this is the key: `XmlParserException: Expected , but found at 65:1`
