### ISSUE TITLE
Library doesn't work in Dart 2.16.2

### ISSUE THREAD

**Issue by githubSudoTechnology** [jonbhanson/flutter_native_splash#337]
when executing the command
`flutter pub run flutter_native_splash:create`
I get the following error:

```
Dart 2.16.2 is incompatible with your dependencies' SDK constraints. Please run "flutter pub get" again.
pub finished with exit code 65
```

**Comment by jonbhanson** [comment]
I believe it is one of your other package dependancies triggering this error.  This package has been tested to run under Dart 2.16.2.
