### ISSUE TITLE
Web accessibility warning: Images must have alternate text: Element has no title attribute

### ISSUE THREAD

**Issue by bdlukaa** [jonbhanson/flutter_native_splash#339]
**Describe the bug**
When running an web app that has a splash screen made by this package, the following warning is thrown:

`Images must have alternate text: Element has no title attribute`
`<img class="center" src="splash/img/light-1x.png">`

**To Reproduce**
1. Go to https://bdlukaa.github.io/fluent_ui/
2. Open DevTools
3. Open issues
4. See warning

**Expected behavior**
No warning is thrown.

**Screenshots**
![Fluent UI Showcase for Flutter](https://user-images.githubusercontent.com/45696119/163565976-de1b932a-087c-4265-8a7a-cb7d4559a358.png)

**Device (please complete the following information):**
 - Browser: Microsoft Edge
 - OS: Windows 11

**Comment by jonbhanson** [comment]
I will push out and update soon that will fix this.
