### ISSUE TITLE
Add support for smaller images (icons)

### ISSUE THREAD

**Issue by dvorapa** [jonbhanson/flutter_native_splash#34]
When you use fluter_native_splash, image covers the whole width of a screen. But what if this is just an icon and you want to make it smaller than screen size (as the icon usually is)?

**Comment by henriquearthur** [comment]
The image should only cover the whole screen width if you use `fill: true`.

When you do something like

	flutter_native_splash:
	  image: assets/images/splash.png
	  color: "42a5f5"

The image will be centered on screen and use only proportional width.

Are you using `fill: true`? What is your image width?

**Comment by dvorapa** [comment]
The image width is 8192x8192. I'm not using `fill: true` I want to achieve something like this:
![1*VB8NR3Ba8awnIzXOdN5GSQ](https://user-images.githubusercontent.com/5113916/71450337-8fbb9380-2760-11ea-82ef-dd533279e2a3.png)
But the image covers the whole screen instead

**Comment by dvorapa** [comment]
I'm currently doing it by hand, because I can not achieve this with my library.

**Comment by cyb3rcod3** [comment]
Same here, image icon size 64x64 covers the whole screen.
I try with fill: false, or without fill parameter, i also tried flutter clean but same result.

Look here:
![alt text](https://i.ibb.co/Lvp4fPR/icon-size-fill-problem.jpg)

**Comment by jonbhanson** [comment]
This should be addressed by recent updates.  Feel free to reopen if you experience any problems.
