### ISSUE TITLE
Adjust Image Size

### ISSUE THREAD

**Issue by tapizquent** [jonbhanson/flutter_native_splash#340]
**Describe the bug**
I am adding the necessary items for the generation of the splash screen. I currently I'm providing an image with size 500x500. 

I am noticing that the image looks a bit too small when added to the splash screen.

Is there any way to adjust the size of this image that appears in the center? Maybe make it a bit larger

**To Reproduce**
1. Add image with 500x500 size
2. Generate splash screen
3. Launch app
4. See small image in center

**Expected behavior**
Image should resize properly

**Screenshots**
![IMG_4902](https://user-images.githubusercontent.com/26445812/163610113-87ec1ffe-1e60-4152-9f5f-355893dd118f.PNG)

**Device (please complete the following information):**
 - Device: iPhone 11 R
 - OS: iOS 14

**Comment by jonbhanson** [comment]
The image is resized for various pixel densities.  If the image is not the size you expect, it may be because a different pixel density of the image was used.  Of course, you can always resize the source image and the resized versions will be changed accordingly.

**Comment by tapizquent** [comment]
> The image is resized for various pixel densities.  If the image is not the size you expect, it may be because a different pixel density of the image was used.  Of course, you can always resize the source image and the resized versions will be changed accordingly.

Amazing! We updated the image to a higher pixel density and it all looks great now. Thank you very much!

**Comment by danallen88** [comment]
We're experiencing the same issue as above, except that using a higher pixel density asset didn't solve the problem for us.  

The assets/icon.png is a 4608x4608 image at 4x pixel density, and previously we had used an 1152x1152 asset at 1x pixel density just for Android 12.  They both produced the same output, which is hard to capture on app startup, but this should give you an idea on how small it is relative to the screen on a Galaxy S10 running Android 12:


![Screenshot_20220524-102633](https://user-images.githubusercontent.com/4910808/170343678-0adf0060-92cd-47ad-8155-7bb44620df75.jpg)
![Screenshot_20220524-102554](https://user-images.githubusercontent.com/4910808/170343703-65a1045d-4bf4-4819-adfb-99887aa4bc16.jpg)


```yaml
flutter_native_splash:
  background_image: "assets/splash_screen_background.png"
  image: "assets/icon.png"
  android: true
  ios: true
  web: false
  android_12:
    image: "assets/icon.png"
    color: "#00A7B5"
```
