### ISSUE TITLE
 Landscape issue

### ISSUE THREAD

**Issue by amirkarimistr** [jonbhanson/flutter_native_splash#344]
**### Landscape  issue**

I'm using this awesome library for showing the splash screen for my landscape flutter application, but it has an issue, when I start the app, the splash screen loaded vertically, and after a few seconds, it changes to the landscape mode.

**Comment by jonbhanson** [comment]
I will push out an update that adds the ability to set the screen orientation in Android.

**Comment by sawongam** [comment]
A Update here, The problem still exists, My app is default landscape however when i use the native_splash_screen, it goes into portait mode automatically.
