### ISSUE TITLE
splash is visible for some seconds even after the page is loaded in flutter web

### ISSUE THREAD

**Issue by GauravCalidig** [jonbhanson/flutter_native_splash#346]
**Describe the bug**
The splash is visible for some seconds even after the page is loaded in flutter web
Visit [here](https://thekaa.web.app/#/) to check
![image](https://user-images.githubusercontent.com/90178033/167057276-9debccdc-2c0e-4dd2-8401-97117c07c86c.png)

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having a problem.

**Comment by GauravCalidig** [comment]
can we close splash before onboarding becomes visible?

**Comment by jonbhanson** [comment]
Use `FlutterNativeSplash.remove();` as described in the [readme](https://pub.dev/packages/flutter_native_splash#3-set-up-app-initialization-optional).
