### ISSUE TITLE
How to extend the duration of the splash screen?

### ISSUE THREAD

**Issue by anburocky3** [jonbhanson/flutter_native_splash#348]
Currently it is little fast, i like to show it for 3 - 4 second.

Thanks in advance.

**Comment by jonbhanson** [comment]
If you look at the example in this package, it has a delay for the purpose of demonstration.  However, I should point out that slowing down your app and forcing the user to wait is a bad design practice.  The splash should only be displayed while the app is unavailable due to loading.

**Comment by anburocky3** [comment]
Can totally understand. It's the client's requirement. They wanted the user to let them know about their brand for at least 3 seconds. 

Thanks for your quick reply. Closing this.

**Comment by anburocky3** [comment]
@jonbhanson Another question, but let me ask it here itself:

Can we add an `Loading indicator` below the logo? Since we made 3 secs, it looks like the app is kind of freezer, 😉 

I know it's a bad practice, but the client asks this.

**Comment by jonbhanson** [comment]
@anburocky3 sorry, I have not added that feature to the package.

**Comment by anburocky3** [comment]
it would be helpfull becoz of the freezing state. Wonderful package btw, loved it.
