### ISSUE TITLE
Flutter v3 WidgetsBinding.Instance! Null check warning

### ISSUE THREAD

**Issue by umitkirtil** [jonbhanson/flutter_native_splash#351]
**Describe the bug**
Flutter v3 WidgetsBinding.Instance! Null check warning

**To Reproduce**
Just create blank project , add this dependency and viola this warning comes up.

**Expected behavior**
Not to see any runtime warning 

i believe this is related to this : https://github.com/flutter/flutter/issues/103561

Possible solution : fix WidgetBinding? Definition.

**Comment by Hixie** [comment]
Are you using fvm?

**Comment by umitkirtil** [comment]
> Are you using fvm?

Hi. No i am not.

**Comment by Hixie** [comment]
Sounds like the flutter_native_splash package can be fixed using `dart fix --apply`.

**Comment by umitkirtil** [comment]
> Sounds like the flutter_native_splash package can be fixed using `dart fix --apply`.

Saw it there . i will try tomorrow and update this issue. Whether it fix or not

Thanks for the info

**Comment by jonbhanson** [comment]
I will push out an update soon that should resolve this.
