### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by Emeka212** [jonbhanson/flutter_native_splash#352]
Because flutter_native_splash >=2.2.0 depends on path ^1.8.1 and every version of flutter_test from sdk depends on path 1.8.0, flutter_native_splash >=2.2.0 is incompatible with flutter_test from sdk.
So, because kakula depends on both flutter_test from sdk and flutter_native_splash ^2.2.0+1, version solving failed.

**Comment by Emeka212** [comment]
this is the error am facing when i try running pub get on my flutter project after putting the current version of  this package on my app, is there a way to fix it, cus i can't understand this question

**Comment by jonbhanson** [comment]
What version of Flutter are you running?

**Comment by romandragan** [comment]
@jonbhanson, I have the same issue on Flutter 2.10.5 (latest stable for now).

**Comment by jonbhanson** [comment]
Flutter 3.0 is the latest Flutter version on the stable channel.  If you are running Flutter 2.x, you will have to stay on `flutter_native_splash 2.1.6`.

**Comment by romandragan** [comment]
@jonbhanson, in fact it appears it works with 2.x as well, but it should be current beta version (`2.13.0-0.4.pre`) as it already depends on `path 1.8.1`, not `path 1.8.0`.

@Emeka212 fyi

**Comment by Emeka212** [comment]
> What version of Flutter are you running?

am using flutter 2.10.5, tho i have install a previous version of this package, since the current one is having issue
