### ISSUE TITLE
Viewport in meta tag

### ISSUE THREAD

**Issue by jbaptisteroesch** [jonbhanson/flutter_native_splash#359]
**Describe the bug**
After creating the splashcreen with the command: `flutter pub run flutter_native_splash:create`, flutter generate a warning: 
`WARNING: found an existing <meta name="viewport"> tag. Flutter Web uses its own viewport configuration for better compatibility with Flutter. This tag will be replaced.`  **when building for flutter web**.

**To Reproduce**
1. Install the dependency with `flutter pub add flutter_native_splash`, the dependency add this code to the html file : `<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>`
2. Create a splashcreen with `flutter pub run flutter_native_splash:create`
3. Build you project for **flutter web**
4. The error appear 

**Expected behavior**
According to the flutter warning message, the viewports attributes must be removed.

**Device (please complete the following information):**
 - Device: Flutter web

**Flutter doctor**
`[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.22000.675], locale en-US)
    • Flutter version 3.0.0 at C:\Users\jbroe\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (12 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
`

**Edit**
Erasing the line `<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>`  resolve the problem.

**Edit 2**
Removing the line cause [this problem ](https://bytemeta.vip/repo/jonbhanson/flutter_native_splash/issues/276) that I'm trying to resolve.

**Comment by jonbhanson** [comment]
I think the link you posted in Edit 2 must be to a private repo, because I cannot access it.

In my experience, erasing the meta line removes the warning message, but then you may experiencing a resize glitch of the splash image.  The meta line was added to resolve this resize glitch.

**Comment by jbaptisteroesch** [comment]
The link redirects to a post that you respond. I don't know that guy, and the link is broken, sorry.
However the suject is the same, the meta line is not took into consideration by flutter as mention in the first post : `This tag will be replaced.` what causes glitch.
Let me know if you have a solution for this.
Regards.

**Comment by jonbhanson** [comment]
At this time, I only know of two choices:
1. Leave the meta tag, in which case you will receive the warning.  However, the splash screen will work fine in web.
2. Remove the meta tag, which will remove the warning, However, the splash screen will change size in web.
