### ISSUE TITLE
How can i deleted it

### ISSUE THREAD

**Issue by moyayo801** [jonbhanson/flutter_native_splash#362]
i tried it but now i wanted gone but the splash keeps showing up

**Comment by jonbhanson** [comment]
Use the remove command.

**Comment by moyayo801** [comment]
i tried but still there

**Comment by jonbhanson** [comment]
It it is iOS, you may be seeing [this problem](https://pub.dev/packages/flutter_native_splash#i-see-a-flash-of-the-wrong-splash-screen-on-ios).

**Comment by moyayo801** [comment]
nah its android , i tried the splash screen gave a color then then i wanted to get rid of the whole screen so i deleted the package and i thought that was enough but i kept re running my app but the screen is still there even with the same color i gave

**Comment by jonbhanson** [comment]
Before you remove the plugin you need to run 
```
flutter pub run flutter_native_splash:remove
```
to remove the splash screen.

**Comment by jonbhanson** [comment]
"When your app is opened, there is a brief time while the native app loads Flutter. By default, during this time, the native app displays a white splash screen."
