### ISSUE TITLE
Remove splash screen for web

### ISSUE THREAD

**Issue by sivaprasadnk** [jonbhanson/flutter_native_splash#364]
Splash screen images are good in Android / iOS, but how to remove the same when running for web ?

Setting web: false as mentioned in docs doesn't remove it ;(

**Comment by jonbhanson** [comment]
If you want to remove the splash for only web, set web = true and android & ios to false in the config.  Then run 
```
flutter pub run flutter_native_splash:remove
```
The remove command will operate on whatever platforms are set to true.
