### ISSUE TITLE
I ran the command and it says "native splash complete." but it is not appearing 

### ISSUE THREAD

**Issue by kavyabhargava** [jonbhanson/flutter_native_splash#366]
I am not getting a splash screen just a white screen, I am not sure what the issue is. Its only happening for android

**Comment by jonbhanson** [comment]
Did you observer [this note](https://pub.dev/packages/flutter_native_splash#android-12-support) in the readme?

PLEASE NOTE: The splash screen may not appear when you launch the app from Android Studio. However, it should appear when you launch by clicking on the launch icon in Android.
