### ISSUE TITLE
Light mode resources used for dark mode in some cases

### ISSUE THREAD

**Issue by Hallot** [jonbhanson/flutter_native_splash#368]
**Describe the bug**
In case `background_image`/`background_image_dark` are used, but not `color` or `image`, then the light resources for branding and background image are used in dark mode.

The issue appears to come from the following in cli_command.dart:
```
  if (darkImage == null && darkColor == null) {
    if (image != null) {
      darkImage = image;
    } else {
      darkColor = color;
    }
    brandingDarkImage = brandingImage;
    darkBackgroundImage = backgroundImage;
  }
```
In case we only set `background_image_dark`, then both `darkImage` and `darkColor` will be null, thus `brandingDarkImage` and `darkBackgroundImage` will be replaced by their light version.

I tried to fix it in https://github.com/jonbhanson/flutter_native_splash/pull/350, but it appears the fix was incorrect.

**To Reproduce**
With the following configuration

> flutter_native_splash:
>   background_image: assets/images/app_splash.png
>   background_image_dark: assets/images/app_splash_dark.png

**Expected behavior**
The dark background image is used in dark mode when only  `background_image`/`background_image_dark` are used.

**Comment by jonbhanson** [comment]
I will push an update soon that will fix this.
