### ISSUE TITLE
Add the default storyboard template to docs

### ISSUE THREAD

**Issue by SethuSenthil** [jonbhanson/flutter_native_splash#369]
**Is your feature request related to a problem? Please describe.**
Chances are people who are initially running into this package have already tried other ways of setting the Splash Screen. This causes a problem when the developer has already modified the storyboard on iOS Xcode project, they will likely run into the error 

> Not able to find "LaunchImage" in LaunchScreen.storyboard. Image for splash screen not updated. Did you modify your default LaunchScreen.storyboard file?

**Describe the solution you'd like**
Add an option to override and replace the splash storyboard file with the default boilerplate storyboard file so they can proceed. 

**Describe alternatives you've considered**
Until this becomes a feature, a link to the default storyboard file in the documentation would be helpful so the developers can manually replace the file. 

**Additional context**
This would be a time-saving enhancement, instead of wasting time creating a new Xcode project or going through Github commits to find the compatible storyboard file, it will automatically be replaced or have a link to the default file in the docs. 

[Link to the autogenerated file referenced in this issue: LaunchScreen.storyboard.zip](https://github.com/jonbhanson/flutter_native_splash/files/8801053/LaunchScreen.storyboard.zip)

**Comment by jonbhanson** [comment]
I will push an update soon that will fix this.
