### ISSUE TITLE
Android 12 shows system splashscreen, then it shows custom flashscreen from flutter_native_splash.

### ISSUE THREAD

**Issue by lethanhclub** [jonbhanson/flutter_native_splash#373]
I added this package into my existing project because I got system & custom splashscreens in android 12. I thought I can fix this issue by using flutter_native_splash, but it's still happening when I applied this package.

I am using flutter 3.0 and my config is below:

> flutter_native_splash:
>   color: "#e1f5fe"
>   image: assets/images/logo_lockup_flutter_vertical.png
>   color_dark: "#042a49"  
>   image_dark: assets/images/logo_lockup_flutter_vertical_wht.png  
>   android_12:    
>     image: assets/images/logo_lockup_flutter_vertical.png
>     icon_background_color: "#e1f5fe"
>   android: true
>   ios: true
>   fullscreen: true

P/s: I saw the example show only system splashscreen, then it return to home widget without flutter_native_splash.

**Comment by jonbhanson** [comment]
>I added this package into my existing project because I got system & custom splashscreens in android 12.
I'm sorry, I don't understand this sentence.

>I am using flutter 3.0 and my config is below:
Your config does not show any indents.  The config is a YAML file, which will not work if the indents are not correct.

>I saw the example show only system splashscreen, then it return to home widget without flutter_native_splash.
I'm sorry, I don't understand this sentence.

**Comment by lethanhclub** [comment]
> I'm sorry, I don't understand this sentence.

I meant I saw 2 splash screens, one is default by android 12, the other is splashscreen created bt flutter_native_splash package

> Your config does not show any indents. The config is a YAML file, which will not work if the indents are not correct.

yes, it has indents in my YAML. The config is working properly in iOS and android 11.

**Comment by lethanhclub** [comment]
> > I meant I saw 2 splash screens, one is default by android 12, the other is splashscreen created bt flutter_native_splash package
> 
> Can you post a video?

Yes, here's my video about that bug:
[https://drive.google.com/file/d/1jXN7owYr0iLMK0ySr6xtvGT8r_7n0HdO/view?usp=sharing](url)

**Comment by jonbhanson** [comment]
That second splash screen is inside your Flutter app, probably in your main.dart.  You should remove it from your main.dart.

**Comment by lethanhclub** [comment]
> That second splash screen is inside your Flutter app, probably in your main.dart. You should remove it from your main.dart. It looks like that code came from and older example of this package, which was changed with version 2.x.

I am using version 2.2.3

**Comment by jonbhanson** [comment]
Great, this is progress.

The splash screen may not appear when you launch the app from Android Studio. However, it should appear when you launch by clicking on the launch icon in Android.  Also, there are a number of reports that non-Google launchers do not display the launch image correctly.  If the launch image does not display correctly, please try the Google launcher to confirm that this package is working.

**Comment by jonbhanson** [comment]
@jean-gblr your problem is not the same as this ticket.  Please open a new ticket and include a screenshot.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having a problem.

**Comment by EhabSalah** [comment]
This behaviour happens with me, I think the os itself be default showing simple splash first as default. Could anyone tell me now to disable the first splash?

**Comment by jonbhanson** [comment]
The first splash cannot be disabled.  It is automatically displayed in Android 12.

**Comment by EhabSalah** [comment]
That's insane 😇, thank you so much 🤝

**Comment by faaqi** [comment]
@jonbhanson can we still not disable the Android 12 system splash?

**Comment by jonbhanson** [comment]
> @jonbhanson can we still not disable the Android 12 system splash?

Not that I am aware of.
