### ISSUE TITLE
Splash screen not showing when we press back button on android 6

### ISSUE THREAD

**Issue by beamAkshay** [jonbhanson/flutter_native_splash#376]
**Describe the bug**
when we press back button it put app to foreground and when we open it from currently open apps list splash screen not showing, it shows black screen otherwise splash screen working fine. I have tested on latest android version it working fine only problem in android 6.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Device: Samsung Galaxy J7
 - OS: Android 6 

**Flutter doctor**
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1766], locale en-IN)
    • Flutter version 2.10.4 at C:\Users\BIPL-DEV2\Documents\sdks\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 months ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\BIPL-DEV2\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.   
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.68.1)
    • VS Code at C:\Users\BIPL-DEV2\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[√] Connected device (1 available)
    • SM J700F (mobile)     

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Additional context**

**Comment by jonbhanson** [comment]
This package does not support Android 6.  For reference, Google discontinued security updates for Android 6 in August 2018.

**Comment by beamAkshay** [comment]
Okay Thanks
