### ISSUE TITLE
Splash screen shows the wrong image momentarily

### ISSUE THREAD

**Issue by haydgately** [jonbhanson/flutter_native_splash#377]
**Describe the bug**
Splash screen shows the wrong image momentarily (shows icon.png, before replacing it with the clear-icon.png)

**To Reproduce**
Launch the app from fresh

**Expected behavior**
Want to see the clear-icon.png but it shows icon.png for 2 seconds before swapping

**Screenshots**

<img width="238" alt="Screenshot 2022-06-30 at 17 17 06" src="https://user-images.githubusercontent.com/8005325/176727836-09945734-4237-4345-acf9-62ef8d4fa81c.png">
<img width="340" alt="Screenshot 2022-06-30 at 17 17 00" src="https://user-images.githubusercontent.com/8005325/176727840-b67fd764-89eb-4043-bc37-b43448f4fd63.png">

https://user-images.githubusercontent.com/8005325/176727867-ff4920fa-19b8-4797-8251-d592cc1ae18f.mov

**Comment by jonbhanson** [comment]
Check out [I see a flash of the wrong splash screen on iOS](https://pub.dev/packages/flutter_native_splash#i-see-a-flash-of-the-wrong-splash-screen-on-ios).

**Comment by haydgately** [comment]
Thanks @jonbhanson  - is this just for me when developing it? Will users ever encounter this? Thanks for such a swift response
