### ISSUE TITLE
Android 11.  Icon size is 1024 X 1024 but still shrunk

### ISSUE THREAD

**Issue by namlxcntt** [jonbhanson/flutter_native_splash#379]
![image](https://user-images.githubusercontent.com/52909802/177008162-26560ea6-097e-440a-bb88-6d945eada0d2.png)

I am using this library. Followed the basic instructions. My icon is the correct size 1024 x 1024 but when running on an android device it is shrunk in the center of the screen. Can someone explain it to me?

**Comment by jonbhanson** [comment]
Can you post the source image that you are using?

**Comment by namlxcntt** [comment]
I`t is 
![ic_icon_application](https://user-images.githubusercontent.com/52909802/177068442-01ecfb38-9d9f-4c4e-8b30-cf03ede6145a.png)

**Comment by jonbhanson** [comment]
I dropped your image into the the example app, ran it on an Android 11 emulator, and it looks like this:
<img width="266" alt="Screen Shot 2022-07-03 at 10 56 05 PM" src="https://user-images.githubusercontent.com/32202698/177073806-4782af2f-d6c3-4766-9a67-f1b3f7f11c6c.png">

Can you post your config?

**Comment by namlxcntt** [comment]
I have accepted to ignore it because it is only on a few special models. thank you
