### ISSUE TITLE
Package removes android:screenOrientation="portrait" from AndroidManifest

### ISSUE THREAD

**Issue by naamapps** [jonbhanson/flutter_native_splash#380]
**Describe the bug**
When running the create command, it removes the `android:screenOrientation="portrait"` from the AndroidManifest activity.

**To Reproduce**
1. Run `flutter pub run flutter_native_splash:create`
2. The android manifest is formated and removed the `android:screenOrientation` from activity.

**Expected behavior**
There shouldn't be any removal of existing values - unless it is required by the package (which I don't think it is the case here).

**Comment by OutdatedGuy** [comment]
Yo @naamapps, after inspecting the package code it seems that if `android_screen_orientation` property is not defined then `android:screenOrientation` is removed from the manifest.

So in your case, just add `android_screen_orientation: portrait` in the splash specifications.
