### ISSUE TITLE
When app restore, splash never ends

### ISSUE THREAD

**Issue by volteretaRestaurante** [jonbhanson/flutter_native_splash#382]
I implemennt this package, and I have GetMaterialApp as main app, then when i change app for another and I restore the instance (like restoration on Android) splash never ends, what can I do?

**Comment by jonbhanson** [comment]
Does everything work OK the first time you run the app?

It sounds like there is something in your codebase that is hanging.  Try returning a  basic widget in your main app without any initialization and see if you still have the same problem.

**Comment by jonbhanson** [comment]
Closing due to no response.  Please feel free to reopen if you still have a problem.
