### ISSUE TITLE
bug in android 12

### ISSUE THREAD

**Issue by mimikayed** [jonbhanson/flutter_native_splash#383]
**Describe the bug**
I'm using your package which works perfectly for all android versions below 12. For android 12, it appears only in emulator but not in real device. I'm stuck on this for 2 weeks now. It's very annoying.

**Expected behavior**
the splash screen should be visible in real devices.

**Screenshots**

**Device (please complete the following information):**
 - Device: galaxy note 10 plus
 - OS: 12

**Flutter doctor**
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19042.1766], locale en-US)
    • Flutter version 3.0.2 at C:\Users\Administrator\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (4 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1766]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 103.0.5060.66
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 103.0.1264.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Additional context**

**Comment by jonbhanson** [comment]
Have you read the [notes in the readme regarding Android 12](https://pub.dev/packages/flutter_native_splash#android-12-support)?

> PLEASE NOTE: The splash screen may not appear when you launch the app from Android Studio. However, it should appear when you launch by clicking on the launch icon in Android.

> PLEASE NOTE: There are a number of reports that non-Google launchers do not display the launch image correctly. If the launch image does not display correctly, please try the Google launcher to confirm that this package is working.

**Comment by jonbhanson** [comment]
If you still have a problem, feel free to reopen.
