### ISSUE TITLE
Add bottom blank line

### ISSUE THREAD

**Issue by mihiron** [jonbhanson/flutter_native_splash#387]
There are no bottom blank line in the generated files.

<img width="706" alt="スクリーンショット 2022-07-17 19 29 49" src="https://user-images.githubusercontent.com/13147691/179394780-3c5ca7e4-98db-4247-b5a6-dd91e02dd0f9.png">
<img width="708" alt="スクリーンショット 2022-07-17 19 30 02" src="https://user-images.githubusercontent.com/13147691/179394781-f45291a3-79e7-4d65-bdc4-24f2d95dac45.png">
<img width="706" alt="スクリーンショット 2022-07-17 19 30 13" src="https://user-images.githubusercontent.com/13147691/179394782-1604ba73-66d8-4308-a3a6-cd0e0184eb09.png">
<img width="703" alt="スクリーンショット 2022-07-17 19 30 25" src="https://user-images.githubusercontent.com/13147691/179394783-4c84b795-f701-4377-9aba-88f928ab282a.png">
<img width="697" alt="スクリーンショット 2022-07-17 19 30 52" src="https://user-images.githubusercontent.com/13147691/179394784-28485470-3df4-4ab9-9a9e-3edc23efcb75.png">
<img width="695" alt="スクリーンショット 2022-07-17 19 31 03" src="https://user-images.githubusercontent.com/13147691/179394785-cf0c3c41-857f-4fd6-af76-15364d4d48a5.png">
<img width="699" alt="スクリーンショット 2022-07-17 19 31 19" src="https://user-images.githubusercontent.com/13147691/179394786-2cc118d1-13c1-4aef-a31a-22029321cea5.png">
<img width="699" alt="スクリーンショット 2022-07-17 19 31 32" src="https://user-images.githubusercontent.com/13147691/179394788-ed7fbec6-5f59-4155-92d7-c48233b62aec.png">
<img width="694" alt="スクリーンショット 2022-07-17 19 32 23" src="https://user-images.githubusercontent.com/13147691/179394789-62c5686b-bdad-4883-a800-5c4407814285.png">
<img width="697" alt="スクリーンショット 2022-07-17 19 32 38" src="https://user-images.githubusercontent.com/13147691/179394790-6622c125-7c08-430e-ba27-4e5f973348de.png">
<img width="707" alt="スクリーンショット 2022-07-17 19 33 03" src="https://user-images.githubusercontent.com/13147691/179394791-c83b8f47-2710-40ad-9610-9e193e7d0dd5.png">

**Comment by jonbhanson** [comment]
Resolved by PR #388.
