### ISSUE TITLE
Splash screen show correct image on some devices while on some devices the app-icon is coming on splash screen.

### ISSUE THREAD

**Issue by gopal-goyal** [jonbhanson/flutter_native_splash#389]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Flutter doctor**
Please paste the results of the `flutter doctor -v` here

**Additional context**

**Comment by jonbhanson** [comment]
Some non-Google launchers do not correctly render the splash screen according to Android 12's splash screen API.  The problem lies with those launchers, not this package.

**Comment by jonbhanson** [comment]
> I can confirm this issue on a Google Pixel 6 as well, were I expect a Google launcher.

Please advise how to reproduce, because I tried it with the example app in this package (set the android12 options in the `pubspec.yaml`) and it displays the splash correctly on my Google Pixel 6.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having a problem.
