### ISSUE TITLE
duration bug 

### ISSUE THREAD

**Issue by Alyy2021** [jonbhanson/flutter_native_splash#391]
**Describe the bug**
Dear Jony 
the package after I install it, I faced issue with duration 
when the phone duration, the splash didn't show well 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Flutter doctor**
Please paste the results of the `flutter doctor -v` here

**Additional context**

**Comment by jonbhanson** [comment]
Closing due to no response.  Please feel free to reopen with a clear description if you still have a problem.
