### ISSUE TITLE
(Web) Meta tag warning

### ISSUE THREAD

**Issue by OutdatedGuy** [jonbhanson/flutter_native_splash#397]
**Describe the bug**
When running on web, this warning is printed
```log
WARNING: found an existing <meta name="viewport"> tag. Flutter Web uses its own viewport configuration for better compatibility with Flutter. This tag will be replaced.
```
as Flutter inserts it's own meta tag when building.

This isn't anything serious but still is a warning.

### Solution
Don't manually insert meta tag using package

**Comment by jonbhanson** [comment]
The meta tag was inserted to solve a glitch where the [splash logo changes sizes](https://github.com/jonbhanson/flutter_native_splash/issues/276).  The meta tag solves this issue, but unfortunately this warning appears now.  I think it is preferable to have the glitch resolved, even if the warning appears as a result.

**Comment by OutdatedGuy** [comment]
Does it only occurs on mobile web/browser?

**Comment by OutdatedGuy** [comment]
I checked, and it mostly happens on mobile devices and not on desktop/laptops. It doesn't have any workaround.

I'll send a PR if I got any updates on it.

**Comment by jonbhanson** [comment]
Yes
