### ISSUE TITLE
Image stretched and status bar is hidden.

### ISSUE THREAD

**Issue by badaween-ahmed** [jonbhanson/flutter_native_splash#40]
I use this package in an old project and it worked totally fine. But not working in a newly generated project, I didn't get any error and both projects are in Android X. The bug is showing in both emulators and physical device. I did add `fill: true`

![Screenshot_20191228-183713](https://user-images.githubusercontent.com/53362329/71544173-da781e00-29a1-11ea-9783-0049a458cef7.png)
![Screenshot_20191228-183717](https://user-images.githubusercontent.com/53362329/71544175-dfd56880-29a1-11ea-8f40-1e94cb716a44.png)

**Comment by badaween-ahmed** [comment]
`<bitmap android:gravity="center" android:src="@drawable/splash" />`
I changed  `fill` to `center` and the image is not stretched now. And one thing I forgot to say, after the splash image it's showing a dark screen.

**Comment by badaween-ahmed** [comment]
https://github.com/henriquearthur/flutter_native_splash/issues/39#issuecomment-568915711
My problem temporarily solved by removing that line. Thanks.

**Comment by maPer77** [comment]
@badaween-ahmed 
If you have a problem with the image skipping at the beginning of the display, I recommend trying to include this line in styles.xml:
`<item name="android:windowShowWallpaper">true</item>`
I don't know if this can cause any problems with viewing the app later, so I had no problem.

**Comment by badaween-ahmed** [comment]
@maPer77 I removed `<item name="android:windowFullscreen">true</item>` this line and it's fixed.

**Comment by maPer77** [comment]
Yes, I know you removed it, I just gave you a hint if it happens that the image changes position when starting the application, this is the solution.

**Comment by tenhobi** [comment]
I also face this issue. `android_disable_fullscreen` didn't fix it. I temporarily commented `<item name="android:windowFullscreen">true</item>`.

**Comment by polilluminato** [comment]
> `<bitmap android:gravity="center" android:src="@drawable/splash" />`
> I changed `fill` to `center` and the image is not stretched now. And one thing I forgot to say, after the splash image it's showing a dark screen.

I've got also the dark screen after the splash but I think it's related to flutter itself and not to 
`flutter_native_splash`

[flutter 1.12.13+hotfix5 Black screen appears when loading #47582](https://github.com/flutter/flutter/issues/47582)
[Black screen before opening the first screen (Android) #47024
](https://github.com/flutter/flutter/issues/47024)

I hope they solve the problem quickly.

**Comment by schultz9998** [comment]
> @badaween-ahmed
> If you have a problem with the image skipping at the beginning of the display, I recommend trying to include this line in styles.xml:
> `<item name="android:windowShowWallpaper">true</item>`
> I don't know if this can cause any problems with viewing the app later, so I had no problem.

That helped to stop the image from jumping! That's great!

**Comment by jonbhanson** [comment]
Should be solved by recent updates.  Please reopen if you experience any other difficulty.
