### ISSUE TITLE
android 12 showing app icon and not image

### ISSUE THREAD

**Issue by Surk217** [jonbhanson/flutter_native_splash#400]
Hey,
I'm testing on a pixel 6 (android 12), when I start my app I see the app icon (currently default flutter icon) and not the asset I added.
I tested on android 11 emulator and it showed the right splash screen.

Since I'm using a pixel I guess it uses a google laucher so that shouldn't be a problem.

Can you help me solve this, please? I've been stuck for days.

this is my pubspec setup:
 color: "#5bdabe"
  color_dark: "#5bdabe"
  image: assets/splash_logo.png
  image_dark: assets/splash_logo.png
  android12:
    image_dark: assets/splash_logo.png
    image: assets/splash_logo.png

**Comment by jonbhanson** [comment]
Did you see this note in the readme:
> PLEASE NOTE: The splash screen may not appear when you launch the app from Android Studio. However, it should appear when you launch by clicking on the launch icon in Android.

**Comment by jonbhanson** [comment]
Your config should have a `android_12` section, not a `android12` section.

**Comment by elliotrtd** [comment]
@jonbhanson This may be related to the dark mode settings. 

In my app android_12 was NOT taking the value for _image_ when in dark mode when _dark_image_ was not defined. I had to force dark_image to use the same value, this was easily missed in another app and it was only whilst testing this one with dark mode left on I found the problem.

**Comment by patrick-enzo** [comment]
@elliotrtd I also experience this issue. The fix you mentioned worked for us as well.

**Comment by jonbhanson** [comment]
Thanks @elliotrtd for the heads up on this issue.  I will push out an update that addresses this.
