### ISSUE TITLE
How can I remove splash screen ?

### ISSUE THREAD

**Issue by OmarAbdelazeem** [jonbhanson/flutter_native_splash#404]

**Comment by jonbhanson** [comment]
With the command `flutter pub run flutter_native_splash:remove`.

**Comment by lramondev** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:AAPT: D:\Sources\Flutter\divina\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v31\values-v31.xml:8: error: resource drawable/android12splash (aka com.example.divina:drawable/android12splash) not found.
     D:\Sources\Flutter\divina\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v31\values-v31.xml:8: error: resource drawable/android12splash (aka com.example.divina:drawable/android12splash) not found.
     D:\Sources\Flutter\divina\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-night-v31\values-night-v31.xml:8: error: resource drawable/android12splash (aka com.example.divina:drawable/android12splash) not found.

**Comment by jonbhanson** [comment]
@lramondev please open a new ticket.
