### ISSUE TITLE
easy_localization incompatibility

### ISSUE THREAD

**Issue by pjpsoft** [jonbhanson/flutter_native_splash#406]
I don't know if it is considered as a bug, but wanted to mention it
**Describe the bug**
depends on both easy_localization_loader ^1.0.0 and flutter_native_splash ^2.2.7, version solving failed

**To Reproduce**
add easy_localization and easy_localization_loader

**Screenshots**
Because flutter_native_splash >=2.2.3 depends on xml ^6.1.0 and easy_localization_loader 1.0.0 depends on xml ^5.0.2, flutter_native_splash >=2.2.3 is incompatible with easy_localization_loader 1.0.0.
And because no versions of easy_localization_loader match >1.0.0 <2.0.0, flutter_native_splash >=2.2.3 is incompatible with easy_localization_loader ^1.0.0.
So, because stemarg depends on both easy_localization_loader ^1.0.0 and flutter_native_splash ^2.2.7, version solving failed.

**Comment by jonbhanson** [comment]
This issue should be raised with `easy_localization_loader`.  That package is running the old version of `xml` and needs to be updated.
