### ISSUE TITLE
App icon is display in splash screen  in Android 12

### ISSUE THREAD

**Issue by darshil123332** [jonbhanson/flutter_native_splash#409]
How to display the full image of the splash image on the splash screen instead of the app icon in android 12?

 - Device: Samsung galaxy s22
 - OS: Android 12

**Comment by jonbhanson** [comment]
Android 12 does not have support for full screen image on the splash screen.  [Android 12 in readme](https://docs.flutter.dev/development/platform-integration/android/splash-screen-migration).
