### ISSUE TITLE
Splash Screen Image Size Issue on Portrait and Landscape

### ISSUE THREAD

**Issue by Asmat906** [jonbhanson/flutter_native_splash#411]
I have used a native splash screen package.
1: How to resize the image?
2: how can we use the same image both for portrait and landscape.
The image that I am using working fine on landscape , but in portrait the image stretched?
It wi be good to know about it's detail and also the image size property also.
Thanks

**Comment by jonbhanson** [comment]
1. Resize the image before you use the package: [How to resize an image](https://www.google.com/search?q=how+to+resize+an+image).
2. Don't use a mode that stretches the image, use something like a center mode instead.
