### ISSUE TITLE
android_gravity and web_image_mode does not work

### ISSUE THREAD

**Issue by fasterlars** [jonbhanson/flutter_native_splash#418]
**Describe the bug**
I have an image with a background and a logo in the middle of the image. I would like this image to be centered, not stretched and not shrinked, in the splash screen. I´ve tried several formats and resolutions, but I cannot find a setup that fits the majority of device dimensions (small phone, large phone, small tablet and large tablet).
As far as I can understand the image will be stretched per default. But there are other options like `android_gravity `and `web_image_mode`, but neither of these seems to work. They don´t seem have any effect on how the splash screen is rendered.
Am I missing something?

**Comment by jonbhanson** [comment]
@fasterlars please include what platform you are having the problem with and a copy of your yaml config.

**Comment by fasterlars** [comment]
Android is my target platform. The emulation device that I´m using is a 10.1 inch tablet.  This is my config:
```
flutter_native_splash: 
  background_image: "assets/splash.png"   
  android_gravity: center 
  web_image_mode: center
```
This is the image I am using is a bacground with a square logo:
![image](https://user-images.githubusercontent.com/42839536/190322730-fc4d2b5b-b748-41d4-93c7-19e6d4a88b12.png)

The result:
![image](https://user-images.githubusercontent.com/42839536/190322812-1dedbc58-362b-4095-888a-b25c88a60204.png)

If you overlay the original and the generated image, you can see that the logo is stretched:
![image](https://user-images.githubusercontent.com/42839536/190323004-b72b5ae1-a76c-473d-bf8b-6748ce5ee72e.png)

Ive tried playing around with both the android_gravity and the web_image_mode settings, but none of them have any effect on the end result.

Thanks for the help!

**Comment by jonbhanson** [comment]
@fasterlars I tried reproducing the problem, but when I ran it, it was the splash logo was centered.  I tried running it on a Nexus 10 tablet (API 30) so that the stretch would be very obvious.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/32202698/190904135-e3e16ea1-1d39-4d9e-b036-f986a279f505.png">

**Comment by fasterlars** [comment]
Hi Jon.
I created a Nexus 10 (api 30) emulator, but the problem remains the same:
![image](https://user-images.githubusercontent.com/42839536/190925027-74af7e69-4177-487e-b5a0-191151e91f1d.png)
On the screenshot you attached, the splash is very small and in the middle? How come it doesen´t fill the screen as it should? Can you make it fill the screen, and not not stretched?

**Comment by jonbhanson** [comment]
@fasterlars can you send me a copy of your project?  Stripped down if necessary.

**Comment by jonbhanson** [comment]
The problem is that you are using `background_image` instead of `image`.  As stated in the readme:
> Use background_image to set the background of your splash screen to a png image.  This is useful for gradients. The image will be stretch to the size of the app.

**Comment by fasterlars** [comment]
Ah, I totally misunderstood the documentation, sorry! I didn´t think you could use multiple images (background and a logo), to lay on top of each other. My bad.
As far as I can see, the branding image is the same as image, except for the positioning value. It would be nice if you could add an offset/margin/padding. So the branding image wont be fixed directly to the bottom.

Anyways, thanks alot!
