### ISSUE TITLE
Not working on OS version: iOS 15.6.1

### ISSUE THREAD

**Issue by sharabiddin** [jonbhanson/flutter_native_splash#419]
App launched to splash screen only. `FlutterNativeSplash.remove()` method is not compatible i think

OS version: iOS 15.6.1

**Comment by floheitzmann** [comment]
Have the same problem, the splash screen will not disappear on my real device.

**Comment by jonbhanson** [comment]
When I tried updating my device, it updated to 15.7.  I tried the demo of this package and the splash screen was removed correctly.  If you are still having trouble, please advise how to reproduce.

**Comment by EArminjon** [comment]
I've ios 15.6.1, i tested and FlutterNativeSplash.remove() works fine :/, are you sure remove() is well called ?

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having a problem.
