### ISSUE TITLE
Add more informations to README

### ISSUE THREAD

**Issue by tenhobi** [jonbhanson/flutter_native_splash#42]
It would be awesome if the README would provide more information about possible inputs.

For example, it is not clear what `fill` means and how it is different from `android_disable_fullscreen`.

Also, if the `fill` is used, it seems (Android) that it switches the whole app to full screen. (`<item name="android:windowFullscreen">true</item>`), not only the splash screen. Is this desired?

**Comment by henriquearthur** [comment]
`fill` means the image will fill entire screen.
`android_disable_fullscreen` disables full screen during splash screen (meaning it will show status bar). 

I agree it should be more clear in README.

> Also, if the fill is used, it seems (Android) that it switches the whole app to full screen. (<item name="android:windowFullscreen">true</item>), not only the splash screen. Is this desired?

This is a bug introduced by a change in the default content of files in newest versions of Flutter. See https://github.com/henriquearthur/flutter_native_splash/issues/39#issuecomment-568915711

**Comment by tenhobi** [comment]
OK, so `fill` only applies to the image used (now it's a bug and does full screen).
And `android_disable_fullscreen` disables full screen during (only) splash screen.
