### ISSUE TITLE
Splash screen not showing on android 12

### ISSUE THREAD

**Issue by abdulkash** [jonbhanson/flutter_native_splash#422]
Here is my pubspec.yaml file

flutter_native_splash:
  background_image: assets/images/fremee_background.png
  image: assets/images/app_logo.png

  android_12:
    image: assets/images/app_logo.png
    icon_background_color: "#000000"

**Comment by jonbhanson** [comment]
Have you read the [notes in the readme regarding Android 12](https://pub.dev/packages/flutter_native_splash#android-12-support)?

> PLEASE NOTE: The splash screen may not appear when you launch the app from Android Studio. However, it should appear when you launch by clicking on the launch icon in Android.

> PLEASE NOTE: There are a number of reports that non-Google launchers do not display the launch image correctly. If the launch image does not display correctly, please try the Google launcher to confirm that this package is working.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having a problem.

**Comment by tim-eucalyptus** [comment]
What is a "Google launcher"?

**Comment by jonbhanson** [comment]
A launcher is essentially the app that displays your home screen, be it your apps, widgets, app drawer, etc.
In a Google phone like a Pixel, the launcher software is made by Google.  However, other phone makers may replace the launcher with their own launcher.
