### ISSUE TITLE
Removing splash screen when tap notification

### ISSUE THREAD

**Issue by cancng** [jonbhanson/flutter_native_splash#423]
I have Firebase Cloud Messaging on my app and also I am using the `flutter_native_splash` package. Everything is working as I wanted. But application is not working, I mean it is not in background it is completely closed and when notification come and user press the notification it does not redirect to the page. 

How can I disable or remove splash screen just tap notification situtation?

My main code
```dart
main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  FlutterNativeSplash.remove();
  setupLocator();
  await GetStorage.init();
  Get.put(MainController());

  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);

  runApp(const MyApp());
}
```

My tap notification function

```dart
Future<void> onTapNotification(RemoteMessage message) async {
  log('Notification tapped', name: 'TAP NOTIFICATION');
  inspect(message);
  FlutterNativeSplash.remove();
  Get.toNamed(
    '/notification-news',
    parameters: {
      "news_id": message.data['news_id'],
    },
  );
}
```

**Comment by jonbhanson** [comment]
> How can I disable or remove splash screen just tap notification situtation?

Do you want to disable the splash screen in the case when a user opens the app from a notification?

Unfortunately I am not aware of a way to accomplish this.

**Comment by jonbhanson** [comment]
Sorry, this question is outside the scope of this package.  I suggest you post a question on [stackoverflow](https://stackoverflow.com/).
