### ISSUE TITLE
iOS Splash Screen Disappears Before main()

### ISSUE THREAD

**Issue by ScottWallace** [jonbhanson/flutter_native_splash#424]
**Describe the bug**
On iOS, the splash screen from `LaunchScreen` disappears before the first call to the `main()` function in main.dart. The first lines of `main()` are:

```
void main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();

  if (kDebugMode) {
    print('Hello world');
  }

  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  if (kDebugMode) {
    print('FlutterNativeSplash.preserve');
  }
```
In a vscode debug breakpoint on the first line, the splash screen is already gone. There is nothing to `preserve()`. The screen shows black until the initialization is complete.

This isn't the cache issue. I've deleted the app, restarted and erased the simulator. It also occurs in a release build on actual device.

How do I insure the splash screen from xcode stays around long enough to be preserved?

**Expected behavior**
The xcode splash screen should stick around long enough to be preserved.

**Flutter doctor**
```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-US)
    • Flutter version 3.3.2 on channel stable at /Users/scottwallace/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (7 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/scottwallace/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/scottwallace/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 0A786F31-05AA-4D98-AF40-7918DFF6EB69 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

pubspec.yaml file:
```
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/images/transparentlogolessmargin.png"
  android: false
  ios: true
  web: false
  # Changes? flutter clean && flutter pub get && flutter pub run flutter_native_splash:create

```

**Comment by ScottWallace** [comment]
Update: When I comment out the `.remove()` the screen stays black, and the main screen never appears.

**Comment by ScottWallace** [comment]
Update: I checked that the image file is properly in the assets section of the pubspec.yaml. Also, the splash screen properly displays the correct colors based on light/dark mode when it briefly appears. It then changes to black with no logo regardless of light/dark mode.

I wonder if it's an xcode 14, or newest flutter (stable 3.3.2), or new iOS (14.0) issue?

**Comment by ScottWallace** [comment]
Update: Tested on iOS 15, also shows black screen after initial splash. Can't downgrade my flutter or xcode.

**Comment by ScottWallace** [comment]
Updated: Ran the example program, with same newest flutter and xcode. A white screen is shown during the countdown. No background colors or images are shown. Don't know why it's white instead of black, but it's not working correctly.

I strongly suspect it's related to either Xcode 14 or Flutter 3.3.2.

**Comment by ScottWallace** [comment]
Update: Noticed the quotation marks around the image name in the pubspec.yaml file. Removed those, didn't help. When I discover the issue, I'll update here for posterity.

**Comment by jonbhanson** [comment]
I would suggest temporarily removing this package from your project and see if the problem goes away.

**Comment by ScottWallace** [comment]
I have been into the wilds and seen many things, and I come back with the greatest of treasures... The Solution.

In your `Info.plist` file, make sure the `UILaunchStoryboardName` string value is `LaunchScreen` and not `LaunchScreen.storyboard`.

If you set the launch screen using the editor Target -> General -> Launch Screen File, Xcode will append the `.storyboard` extension. You don't want that. You very much don't want that. You will lose many hours trying to find the problem (unless you've found this thread.)

Edit the `Info.plist` file as source code, and make sure `.storyboard` extension isn't there. Then, the Target -> General -> Launch Screen File value will appear blank, which is what you want. I finally solved this by performing a Diff on my `Info.plist` file, and that of this project's example. "Surely not...", he exclaimed, but, indeed, that's the problem.

Here's a few additional tips found on the way:

1) Initializations become trickier as a project grows. Make sure yours is exactly correct, in the correct order, with no warnings or errors ... ever. I chose to create a static class called `Initializer`, and I dumped all that stuff into there. It made it easier to initialize everything because it was in one place. I call it via a `static Init() async {...}` function, just before `runApp`, and after having made `main()` an `async`.

Here's my `main()`. Note, I do some init'ing in main, because it just feels right. The rest, in Init(), is a glorious melange of Firebase, Messaging function setups, GetX controller lazyPuts, start page and other saved preferences, checking for first-time run, AppTrackingTransparency BS, and more. This is what init'ing an app has become, and it's right to treat it as it's own thing, rather than sprinkling it about.

```
Future<void> main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();

  if (kDebugMode) {
    print('Hello world');
  }

  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  if (kDebugMode) {
    print('FlutterNativeSplash.preserve');
  }

  setPathUrlStrategy();
  if (kDebugMode) {
    print('setPathUrlStrategy');
  }

  if (Platform.I.isWeb != true) {
    MobileAds.instance.initialize();
    if (kDebugMode) {
      print('MobileAds.instance.initialize');
    }
  }

  SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []);
  if (kDebugMode) {
    print('SystemChrome.setEnabledSystemUIMode');
  }

  await SharedPrefencesService().init();
  if (kDebugMode) {
    print('SharedPrefencesService().init');
  }

  await JustAudioBackground.init();
  if (kDebugMode) {
    print('JustAudioBackground().init');
  }

  await Initer.init();

  runApp(const SixtyThreeRed());
}
```

2) If your Xcode startup code is throwing warnings, or, God forbid, errors, pay attention! It's easy to say, "I'll deal with that later." No. These are "layering errors", that is to say, an error that will cause a later error that you shouldn't solve - solve the first one instead.  It's a layer. Much time and trouble saved by making sure the iOS Swift code performs flawlessly, before you even hit the first line of `main()`. 

3) Google is gamed. Finding the answer to an obscure problem requires a) having a keen eye to spot promotional web pages that pretend will solve things but instead are copy-paste text of obvious things ending in a product they want to sell you, and b) carefully avoiding the "Just delete it all and start over" crowd. Google is a complete piece of hot garbage right now. It's Amazon's best friend, but your worst enemy.

So. That's it. `.storyboard`. That was all it was. Much learned, and I have a better product for it, but screw this kind of learning and improvement. 

Next time, I just want to know the answer.

**Comment by jonbhanson** [comment]
@ScottWallace you are a poet. 🤩 Glad you fixed it... sorry it was such a slog!

**Comment by kienvtqhi** [comment]
@ScottWallace Thank you so much. This topic save my day :)

**Comment by agordeev** [comment]
@ScottWallace THANK YOU FOR THIS!
The `storyboard` part is not needed. This is mentioned in the README, but I missed that. It should be emphasized.

**Comment by giantss** [comment]
@ScottWallace Thank you so much. This topic saves my day :)
