### ISSUE TITLE
android 12 image appears blurred

### ISSUE THREAD

**Issue by ahmetcanpoyrazizmirteknoloji** [jonbhanson/flutter_native_splash#425]
In android 12 image appears blurred any help? I am using 2.2.9 version

**Comment by ahmetcanpoyrazizmirteknoloji** [comment]
I try different images but all of them showing blurry, in Ios there is no problem.

![Screen Shot 2022-09-22 at 14 59 59](https://user-images.githubusercontent.com/108858310/191741159-c51b2a08-3d33-4a6a-90d5-f8a9a5309250.png)

**Comment by jonbhanson** [comment]
What is the size of your source image?

**Comment by ahmetcanpoyrazizmirteknoloji** [comment]
I tried different sizes 240x240,160x160 etc.. with different images, there is a problem but I did not found why

**Comment by jonbhanson** [comment]
As stated in the readme,

>    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
>    # 640 pixels in diameter.
>    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
>    # 768 pixels in diameter.

**Comment by erperejildo** [comment]
> As stated in the readme,
> 
> > ```
> > App icon with an icon background: This should be 960×960 pixels, and fit within a circle
> > 640 pixels in diameter.
> > App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
> > 768 pixels in diameter.
> > ```

I'll use this same issue to ask about similar thing.

This is my circle/container (the canvas is 1152×1152):
![image](https://github.com/user-attachments/assets/b390fde7-fb86-469a-b2be-266c26c6d5a9)

The image exported has enough quality:
![splash_android12](https://github.com/user-attachments/assets/8db205b6-bcab-4f0f-b3c0-9e591be6f860)

but not the generated icon:
![WhatsApp Image 2024-08-28 at 16 57 09_e02c4c98](https://github.com/user-attachments/assets/888cb540-1c8b-430c-bb37-5c3d2a9123c5)

Also, what should be the size for the branding image? I don't find anything information related in the documentation
