### ISSUE TITLE
Android 12 still displaying app icon as splash image

### ISSUE THREAD

**Issue by Prince-Kd** [jonbhanson/flutter_native_splash#427]
Even after setting the image under android 12, the app icon still shows as the splash image

**Comment by jonbhanson** [comment]
Please supply your config and a screenshot of the splash.  Have you read the [readme notes on Android 12](https://pub.dev/packages/flutter_native_splash#android-12-support)?

**Comment by arnirichard** [comment]
``![Screenshot_20220926-041507](https://user-images.githubusercontent.com/95013472/192165976-63fb1ff8-45e2-4714-86e7-76ab2bada7f3.jpg)

My Android 12 app splash looks like this, my config is

```flutter_native_splash:
  color: "#BCBCBC"
  image: "assets/icons/boat_blue_1024.png"
  android_12:
    image: assets/icons/boat_blue_960.png
    color: "#BCBCBC"
    icon_background_color: "#BCBCBC"```

**Comment by jonbhanson** [comment]
@arnirichard I see a splash page with color #BCBCBC and a boat, and a config that has color #BCBCBC and a boat.  Is there a problem?  Also, I have no context - are you the same user as @Prince-Kd, posting the follow up info I requested, or do you have your own problem?

**Comment by arnirichard** [comment]
@jonbhanson I was expecting that the icon would fill the white area. I was wondering if that is the same problem as reported. Is this expected look?

**Comment by jonbhanson** [comment]
Please post your 'assets/icons/boat_blue_960.png' image.

**Comment by arnirichard** [comment]
![boat_blue_960](https://user-images.githubusercontent.com/95013472/192281172-55064d90-a114-4924-aa26-4bf3b1df5416.png)

**Comment by arnirichard** [comment]
It is 960x960

**Comment by jonbhanson** [comment]
I ran your config and this is how it appeared for me.

I don't know why yours looks different.  Send me your app source (stripped out if necessary) if you'd like me to check further.

<img width="831" alt="Screen Shot 2022-09-26 at 9 00 32 AM" src="https://user-images.githubusercontent.com/32202698/192283095-5c9b0c8e-55e7-4e73-9002-80027ebc83f1.png">

**Comment by arnirichard** [comment]
Thanks, I will investigate and report here my findings.

**Comment by jonbhanson** [comment]
If you are using a non-google launcher, you may want to try running it on a Google emulator.  Some of the non-google launchers don't seem to be handling the splash according to Google's specs yet on Android 12.

**Comment by arnirichard** [comment]
I am using a Samsung device, but I will try Google, thank you

**Comment by arnirichard** [comment]
@jonbhanson I am getting the same as you on Pixel emulator. How can I at least fix that?

**Comment by arnirichard** [comment]
@jonbhanson I created an image 1500x1500 and then placed the 1024x1024 in the center, then it appears ok, but it is a hack

**Comment by arnirichard** [comment]
I gues this mean the pic should be 960x960 and the icon should be 640x640, I will try that

  # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.

**Comment by jonbhanson** [comment]
Sounds like this is OK to close?

**Comment by arnirichard** [comment]
@jonbhanson I think the initial problem sounds like he uses Samsung, there is little to do about it.

**Comment by apoorvpandey** [comment]
Hi @jonbhanson  I am using the same package and on every device It is showing splash as App Icon, What's the issue?

**Comment by apoorvpandey** [comment]
Hi @jonbhanson  I am using the same package and on every device It is showing splash as App Icon, What's the issue? please help!!!

**Comment by jonbhanson** [comment]
@apoorvpandey please open a new ticket and make sure to fill all the details that you will find in the new bug ticket template.

**Comment by apoorvpandey** [comment]
> Hi @jonbhanson I am using the same package and on every device It is showing splash as App Icon, What's the issue? please help!!!

My Config:


`flutter_native_splash:
  color: "#ffffff"
  image: assets/images/man.png
  android_12:
    image: assets/images/man.png
    color: "#ffffff"`

**Comment by apoorvpandey** [comment]
> @apoorvpandey please open a new ticket and make sure to fill all the details that you will find in the new bug ticket template.

Thanks for the quick response, highly appreciate that. I have raised a new issue with details please check. Thanks in advance!

**Comment by apoorvpandey** [comment]
> @apoorvpandey please open a new ticket and make sure to fill all the details that you will find in the new bug ticket template.

Thanks for the quick response, highly appreciate that. I have raised a new issue with details please check. Thanks in advance!
