### ISSUE TITLE
index.html always gets additional lines added

### ISSUE THREAD

**Issue by Bungeefan** [jonbhanson/flutter_native_splash#430]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

Everytime the `create` task is executed, the package adds new lines to index.html. Even if there are already enough lines.

**Configuration**

Shouldn't need any configuration but if in doubt, see configuration from https://github.com/jonbhanson/flutter_native_splash/issues/429

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config
2. Run `flutter pub run flutter_native_splash:create` multiple times
3. See `index.html` for new lines after the last `picture` tag.

**Screenshots**
-

**Additional context**
-

**Comment by jonbhanson** [comment]
Thanks for catching this.  I will soon push an update that includes a fix.

**Comment by Bungeefan** [comment]
Thanks for the quick fix!
Is it intenional that it still adds a single blank line after each `create` execution?
