### ISSUE TITLE
Shouldn't this be a dev_dependencies?

### ISSUE THREAD

**Issue by tobiasht** [jonbhanson/flutter_native_splash#431]
Shouldn't this be a `dev_dependencies` and not a `dependencies`? 

I thought all the files were generated when you run `flutter pub run flutter_native_splash:create`. So there should be no need to compile the package along with the app.

**Comment by tobiasht** [comment]
I found the reason for it in the ReadMe. But if you don't need the splash screen to remain open while your app initialises. You can still use it as a `dev_dependencies`, right? If that is the case, it should be made clearer in the usage section.

**Comment by jonbhanson** [comment]
I will make an update in the readme to clarify this point.  However, it will still only be a small note at the bottom - developers often start with the most prominent example code and only the read the documentation if it does not work, so I want the default to work for everyone.
