### ISSUE TITLE
Image Icon does not fit in circle with Android12

### ISSUE THREAD

**Issue by Sisero986** [jonbhanson/flutter_native_splash#434]
Hello everybody,
I'm using this great library on Android Studio in Windows 11 OS, and I'm able to get the color background and icon image that I need but when I start the debugger, the icon doesn't fit right on the circle used with android 12 version (with emulator and physical device).
Little part of the image is cut by the circle, I tried to change a lot of time the resolution of the image as indicated on the official document in android dev. and on the library description but the problem is always present.

Do you have any idea how to solve this problem?
Could you give ne indication about the right size of the asset images?

**Comment by jonbhanson** [comment]
Did you see this in the readme?
>    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
>    # 640 pixels in diameter.
>    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
>    # 768 pixels in diameter.

**Comment by jonbhanson** [comment]
Feel free to reopen if you are still having trouble.
