### ISSUE TITLE
Android 12+ Splash Screen image showing as App Icon

### ISSUE THREAD

**Issue by apoorvpandey** [jonbhanson/flutter_native_splash#435]
I am using the flutter_native_splash and configured it as video tutorial and documentation the files are generated correctly but still Splash Image is showing as App Icon

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/a.png
  android_12:
    image: assets/images/a.png
    color: "#ffffff"

Paste the flutter_native_splash section of your yaml config.

 - Device: Pixel 4a (Physical Device)
 - OS: Android 13

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to flutter_native_splash:
  color: "#ffffff"
  image: assets/images/a.png
  android_12:
    image: assets/images/a.png
    color: "#ffffff"
2. Run in an emulator  or physical device configured with 
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/a.png
  android_12:
    image: assets/images/a.png
    color: "#ffffff"

**Screenshots**

Config
<img width="988" alt="Screen Shot 2022-10-12 at 02 00 15" src="https://user-images.githubusercontent.com/17758959/195192509-56bc092f-4a07-46de-a3c4-2a30377033f7.png">

Splash image "a.png"
![a](https://user-images.githubusercontent.com/17758959/195192575-5451d9ce-6c36-4203-9a80-72a6a6dd9b96.png)

Output in mobile
![output](https://user-images.githubusercontent.com/17758959/195193246-e1854719-137d-4ba5-9dd6-56e28b2a863b.png)
App Icon
![app_icon](https://user-images.githubusercontent.com/17758959/195193271-f525c58e-57dd-4b3c-8668-4f81b8b059ff.png)

**Comment by liasica** [comment]
Same issuse

**Comment by jonbhanson** [comment]
Are you launching the app from Android Studio?  If so, the splash screen config is not used.  However, it will appear when you launch inside Android by clicking on the launch icon.

**Comment by apoorvpandey** [comment]
I have tried it but it's same!

**Comment by jonbhanson** [comment]
I modified the example app with the parameters that you instructed, and my splash screen looked as follows:

![Screenshot_20221023-124340](https://user-images.githubusercontent.com/32202698/197404669-f9240db7-b422-4783-8514-1d525e50bd82.png)

As far as I can tell everything is working okay.

Can you upload a stripped out version of your app that I can test?

**Comment by apoorvpandey** [comment]
Okay, will share. Thanks

**Comment by danken00** [comment]
> Are you launching the app from Android Studio? If so, the splash screen config is not used. However, it will appear when you launch inside Android by clicking on the launch icon.

Might be worth adding that into the notes somewhere, it caught me out too. Thanks for a great plugin though!

**Comment by cvphat** [comment]
I am using samsung device. It shows app icon if I use One UI launcher but there is no have image if the default launcher is third party

**Comment by jonbhanson** [comment]
> I am using samsung device. It shows app icon if I use One UI launcher but there is no have image if the default launcher is third party

@cvphat this sounds like what is described in the readme:
> PLEASE NOTE: There are a number of reports that non-Google launchers do not display the launch image correctly. If the launch image does not display correctly, please try the Google launcher to confirm that this package is working.

> Okay, will share. Thanks
@apoorvpandey closed due to inactivity.  Feel free to reopen with an example if you are still having a problem.
