### ISSUE TITLE
Web splash Google way

### ISSUE THREAD

**Issue by prologikus** [jonbhanson/flutter_native_splash#436]
I'm trying to optimise my app so i can minimize the loading time of the app, which is already big because of canvaskit, and this plugins adds 8 new images to my app size.

Also, a loading progress animation would be much better nowadays because if it takes too long to load it is better to show a loading animation then a static image.

From Flutter blog: Customizing web app initialization
https://docs.flutter.dev/development/platform-integration/web/initialization

You can see the loading animation here:
https://gallery.flutter.dev

And the code for it is pretty simple and on point, without using other images then the ones for PWA, (icons folder)
https://github.com/flutter/gallery/blob/master/web/index.html

**Comment by jonbhanson** [comment]
> this plugins adds 8 new images to my app size.
Is this a problem?  The client's browser is only going to load one of these images, depending on the pixel density of the device in use.

**Comment by jonbhanson** [comment]
Closed due to inactivity.
