### ISSUE TITLE
No splash screen on iOS / circular image on black screen on Android

### ISSUE THREAD

**Issue by JohnnyRainbow81** [jonbhanson/flutter_native_splash#440]
Hi,

flutter_native_splash: ^2.1.2

Pixel 5 Emulator (Android 12 >) 
iPhone 8 Device, (iOS 15.6.1) 

My pubspec.yaml:

<img width="389" alt="Bildschirmfoto 2022-10-18 um 11 57 37" src="https://user-images.githubusercontent.com/23189088/196399347-a34d5a24-1d32-4467-aa90-2bb027ed34f8.png">

On Android Emulator, a circular Logo is shown on a black screen: 

<img width="360" alt="Bildschirmfoto 2022-10-18 um 11 47 15" src="https://user-images.githubusercontent.com/23189088/196398267-496dbc06-da47-40e7-9edc-d49eb78b7be6.png">

On my iPhone 8, I only get a black screen, no custom splash color, no logo, nothing.

I tried:

`flutter clean && flutter pub get && flutter pub run flutter_native_splash:create`

deinstall app on emulator & device, restart devices, reinstall > no effect

**Comment by jonbhanson** [comment]
Can you post a stripped out version of your app that I can test?

**Comment by JohnnyRainbow81** [comment]
Hi Jon! 
Thank you for your help. Sorry for being this late, I had some major cold to cure... 

Here is my app as barebones as it gets: 

[https://github.com/JohnnyRainbow81/speakyfox_splash_screen_fix.git](url)

Thanks again for looking into it!

**Comment by jonbhanson** [comment]
You have a `flutter_native_splash.yaml` file in your project.  By default, this packages gets it's config from that file.  If you want to use the config found in `pubspec.yaml`, delete the `flutter_native_splash.yaml` file.

**Comment by JohnnyRainbow81** [comment]
This unfortunately doesn't have any effect. 
I deleted `flutter_native_splash.yaml`, ran `flutter clean && flutter pub get` and nothing changed.

**Comment by jonbhanson** [comment]
You have to run `flutter pub run flutter_native_splash:create`.

**Comment by JohnnyRainbow81** [comment]
Oh my. That's what I missed after deleting `flutter_native_splash.yaml`.

Issue closed, thank you very much!!
