### ISSUE TITLE
Android 12 splash screen 

### ISSUE THREAD

**Issue by haithemmihoubi** [jonbhanson/flutter_native_splash#441]
**Is your feature request related to a problem? Please describe.**
The android 12 support isn't working and when we try to implement it shows nothing, only the colour.

**Describe the solution you'd like**
 just verify the support for android 12 with the background image

**Comment by jonbhanson** [comment]
Android 12 does not support a background image on the splash screen.  [docs](https://developer.android.com/develop/ui/views/launch/splash-screen).
