### ISSUE TITLE
Because hellochatpay depends on flutter_native_splash >=2.2.10 which requires SDK version >=2.18.0 <3.0.0, version solving failed.

### ISSUE THREAD

**Issue by CWTgithub** [jonbhanson/flutter_native_splash#442]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

**Configuration**

Paste the flutter_native_splash section of your yaml config.

**Device (please complete the following information):**

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to '...'
2. Run in an emulator configured with '...'
3. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.  If in doubt, attach a screenshot.

**Additional context**

**Comment by jonbhanson** [comment]
You can resolve this by updating the dart SDK in your `pubspec.yaml`: `  sdk: '>=2.18.0 <3.0.0'`

**Comment by CWTgithub** [comment]
Thank you. I'll try upgrading the flutter SDK
