### ISSUE TITLE
How to put splashscreen image fullscreen?

### ISSUE THREAD

**Issue by tanz98** [jonbhanson/flutter_native_splash#443]
How to put splashcreen image fullscreen like this in this package?

![Example Screen](https://user-images.githubusercontent.com/35478469/198541265-e457604d-3e6f-4a9f-9534-f47db0ce2105.png)

I already implement the image was added to center not fullscreen :)

**Comment by jonbhanson** [comment]
The answer depends on the platform:

`android_gravity: fill`
`ios_content_mode: scaleToFill`
`web_image_mode: stretch`

However, if you choose to fill the screen, your image will looked when used on devices of different aspect ratios.  It is better to center an image that does not depend on the size of the screen.

**Comment by tanz98** [comment]
ok sir thank you,but one question again sir... is in this library have an option to make manual splashscreen ui sir? so we can make manual like we create a page, so not just in the center :).

**Comment by jonbhanson** [comment]
Everything you need to know about this package is in the description on the front page.
