### ISSUE TITLE
Dark background image isn't correctly set up on iOS

### ISSUE THREAD

**Issue by CoocooFroggy** [jonbhanson/flutter_native_splash#452]
**Describe the bug**

The dark splash screen `background_image_dark` isn't correctly configured with LaunchBackground.imageset, and only the light `background_image` is used.

**Configuration**

```yaml
flutter_native_splash:
  background_image: "assets/background_light.png"
  background_image_dark: "assets/background_dark.png"
```

**Device (please complete the following information):**
 - Device: Simulator, iPhone 14 Pro (but likely happens on every device)
 - OS: iOS 16.1 (but likely happens on every version)

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Create a new flutter app
2. Add `flutter_native_splash: ^2.2.14` to dependencies
3. Add the above flutter_native_splash configuration to pubspec.yaml
4. Add images to the project under `assets/background_light.png` and `assets/background_dark.png`
5. Run `flutter pub run flutter_native_splash:create`

**Screenshots**
![Image](https://i.ibb.co/zRQZPMS/Screenshot-2022-11-17-at-9-11-38-PM.png)

**Additional context**
LaunchBackground's Contents.json

```json
{
  "images" : [
    {
      "filename" : "background.png",
      "idiom" : "universal",
      "scale" : "1x"
    },
    {
      "idiom" : "universal",
      "scale" : "2x"
    },
    {
      "idiom" : "universal",
      "scale" : "3x"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
```

Issue is the same as #439.

**Comment by jonbhanson** [comment]
I will push out an update soon that should fix this.
