### ISSUE TITLE
Android 12 image not showing

### ISSUE THREAD

**Issue by GiulioWecove** [jonbhanson/flutter_native_splash#457]
I'm trying to create a splash screen for android 12 devices, all the android emulators don't show the image icon, also my device (nothing phone) doesn't show the logo. The only thing that changes is the background color. I've tried with multiple logos on multiple dimensions, also the ones reported on the documentation. I've also tried with a brand new project for testing purposes on 2.2.15 and 2.2.14 versions of the package.

**Configuration**

flutter_native_splash:

 ```
color: "#D8C2BE"
image: assets/images/splashscreen.png
android_12:
  image: assets/images/splashscreen_icon.png
```

Devices: 
 - Device: Nothing phone
 - OS: Android 12
 
 - Device: Multiple Android Emulators
 - OS: Android API 31,32,33

**To Reproduce**
`[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.73.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability`

Make a brand new installation, create the emulators and follow the plugin documentation.

**Comment by jonbhanson** [comment]
There are a [couple circumstances](https://pub.dev/packages/flutter_native_splash#android-12-support) where the icon is not show in Android 12.  Have you ruled these out?

**Comment by GiulioWecove** [comment]
> 

Thank you very much for the reply. 
I've checked and the emulators use Pixel launcher, my physical device don't.

**Comment by mngkvn** [comment]
Same problem here. Tried different emulators and android 12 below. Still didn't work.

**Comment by GiulioWecove** [comment]
I had to make a release of the app that didn't show the icon and on the downloaded app the icon is showing. So I've tried to run the app in release and profile mode but still didn't show up. 
I downloaded the app on my physical device, so on Nothing launcher there should be no problems.

**Comment by SalimliOrxan** [comment]
Works on emulator, but not on physical device (both android 13). When app installed first time splash screen and background color appeared. But when teminate app and enter again, appears only background color.

**Comment by brijeshsoni1300** [comment]
its not showing icon while running it from android studio or vs code 
but its showing when we open application from our physical device by clicking on launcher icon

**Comment by GiulioWecove** [comment]
> 

You are right! When the app is running it didn't show up, but if you stop the process and open it manually (even from emulator) it will appear..

**Comment by NOU-VANNET** [comment]
Android 12 is showing up incorrectly inside circle and it not show the full image.

**Comment by booooohdan** [comment]
> Android 12 is showing up incorrectly inside the circle and it did not show the full image.

Android 13. The same problem. Firstly I see a standard Android 13 splash screen with a big rounded icon, after I see the smaller icon generated by this package. I think we need to option to disable generating splash screen option for Android 12 and 13

**Comment by jonbhanson** [comment]
> You are right! When the app is running it didn't show up, but if you stop the process and open it manually (even from emulator) it will appear..

This is by design: on Android the [splash screen is not shown on a hot start](https://developer.android.com/develop/ui/views/launch/splash-screen#how).

For those who have commented on this ticket, if your problem regards a different circumstance, please open a new ticket and include all the required information in the new ticket template.

**Comment by GiulioWecove** [comment]
> 

When I launch `flutter run` the splash screen is showing, that's not the problem, I've also avoided to call the remove function to let the splash screen always on. It works because I can see the different background color when i change it. The problem here is that I cannot see the icon when I launch a `flutter run` but only if I open the app without the debugger running.

**Comment by jonbhanson** [comment]
@GiulioWecove what you describe is a [problem with Android 12](https://stackoverflow.com/questions/69812590/android-12-splash-screen-icon-not-displaying), not this package.
