### ISSUE TITLE
Instagram-like layout

### ISSUE THREAD

**Issue by tenhobi** [jonbhanson/flutter_native_splash#46]
Hi, how can I accomplish an Instagram-like splash screen, which has two images, one at the bottom and one somewhere in center/top part?

![image](https://user-images.githubusercontent.com/5287596/72759748-e0df6b80-3bd6-11ea-83c8-aa05a62ec210.png)

**Comment by vipinnegi90** [comment]
For different elements, it might not be possible with the current library. 
If I were you I'd give this a try, it might not work but I'd try keeping all elements in one .png.

**Comment by jonbhanson** [comment]
As @vipinnegi90 suggested, you could accomplish this look by integrating both elements into one .png file. 👍🏻
