### ISSUE TITLE
The splash icon is not displayed when the application is launched from Firebase Dynamic Links

### ISSUE THREAD

**Issue by manabu0926** [jonbhanson/flutter_native_splash#461]
**Describe the bug**

I'm currently building a function to launch an app with Firebase Dynamic Links.
As expected, the splash screen will appear when you launch the normal application.
But via Dynamic Links, I don't see the splash icon.

**Configuration**
```pubspec.yml
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.15
... etc

flutter_native_splash:
  color: "#3F51B5"
  image: "assets/images/icon_transparent.png"
  color_dark: "#3F51B5"
  image_dark: "assets/images/icon_transparent.png"
  fullscreen: true
  android_12:
    icon_background_color: "#3F51B5"
    image: "assets/images/splash_android.png"
    icon_background_color_dark: "#3F51B5"
    image_dark: "assets/images/splash_android.png"

```

**Device (please complete the following information):**
 - Device: Oppo Reno5 A
 - OS: Android12

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. set Firebase Dynamic Links
2. click DynamicLinks
3. not show splash app icon(octopus).
4. but, show splash app icon if click app icon.

**Screenshots**

https://user-images.githubusercontent.com/43611707/204127848-63e269df-3283-4eb1-9f42-e20a67ced7e3.mp4

**Additional context**
I'm Japanese, so I'm not good at English.
Feel free to comment if it's hard to understand or if you want more details.

**Comment by jonbhanson** [comment]
As [stated in the readme](https://pub.dev/packages/flutter_native_splash#android-12-support):

> PLEASE NOTE: The splash screen does not appear when you launch the app from a notification. Apparently this is the intended behavior on Android 12: [core-splashscreen Icon not shown when cold launched from notification](https://issuetracker.google.com/issues/199776339?pli=1).
