### ISSUE TITLE
Dynamic text on splash screen

### ISSUE THREAD

**Issue by syeds-git** [jonbhanson/flutter_native_splash#465]
**Is your feature request related to a problem? Please describe.**
This package allows us to display a splash screen while we are initializing the app. However, during initialization the app might be doing several things like downloading images, database, user settings etc. Now all of these together could take some time and the app would just be displaying one single image.

**Describe the solution you'd like**
Would it be possible to allow this plugin to take as input a list of call backs which would return a text message that would be displayed to users for example "Downloading assets", "Downloading player data", "Extracting archives" etc.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by jonbhanson** [comment]
@syeds-git I don't see this feature happening in the near term (unless someone wants to make a PR).  In the meantime, if you want to make this happen, you can use this package to set the splash screen for the native platform, and as soon as Flutter is loaded, switch to a Flutter-based splash screen where it would be simple to display dynamic content while the rest of your initialization takes place.
