### ISSUE TITLE
Blue screen before splash

### ISSUE THREAD

**Issue by jostney** [jonbhanson/flutter_native_splash#468]
https://user-images.githubusercontent.com/108373490/206325665-2f3d1f56-c6f8-4e5d-8cf5-3c0a996bebbf.MOV

**Describe the bug**

A blue screen appears before splash screen

**Configuration**

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png

**Device (please complete the following information):**
 - Device: Iphone 12 Mini
 - OS: iOS 15.7.1

**Comment by Iverson** [comment]
Same problem. iOS 16.1 Simulator.

**Comment by Iverson** [comment]
Had the same problem. This tip helped me - https://pub.dev/packages/flutter_native_splash#i-see-a-flash-of-the-wrong-splash-screen-on-ios
