### ISSUE TITLE
Not working well on android 13

### ISSUE THREAD

**Issue by aqueebqazi** [jonbhanson/flutter_native_splash#471]
Steps to reproduce
followed the android 12 guide to install splash screen
getting flutter logo before the custom splash screen

**Comment by jonbhanson** [comment]
I tried running the example that is included with this package and it ran as expected under API 33 (Android 13).  You will have to provide more info on how to reproduce.

**Comment by jonbhanson** [comment]
Closed for inactivity.  Feel free to reopen if you are still having a problem.
