### ISSUE TITLE
Web image is pixelated

### ISSUE THREAD

**Issue by cedvdb** [jonbhanson/flutter_native_splash#472]
**Describe the bug**

For an image containing text, which is 844x394 this result in an image which is very pixelated. It seems to work fine on android.

It also seems like this package resizes the original image, and I've some doubts about the resizing algo used as I've seen this problem in multiple packages, like assets generator or even the Image package. In case the image package is used to resize, the interpolation can be set to the one which adds a slight blur for better results. I believe it's the average one but I can't recall for certain.

Edit: yeah https://github.com/jonbhanson/flutter_native_splash/blob/2f6e0905f48fb8d0bce34bbc18e1c41e0fc5e644/lib/web.dart#L162

Also some direction about what ratio yields better results with this algo would be nice

**Configuration**

web

**Comment by jonbhanson** [comment]
Just pushed out an update to fix this.
