### ISSUE TITLE
flutter_native_splash not showing image in Android 10

### ISSUE THREAD

**Issue by stolets-k-od** [jonbhanson/flutter_native_splash#479]
Hello!

Android 12, Android 11 working
Android 10 not working image
Color changes successfully

I sent the project to my friend and everything works for him

what could be the problem?

![image](https://user-images.githubusercontent.com/97661116/208486221-327f66ee-5d9a-47d2-a2f8-1d22ae45fd77.png)

**Comment by jonbhanson** [comment]
I tested your config on an Android 10 emulator and it worked fine for me.  However, I see that you have a `color` parameter but not a `color_dark` parameter, even though you have both light and dark mode images.  Maybe one of your images does not show up against the selected color and you need to set a contrasting `color_dark`?

**Comment by stolets-k-od** [comment]
Yes, it turned out that it was necessary to enter the `color_dark` parameter and then there was success.

Conclusions: if we use day and night modes in the project, then it is necessary to configure `flutter_native_splash` for both modes

Thanks!
