### ISSUE TITLE
android12 splash screen 

### ISSUE THREAD

**Issue by jacky70638** [jonbhanson/flutter_native_splash#482]
Opening the app for the first time, there is no splash screen
The second boot is fine
This issue is limited to Android 12 and above

Recreate a flutter project
Start directly, and there is still this problem of no startup screen

This refers to no startup screen
There is a background color, but the launch image does not appear
Only open for the first time

android/app/src/main/res/values-v31/styles.xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    
    <style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">
        <item name="android:forceDarkAllowed">false</item>
        <item name="android:windowFullscreen">false</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
        <item name="android:windowSplashScreenBackground">#FF0000</item>
        <item name="android:windowSplashScreenAnimatedIcon">@drawable/android12splash</item>
        <item name="android:windowSplashScreenIconBackgroundColor">#FF0000</item>
    </style>
    
    <style name="NormalTheme" parent="@android:style/Theme.Light.NoTitleBar">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>

**Comment by thirstyde** [comment]
![image](https://user-images.githubusercontent.com/113355668/209511553-aa3f2143-ad36-4a59-af4a-0ba4925299f8.png)


***This is my command response***
[Android] Creating splash images
[Android] Creating dark mode splash images
[Android] Updating launch background(s) with splash image path...
[Android]    - android/app/src/main/res/drawable/launch_background.xml
[Android]    - android/app/src/main/res/drawable-night/launch_background.xml
[Android]    - android/app/src/main/res/drawable-v21/launch_background.xml
[Android]    - android/app/src/main/res/drawable-night-v21/launch_background.xml
[Android] Updating styles...
[Android]    - android/app/src/main/res/values-v31/styles.xml
[Android]    - android/app/src/main/res/values-night-v31/styles.xml
[Android]    - android/app/src/main/res/values/styles.xml
[Android]    - android/app/src/main/res/values-night/styles.xml
[iOS] Creating  images
[iOS] Creating dark mode  images
[iOS] Updating LaunchScreen.storyboard with width, and height
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
Web folder not found, skipping web splash update...




can not create android 12 splase screen

**Comment by jacky70638** [comment]
Do you also encounter the problem that android12 cannot run out of the startup image?

**Comment by thirstyde** [comment]
can not generate android 12 splash in res folder

**Comment by jacky70638** [comment]
[Android] - android/app/src/main/res/values-v31/styles.xml
[Android ] - android/app/src/main/res/values-night-v31/styles.xml

Isn't this what it is?

**Comment by thirstyde** [comment]
> [Android] - android/app/src/main/res/values-v31/styles.xml [Android ] - android/app/src/main/res/values-night-v31/styles.xml
> 
> Isn't this what it is?

this folder generated but  
![image](https://user-images.githubusercontent.com/113355668/209517505-fd6b8b41-6d07-41aa-9751-cc7e358661bb.png)
image can not generated same as photo

**Comment by jacky70638** [comment]
Do you also encounter the problem of Android 12 startup image?

**Comment by thirstyde** [comment]
> Do you also encounter the problem of Android 12 startup image?

yes,no error show

**Comment by jacky70638** [comment]
I have the same problem with Android 12
However, I opened it for the first time after installation and there will be no startup image
It's normal the second time
do you have this condition

**Comment by thirstyde** [comment]
i have found already one image

**Comment by ziqq** [comment]
I have this same issue, but only 31 API lvl

**Comment by jacky70638** [comment]
@ziqq It seems to be a problem above android12
I still can't find the answer

**Comment by ziqq** [comment]
> @ziqq It seems to be a problem above android12 I still can't find the answer

My config run on 32 and above and below 31 api versions. But not working on 31 api version.

**Comment by jacky70638** [comment]
Looks like we'll just have to wait for an official fix.

**Comment by NTA-trongpq** [comment]
"image" parameter not showing although it's specifited on android 12

**Comment by jacky70638** [comment]
What's the meaning

**Comment by thirstyde** [comment]
I have upgrade my project in 3.3.4 then generate splash screen sucessfully work.

**Comment by ziqq** [comment]
> 

What the 3.3.4 version?

**Comment by thirstyde** [comment]
> 

3.3.4 is flutter sdk version

**Comment by ziqq** [comment]
I'm using 3.3.9 sdk version and i catch this problem on 31 API lvl.

**Comment by thirstyde** [comment]
First of add following lines in pubspec.yaml 

![image](https://user-images.githubusercontent.com/113355668/209807121-4915336f-a894-4a7c-a892-c64467a1ae8c.png)
then open terminal  and run 
=> flutter pub run flutter_native_splash:create
![git](https://user-images.githubusercontent.com/113355668/209806853-3ea63b3b-08f5-44d9-b5d0-b1d2d640e928.png)

**Comment by jacky70638** [comment]
@thirstyde The settings are almost the same, but I still have the same problem
I am using 3.3.9 sdk version

**Comment by jonbhanson** [comment]
Have you seen the [notes](https://pub.dev/packages/flutter_native_splash#android-12-support) on Android 12?  There are a couple cases where the image does not show which are a limitation of Android12.  Here are some [details from google support](https://issuetracker.google.com/issues/205021357#comment14).

**Comment by jacky70638** [comment]
@jonbhanson 
After downloading the app
The first time you turn it on, there will be no startup image
The second time you turn it on, there will be a normal startup image
How can this be explained?

**Comment by ziqq** [comment]
> Have you seen the [notes](https://pub.dev/packages/flutter_native_splash#android-12-support) on Android 12? There are a couple cases where the image does not show which are a limitation of Android12. Here are some [details from google support](https://issuetracker.google.com/issues/205021357#comment14).

Android 12 is working, but not 31 API lvl

**Comment by thirstyde** [comment]
> 

1.first time you install in debug mode 
2.first of you can build apk after install on your phone.

**Comment by jonbhanson** [comment]
@jacky70638   Please clarify: the first time you install, how do you run the app?  Are you tapping the icon in Google's launcher on your Android device to open the app?  If you are running the app any other way like using Android Studio's "debug" button, or running a `flutter run` command, the splash icon will not show on Android 12.  Apparently this is the intended behavior on Android 12: [core-splashscreen Icon not shown when cold launched from notification](https://issuetracker.google.com/issues/199776339?pli=1).

**Comment by paulobreim** [comment]
In my app, only on android 12, the splashscreen is not shown. Only the default icon appears.
I use this same setting in other applications and it works.

My config in pubspec
  flutter_native_splash: ^2.2.17

flutter_native_splash:
  color: "#3A4F62"
  image: assets/images/splash.png
  android: true
  ios: false
  android_gravity: fill
android_12:
  color: "#3A4F62"
  image: assets/images/splash.png

The app is: https://play.google.com/store/apps/details?id=cbp.net.imoveissp&pli=1

I am available for do some tests

Tks
paulo

**Comment by jonbhanson** [comment]
@paulobreim it looks like your problem is different from the author of this problem, who only had a problem on the first start of the app.  Please open a new ticket, because I am closing this ticket due to inactivity.  Others on this ticket: feel free to open a new ticket with a full description if you are still having a problem.
