### ISSUE TITLE
How to remove flutter_native_splash???/

### ISSUE THREAD

**Issue by DigvijayZ** [jonbhanson/flutter_native_splash#487]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

**Configuration**

Paste the flutter_native_splash section of your yaml config.

**Device (please complete the following information):**

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to '...'
2. Run in an emulator configured with '...'
3. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.  If in doubt, attach a screenshot.

**Additional context**

**Comment by lramondev** [comment]
flutter pub run flutter_native_splash:remove
but get error on startup debug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:AAPT: D:\Sources\Flutter\divina\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v31\values-v31.xml:8: error: resource drawable/android12splash (aka com.example.divina:drawable/android12splash) not found.
     D:\Sources\Flutter\divina\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-v31\values-v31.xml:8: error: resource drawable/android12splash (aka com.example.divina:drawable/android12splash) not found.
     D:\Sources\Flutter\divina\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values-night-v31\values-night-v31.xml:8: error: resource drawable/android12splash (aka com.example.divina:drawable/android12splash) not found.
