### ISSUE TITLE
Two errors on the web

### ISSUE THREAD

**Issue by lJanusl** [jonbhanson/flutter_native_splash#488]
**Describe the bug**

1. Initially a solid color appears, not the established background image. 
    - Takes a few seconds before displaying the background image
3. When you change windows and come back it takes a couple of seconds before the app responds  
    - This happens since the last update (2.2.16) I had to go back to (2.2.14) and remove the html tag in splash.css to make it work normally without the background image

**Device (please complete the following information):**
 - on web (Brave, Chrome, Edge and Safari)  - Win 11 and 10

Thanks for all the work

**Comment by jonbhanson** [comment]
@lJanusl if you create the splash on 2.2.15, do you have this same problem?

@Bungeefan the html tag that @lJanusl refers to was added in your PR #459.  Can you help out with this ticket?

**Comment by lJanusl** [comment]
Hello! 

Yes indeed, now I don't have any errors, thank you very much for the reply.
