### ISSUE TITLE
Different splash screens based on some condition

### ISSUE THREAD

**Issue by vaibhav891** [jonbhanson/flutter_native_splash#490]
**Describe the solution you'd like**
I would like to show different splash screens based on some condition. For example, I have a freemium app. I would like to show a different splash screen to my free users and a different splash screen with some premium look n feel to my premium users. Does not look like I can achieve this currently using the package. I think this would be a cool feature to add.

**Comment by jonbhanson** [comment]
What platform(s) are you using?

**Comment by vaibhav891** [comment]
Android & iOS

**Comment by efforthye** [comment]
May I handle this issue? please assign to me~ I'll create PR soon!

**Comment by jonbhanson** [comment]
I will close this issue and await your PR @efforthye.
