### ISSUE TITLE
iOS Splash Screen Image too big

### ISSUE THREAD

**Issue by nicop2000** [jonbhanson/flutter_native_splash#494]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

The image on the iOS Splash Screen is way too big. It's bigger than the screen and can not be fully seen

flutter_native_splash:
  color: "#212020"
  color_dark: "#212020"
  image: assets/images/logo_neu.png
  image_dark: assets/images/logo_neu.png
  android_12:
    image: assets/images/logo_neu.png
    icon_background_color: "#212020"
    image_dark: assets/images/logo_neu.png
    icon_background_color_dark: "#212020"
  fullscreen: true

Paste the flutter_native_splash section of your yaml config.

**Device (please complete the following information):**
 - Device: iPhone 14 Pro (Simulator)
 - OS: 16.2

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to '...'
2. Run in an emulator configured with '...'
3. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.  If in doubt, attach a screenshot.

**Additional context**
I added the things in Xcode like the manual described. No special flavours

**Comment by jonbhanson** [comment]
You should resize the source image that you are supplying to this package.

**Comment by nicop2000** [comment]
I've done that now, but maybe it it possible to make a fit-content variable or size variable?
