### ISSUE TITLE
Splash screen image is cropped on Android 13

### ISSUE THREAD

**Issue by carpentierchloe** [jonbhanson/flutter_native_splash#495]
The splash screen image is cropped using device with Android 13

**Configuration**

flutter_native_splash:
  image: assets/images/image.png
  color: "#FFFFFF"
  color_dark: "#000000"
  image_dark: assets/images/image.png
  android_12:
    image: assets/images/image.png
    image_dark: assets/images/image.png
    color: "#FFFFFF"
  android_13:
    image: assets/images/image.png
    image_dark: assets/images/image.png
    color: "#FFFFFF"
  web: false
  fullscreen: true

**Device**
 - Device: One Plus 8T
 - OS: OxygenOS

**Screenshots**

![IMG-20230107-WA0004](https://user-images.githubusercontent.com/61030036/211144784-11ebb780-fae7-4bd6-8c7f-19469a95ef5d.jpg)

**Comment by jonbhanson** [comment]
There is no `android_13` section of the config, although that is not the problem with the cropping.  Is your source image for Android 12+ a square image?  Please see the readme for image size guidelines.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you still have a problem.

**Comment by Admave13** [comment]
It happened to me too, the image is cropped in a square and in a lower resolution, but only in my real device, in the emulator works fine.  The image is 1152x1152 and follows the image size guidelines.
![53630273105_6b4b97bed2_6k](https://github.com/jonbhanson/flutter_native_splash/assets/103357825/6ce12739-a268-49df-9850-aa9ad9075902)
