### ISSUE TITLE
Upgrade image dependency

### ISSUE THREAD

**Issue by IAmJulianAcosta** [jonbhanson/flutter_native_splash#497]
**Is your feature request related to a problem? Please describe.**
Can't upgrade my project `image` dependency to 4.x.x because this is locked to 3.x.x

**Describe the solution you'd like**
Upgrade image dependency

**Comment by jonbhanson** [comment]
Just pushed out an update to fix this.

**Comment by IAmJulianAcosta** [comment]
Thanks for the fast turnaround
