### ISSUE TITLE
The branding image position

### ISSUE THREAD

**Issue by ayechan-maung** [jonbhanson/flutter_native_splash#499]
How do I adjust the position of the branding image? The branding image is too close to the bottom of the screen in iOS devices and android devices under version 12. Is there any specific solution to solve this?

**Configuration**
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/toppay_member.png
  branding: assets/icons/mb_branding.png
  branding_mode: bottom
  android_12:
    color: "#FFFFFF"
#    image: assets/icons/12_logo.png
    branding: assets/icons/member_branding.png
    branding_mode: bottom

**Device (please complete the following information):**
 
![Simulator Screen Shot - iPhone 14 - 2023-01-16 at 17 02 46](https://user-images.githubusercontent.com/49619379/212658381-6ff8d44b-3a6d-488d-bbd1-3371f9ba90bb.png)

**Comment by jonbhanson** [comment]
You can add some padding at the bottom of your actual image to move it up.  That is to say, change the dimensions of your image and move your logo within the image.  Android 12 has a separate branding image, so its position should be unaffected.
