### ISSUE TITLE
Moving the splash JS and CSS to be inline within index.html improves load time for HTML Web builds

### ISSUE THREAD

**Issue by toomanydev** [jonbhanson/flutter_native_splash#500]
One of the things I like about Flutter is that the HTML web build of the template project can be reduced to about 400KB. 
This is miles ahead of other crossplatform frameworks that support desktop, mobile and web.
Web load times are very important, as users will click away very quickly if they think a site is down.

By inlining the code from splash/splash.js and splash/style.css into index.html, the time to show the coloured background (DOMContentLoaded) and splash image (load) can be reduced by 50% and 33% respectively. This is excellent for poor connections, where the latency to access these small files is much more constricting than the time the actual download takes.

<details>
<summary>Image</summary>

![Untitled](https://user-images.githubusercontent.com/69650390/212655991-2ab916ca-46a7-4deb-aaec-3454c416ec6a.jpg)

</details>

**Comment by jonbhanson** [comment]
Thanks for the tip.  I will try to implement this in a future update.  Of course, PRs are always welcomed as well. 😉
