### ISSUE TITLE
How to change color statusbar

### ISSUE THREAD

**Issue by markjornales** [jonbhanson/flutter_native_splash#501]
how to change color statusbar
 
<img width="440" alt="Screenshot 2023-01-17 123931" src="https://user-images.githubusercontent.com/70134516/212811364-9bc6a5d2-a7ef-48b6-9e1c-6fdb4d58e018.png">

**Comment by jonbhanson** [comment]
This package does not support changing the color of the status bar.  You can use the `fullscreen: true` option to extend your splash screen all the way to the top, hiding the status bar.
