### ISSUE TITLE
CANT REMOVE

### ISSUE THREAD

**Issue by greylabsofficial** [jonbhanson/flutter_native_splash#514]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     com.admin.ansque_admin.app-mergeDebugResources-25:/values-v31/values-v31.xml:8: error: resource drawable/android12splash (aka com.admin.ansque_admin:drawable/android12splash) not found.
     com.admin.ansque_admin.app-mergeDebugResources-25:/values-v31/values-v31.xml:8: error: resource drawable/android12splash (aka com.admin.ansque_admin:drawable/android12splash) not found.
     com.admin.ansque_admin.app-mergeDebugResources-25:/values-night-v31/values-night-v31.xml:8: error: resource drawable/android12splash (aka com.admin.ansque_admin:drawable/android12splash) not found.
     com.admin.ansque_admin.app-mergeDebugResources-25:/values-night-v31/values-night-v31.xml:8: error: resource drawable/android12splash (aka com.admin.ansque_admin:drawable/android12splash) not found.
     error: failed linking references.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 10s
Exception: Gradle task assembleDebug failed with exit code 1

**Configuration**

Paste the flutter_native_splash section of your yaml config.

**Device (please complete the following information):**
 - Device: [SAMSUNG GALAXY S8]

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to '...'
2. Run in an emulator configured with '...'
3. See error

**Additional context**
I cant remove the package from my pubspec.

**Comment by greylabsofficial** [comment]
I can not remove the package when i remove i get error which i write on first comment

**Comment by greylabsofficial** [comment]
remove from pubspec

**Comment by jonbhanson** [comment]
I will push out an update that fixes this.
