### ISSUE TITLE
Allow to specify the name for iOS resources

### ISSUE THREAD

**Issue by bw-flagship** [jonbhanson/flutter_native_splash#515]
**Is your feature request related to a problem? Please describe.**
The iOS files have a hardcoded name, e.g. LaunchImage.imageset. When changing the splash screen, it sometimes does not update for users, because the old one is cached.  A solution is to rename the imageset, which is not possible when using flutter_native_splash.

**Describe the solution you'd like**
An optional parameter like iOS_imageset_name which defaults to "LaunchImage".

**Describe alternatives you've considered**
None, actually

**Comment by jonbhanson** [comment]
Other users of this package: please give @bw-flagship' request above a thumbs up if you also need this feature.

**Comment by jonbhanson** [comment]
It doesn't look like this is a feature that has much demand behind it, so I will close it.

**Comment by EaseTheWorld** [comment]
I was about to request exactly same feature for same reason...
