### ISSUE TITLE
Status/Notification bar still showing during splash screen on Android 12

### ISSUE THREAD

**Issue by Nathan617** [jonbhanson/flutter_native_splash#517]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

The status bar / notification bar still shows up when the splash screen shows. I need to have my splash screen full screen. Works on iOs but I keep having the status/notification bar in black on top during splash screen on Android 12.

Android Studio : 2022.1
Xcode : 14.2
Flutter : 3.7.3
flutter_native_splash : ^2.2.17

Paste the flutter_native_splash section of your yaml config.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pinput: ^2.2.23
  flutter_secure_storage: ^8.0.0
  get_it: ^7.2.0
  get: ^4.6.5
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.9
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  flutter_native_splash: ^2.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# Run commands to generate splash screen
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/kempus_logo_transparent_white three_quarter_size.png
  color: "EA4450"
  fullscreen: true

**Device (please complete the following information):**
 - Device: [Huawei Mate 20 Pro]
 - OS: [EMUI version: 12.0.0]

**To Reproduce**
Steps to reproduce the behavior, using the example app:
I run it on my physical Huawei Mate 20 Pro phone.

**Screenshots**
![splash_status_bar_present](https://user-images.githubusercontent.com/17249157/218911974-ad7b2987-cd8e-4819-8500-d26ef9b74463.jpeg)

**Additional context**
Works on iOS as it is full screen. Not Android 12.

**Comment by jonbhanson** [comment]
I am not aware of Android 12 having support for hiding the notification bar.

**Comment by Nathan617** [comment]
> I am not aware of Android 12 having support for hiding the notification bar.

Do you mean that there is nothing we can do about this?

**Comment by jonbhanson** [comment]
> > I am not aware of Android 12 having support for hiding the notification bar.
> 
> Do you mean that there is nothing we can do about this?

Yes

**Comment by Nathan617** [comment]
I understand. Thank you

**Comment by LastMonopoly** [comment]
Same problem on my Android, many other apps can hide their notification bar during splash screen showing.

**Comment by Nathan617** [comment]
> Same problem on my Android, many other apps can hide their notification bar during splash screen showing.

Or at least change the color of the notification/status bar this would be great

**Comment by jonbhanson** [comment]
@LastMonopoly are you talking about Android 12?  Can you give me an example of an app that hides the notification bar on the native splash screen on Android 12?

@Nathan617 I don't think it is possible to change the color of the notification bar on the splash screen in Android 12.  Just now I opened a couple dozen apps and they all had the same color for the notification area as the splash screen.  It appears from your post that EMUI must handle the splash screen differently from Android.

**Comment by LastMonopoly** [comment]
My huawei phone is using HarmonyOS 3.0, which is compatible with Android 12.

This app is using fullscreen splash screen:
![Screenshot_20230219_235025_com kanlixiang android](https://user-images.githubusercontent.com/839799/219959076-d9aa6da1-dcf5-42df-b481-5d1e4cd0cf47.jpg)

This is app is using flutter_native_splash:
![Screenshot_20230219_235030_com haowangdao haowangdao](https://user-images.githubusercontent.com/839799/219959082-921b5821-fd56-4593-955b-1e8510718086.jpg)

**Comment by LastMonopoly** [comment]
Same problem also happens on my Xiaomi, which is of with Android 11.

The left one is other normal android app, the right one is my app using flutter_native_splash with fullscreen: true

| ![Screenshot_2023-02-20-00-34-13-979_com kanlixiang android](https://user-images.githubusercontent.com/839799/219962321-9286c105-a76a-472a-9f15-da731e8cb71a.jpg) | ![Screenshot_2023-02-20-00-43-06-018_com haowangdao haowangdao](https://user-images.githubusercontent.com/839799/219962324-447f7c86-1516-44cf-8dbe-c37e12d32f81.jpg) |
| - | - |

**Comment by jonbhanson** [comment]
I don't have a device with HarmonyOS or Xiaomi, so I am not able to test any changes that would improve compatibility on these operating systems.

**Comment by LastMonopoly** [comment]
@jonbhanson Xiaomi is using Android 11, have you tested on Android 11?

**Comment by jonbhanson** [comment]
@LastMonopoly this package has been tested extensively with all recent versions of Android.  Unfortunately, clones of Android like MIUI don't always work exactly the same as Android.  Since I don't have any Xiaomi devices, there is no way for me to determine what needs to be changed to make the splash screen work the same as on Android.  But like [this example](https://github.com/jonbhanson/flutter_native_splash/issues/184), if an Xiaomi user can tell me what needs to be changed and I can confirm it, I am happy to make changes to accommodate.

**Comment by Nathan617** [comment]
@jonbhanson I finally found a solution coming from this link :

https://stackoverflow.com/questions/72471785/how-to-change-status-bar-color-of-native-splash-screen-in-flutter

The solution is to go to project / android / app / src / main / res / values-night / styles.xml and to overwrite the <style name="LaunchTheme ... " section with the following code :

<style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
        <item name="android:forceDarkAllowed">false</item>
        <item name="android:windowFullscreen">false</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
        <item name="android:windowTranslucentNavigation">true</item>
        <item name="android:windowLightStatusBar">true</item>
    </style>

I now have the full screen during the splash

![Screenshot_20230220_103714_com kempus kempus_mobile_app](https://user-images.githubusercontent.com/17249157/219996861-ebdaa972-9e23-4d22-b8b3-11c53e275cf8.jpg)

**Comment by Nathan617** [comment]
@jonbhanson  I finally found a solution coming from this link :

https://stackoverflow.com/questions/72471785/how-to-change-status-bar-color-of-native-splash-screen-in-flutter

The solution is to go to project / android / app / src / main / res / values-night / styles.xml and to overwrite the <style name="LaunchTheme ... " section with the following code :

 <style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
        <item name="android:forceDarkAllowed">false</item>
        <item name="android:windowFullscreen">false</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
        <item name="android:windowTranslucentNavigation">true</item>
        <item name="android:windowLightStatusBar">true</item>
    </style>

I now have the full screen during the splash as you can see below:

![Screenshot_20230220_103714_com kempus kempus_mobile_app](https://user-images.githubusercontent.com/17249157/219997010-cb12cd80-34c0-4ced-9f15-2a7fceb8a0b7.jpg)

**Comment by LastMonopoly** [comment]
@Nathan617 Same result on my Huawei, the trick is 
`<item name="android:windowDrawsSystemBarBackgrounds">true</item>`

**Comment by LastMonopoly** [comment]
@Nathan617 
This is my setup to achieve fullscreen, for `styles.xml` under `values` and `values-night` folder,
without `<item name="android:windowTranslucentNavigation">true</item>`
```
<style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">
      <!-- Show a splash screen on the activity. Automatically removed when
           the Flutter engine draws its first frame -->
      <item name="android:windowBackground">@drawable/launch_background</item>
      <item name="android:windowDrawsSystemBarBackgrounds">true</item>
      <item name="android:statusBarColor">@android:color/transparent</item>
      <item name="android:windowLightStatusBar">false</item>
      <item name="android:forceDarkAllowed">false</item>
      <item name="android:windowFullscreen">true</item>
      <item name="android:navigationBarColor">#000000</item>
      <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
  </style>
```

**Comment by LastMonopoly** [comment]
![1551677116076_ pic](https://user-images.githubusercontent.com/839799/220802564-e2e1b0fc-eedb-41ff-b3e4-6ab3daf2b680.jpg)

**Comment by Nathan617** [comment]
@jonbhanson Maybe something to consider in a further update? :)

**Comment by jonbhanson** [comment]
@Nathan617 @LastMonopoly thanks for the detective work.  I will push out an update that adds the `<item name="android:windowDrawsSystemBarBackgrounds">true</item>`.  Unfortunately I can't test it since I don't have a Xiaomi device, but since you both confirmed the fix I will go ahead with the change to fix this for other Xiaomi users.

**Comment by LastMonopoly** [comment]
@Nathan617 Thanks a lot for your effort, I will verify it later.
