### ISSUE TITLE
Android 12 does not display the startup page for the first time. It will be displayed when it is opened later. It will not be displayed when it is installed for the first time. What is the reason? The version used is 2.2.16

### ISSUE THREAD

**Issue by yj229201093** [jonbhanson/flutter_native_splash#521]
Android 12 does not display the startup page for the first time. It will be displayed when it is opened later. It will not be displayed when it is installed for the first time. What is the reason? The version used is 2.2.16

**Comment by paulobreim** [comment]
verify it.
https://github.com/jonbhanson/flutter_native_splash/issues/506#issuecomment-1407780313

**Comment by jonbhanson** [comment]
Please advise how to reproduce.  I installed the package example on an API 31 as well as an Android 13 device with the following commands:

```
flutter build apk
flutter install
```
When I first launched the app, the splash screen appeared.

Maybe you are experiencing what is described in the readme:

> **PLEASE NOTE**: The splash screen may not appear when you launch the app from Android Studio on API 31. However, it should appear when you launch by clicking on the launch icon in Android. This seems to be resolved in API 32+.

**Comment by paulobreim** [comment]
I think the best test you can do is through vscode or android studio.
simply run the program and see the emulator.

**Comment by jonbhanson** [comment]
@paulobreim testing by running from VS code or Android Studio is not a valid test.  [link](https://stackoverflow.com/a/69831106/8371825).

**Comment by jonbhanson** [comment]
Closed due to inactivity. Feel free to reopen if you still have a problem.

**Comment by parshvas1515** [comment]
Hello 
- I'm facing same issue when using native splash and run app in dev mode with opening from android studio or taping from launcher icon all time icons shows .
- When creating relase apk at the very first time it will not show icon it will show only background color and if lunch latter on it will show the splash below is the code snippet for same 


`flutter_native_splash:
  color: "#FFFFFF"
  image: assets/image/ic_splash_icon_new.png
  color_dark: "#FFFFFF"
  image_dark: assets/image/ic_splash_icon_new.png
  android_gravity: center
  android: true
  ios: true
  image_ios: assets/image/logo.png
  image_dark_ios: assets/image/logo.png
  web: false
  # add this
  android_12:
    color_dark: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    image: assets/image/ic_splash_icon_new.png
`
