### ISSUE TITLE
Add Text as option to splash-screen

### ISSUE THREAD

**Issue by viremman** [jonbhanson/flutter_native_splash#522]
**Give Option for Adding Text**

Allow developers to either add text along side the image or just text to the splashcreen and be able to style it.

**Comment by jonbhanson** [comment]
Do you mean something different from #465? Is there a reason you can't put the text on the splash image itself?

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having a problem.
