### ISSUE TITLE
A new feature to animate splash on web or include any sort of loading indication

### ISSUE THREAD

**Issue by newaishy** [jonbhanson/flutter_native_splash#524]
The initial loading on web sometimes takes too long and it seems like the page is frozen

A simple breathing animation or an animated loading bar at the top would be very helpful

I'v considered animating the image myself and adding a loading bar but with no success

**Comment by jonbhanson** [comment]
The most likely way this feature will be implemented would be with support for an animated file format.  Please voice your support for your preferred format in #245.
