### ISSUE TITLE
not able to update pubspec.yaml with the latest release

### ISSUE THREAD

**Issue by proismailshah** [jonbhanson/flutter_native_splash#529]
`Attention:` If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**
`flutter doctor -v
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.19044.2604], locale en-US)
    • Flutter version 3.7.3 on channel stable at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (4 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn

[X] Windows Version (Exit status from running `systeminfo` was unsuccessful)

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\SHAH\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\SHAH\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.76.0)
    • VS Code at C:\Users\SHAH\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2604]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.178
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.49

[√] HTTP Host Availability
    • All required HTTP hosts are available`

**Configuration**

Paste the flutter_native_splash section of your yaml config.

**Device (please complete the following information):**

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to '...'
2. Run in an emulator configured with '...'
3. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.  If in doubt, attach a screenshot.

**Additional context**

**Comment by jonbhanson** [comment]
Lacking information.
