### ISSUE TITLE
IOS:The screen stays on the startup page

### ISSUE THREAD

**Issue by FangPro** [jonbhanson/flutter_native_splash#532]
IOS: After the tester is turned on, the screen remains on the startup page and cannot jump; Do I need to configure anything on the ios side?

**Comment by ezgezl752000** [comment]
same to me. The screen remains remains on Splash Screen.

**Comment by wnsgh78b** [comment]
same to me. ㅠ.ㅠ

**Comment by aintend-com** [comment]
Same Here

**Comment by dwzrlp** [comment]
same to me

**Comment by jonbhanson** [comment]
I am not able to reproduce this problem.  Please supply a minimal code sample that demonstrates this problem.

**Comment by dwzrlp** [comment]
> I am not able to reproduce this problem. Please supply a minimal code sample that demonstrates this problem.

no problem in debug mode, just in release mode.

**Comment by jonbhanson** [comment]
> > I am not able to reproduce this problem. Please supply a minimal code sample that demonstrates this problem.
> 
> no problem in debug mode, just in release mode.

I tried running the package's example app in release mode, but no problem.  Please supply a minimal code sample that demonstrates this problem.

**Comment by FangPro** [comment]
--flutter_native_splash.yaml--
`flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#e1f5fe"
  # background_image: assets/logo_lockup_flutter_vertical.png

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
#  image: assets/logo_lockup_flutter_vertical.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. Currently, it is only supported for Android < v12 and iOS.
#  branding: assets/dart.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
#  image_dark: assets/logo_lockup_flutter_vertical_wht.png
#  branding_dark: assets/dart_dark.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
  # The image parameter sets the splash screen icon image.  If this parameter is not specified,
  # the app's launcher icon will be used instead.
  # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
  # 640 pixels in diameter.
  # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
  # 768 pixels in diameter.
  #image: assets/android12splash.png

  # App icon background color.
  #icon_background_color: "#eeeeee"

  # The image_dark parameter and icon_background_color_dark set the image and icon background
  # color when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above.
  #image_dark: assets/android12splash-invert.png
  #icon_background_color_dark: "#111111"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'`

--main.dart--
`void main() {
  // WidgetsFlutterBinding.ensureInitialized();
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  Wakelock.enable();
  StorageManage.init((){
    FlutterFileView.init();
    CacheUtil.instance.init();
  });
  runApp(const MyApp());
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    systemNavigationBarColor: Colors.white,
  ));
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);
}`
![Simulator Screen Shot - iPhone 13 - 2023-04-03 at 21 56 11](https://user-images.githubusercontent.com/45156835/229532279-b088dff0-dc43-4d9c-be65-af1bc3cc501a.png)

After the program starts, it stays in this screen all the time. As shown in the screenshot above, how can I solve it

**Comment by jonbhanson** [comment]
The problem is that you never make a call to `.remove()`:

```dart
// whenever your initialization is completed, remove the splash screen:
    FlutterNativeSplash.remove();
```

**Comment by FangPro** [comment]
The problem has been resolved, and your suggestion is useful. Thank you very much for your help

**Comment by dwzrlp** [comment]
> > > I am not able to reproduce this problem. Please supply a minimal code sample that demonstrates this problem.
> > 
> > 
> > no problem in debug mode, just in release mode.
> 
> I tried running the package's example app in release mode, but no problem. Please supply a minimal code sample that demonstrates this problem.

For me, it's an issue with Firebase configuration. Sorry for bothering you.

**Comment by dwzrlp** [comment]
> @dwzrlp can you please elaborate more your problem ... maybe we have the same issue, thansk

This only applies to my situation: when I was in release mode on the iOS device, the app got stuck on the splash screen. However, after removing the FirebaseMessaging.instance.getToken() function, everything returned to normal.

**Comment by mrzanirato** [comment]
mmm ... interesting ... I'll give it a try! Thanks

**Comment by mrzanirato** [comment]
Solved moving the getToken() function inside the initState()() method. Hope it helps someone. @dwzrlp

**Comment by aprashantz** [comment]
> > > > I am not able to reproduce this problem. Please supply a minimal code sample that demonstrates this problem.
> > > 
> > > 
> > > no problem in debug mode, just in release mode.
> > 
> > 
> > I tried running the package's example app in release mode, but no problem. Please supply a minimal code sample that demonstrates this problem.
> 
> For me, it's an issue with Firebase configuration. Sorry for bothering you.

How did you fix your Firebase configuration issue that caused issue in release mode

**Comment by SametSahin10** [comment]
How could this be related to getting the Firebase Messaging Token?

**Comment by aprashantz** [comment]
> How could this be related to getting the Firebase Messaging Token?

Binding needs to be initialized before calling runApp, if there is issue in initializing bindings, app can stuck in splash. 
If Firebase Messaging Token is not implemented properly, Previously, i have faced the app stuck at splash. Solved it by making changes in the Firebase Messaging related part.

**Comment by korkmazMert** [comment]
In my case its only happening in ios. It opens app with no problem at first but when i take app to background and open it again it gets stuck at splash screen. Im also using fcm can you tell what changes did you do about fcm @aprashantz
