### ISSUE TITLE
[ How to "undo" ? ]

### ISSUE THREAD

**Issue by Gobmichet** [jonbhanson/flutter_native_splash#539]
Hi,
Thanks for the job,
It seems that, somehow, the lib is interferring with our app's display on certain phones (Huawei and Xiaomi).
How to just undo what we did with the cmd line launching the lib ?

is there a "rollback" cmd ?

Thanks in advance,
Regards.

**Comment by jonbhanson** [comment]
No, there is not a rollback command.  Probably the best way is to rollback with your version control system.

**Comment by Gobmichet** [comment]
Well that's clearly not possible.
We added your feature at the start of the project months aqo :(

>>  How can you manually rollback then ?

I'll explain the problem maybe you could help cause we'd rather continue to use your splashScreen ^^

**Indeed, the problem is that on Xiaomi's phones, everything at first launch is ok but when background/foreground the app or kill the app and come back, the bottomNavigationBar won't display normally !**

What's wierd is that we thought we had corrected the problem with the android 12 specific configuration and relaunching the cmd...
 
But the problem seems to be **BACK**...
Saw elsewhere  an issue that looks alike by two other persons and you added some conf for that purpose...
But either it is back, either there's something more in the same vein...

Can you please help in a way or another ?
Thanks in advance ^^

**Comment by jonbhanson** [comment]
@Nathan617 and @LastMonopoly in [that thread](https://github.com/jonbhanson/flutter_native_splash/issues/517) had a number of additional configuration parameters in their `styles.xml`.  Could you try those parameters and see if they resolve the issue?  Unfortunatly I do not have an Xiaomi device so I have no way to test it.

**Comment by Gobmichet** [comment]
OK thanks for your answers,

I relaunched the CMD and it reworked,
The only things that changed are on :
/values/styles.xml
/values-31/styles.xml
/values-night-31/styles.xml

> CRLF > LF

**Comment by Gobmichet** [comment]
OK that's really wierd guys...

When comming directly from my IDE that works fine...
I build the .apk and then the problem shows...

Any idea ? :s

**Comment by Gobmichet** [comment]
ALL MY APOLOGIES !
I'm really confused, i found here :
https://stackoverflow.com/questions/69851578/why-does-my-flutter-page-sometimes-not-render-completely-in-release-version/71614185#71614185

a workaround for my problem...
it seems that for obscur reasons and only in release .apk, Flutter encounters some graphical issues even if you use such code :
> WidgetsFlutterBinding.ensureInitialized();

juste adding
> await Future.delayed(const Duration(milliseconds: 300));
"solved" the problem
I don't like it cause it's "bricolage" in french but i will create a tcket/issue directly to Flutter Teams about this really wierd issue...

Again all my apologies...
And again, thanks for your work ^^

Regards,
