### ISSUE TITLE
flutter_native_splash doesn't work in Android Studio but works in Visual Studio Code

### ISSUE THREAD

**Issue by UserY1** [jonbhanson/flutter_native_splash#540]
Exception: Your `pubspec.yaml` file does not contain a `flutter_native_splash` section.
...
pub finished with exit code 255.
-----

I am getting this error after the command 'flutter pub run flutter_native_splash:create'.
But I noticed that even during installation, after the command 'flutter pub add flutter_native_splash', the line 'flutter_native_splash: ^2.2.19' does not appear in pubspec.yaml in the 'dependencies:' section and there is no entry about flutter_native_splash in pubspec.lock.
Tested on:
Android Studio Electric Eel | 2022.1.1
and
Android Studio Electric Eel | 2022.1.1 Patch 2

I tried to specify the 'color' and 'image' both in pubspec.yaml and in a separate file. 
Accounted for all gaps.
'ios/Runner/Info.plist' has not been modified.
'flutter clean' and 'flutter pub get' doesn't help.
Opening and closing Android Studio does not help.
Restarting the computer doesn't help.
In 'launch_background.xml', of course, there are no entries about "@drawable/background" and "@drawable/splash".
flutter_launcher_icons is not set.

The 'pubspec.lock' entry only appears when you specify 'flutter_native_splash: ^2.2.19' in both 'dependencies:' and 'dev_dependencies:' at the same time. But 'flutter pub run flutter_native_splash:create' still doesn't work.

On an empty project with a counter in Android Studio, flutter_native_splash works. But not in my project.

Visual Studio Code adds flutter_native_splash to my project nicely. An entry is added to 'dependencies:'. 'flutter pub run flutter_native_splash:create' works. Everything is working. If you then open the project again after VS code in Android Studio, then the entry in 'dependencies:' will be saved, in 'pubspec.lock' too, but 'flutter pub run flutter_native_splash:create' will still not work.

Most likely this bug should be addressed to Android Studio developers.

**Comment by jonbhanson** [comment]
> But I noticed that even during installation, after the command 'flutter pub add flutter_native_splash', the line 'flutter_native_splash: ^2.2.19' does not appear in pubspec.yaml in the 'dependencies:' section and there is no entry about flutter_native_splash in pubspec.lock.
Whatever the problem is, it is not with this package.  I would suggest carefully check the spelling in your commands/configs.

**Comment by UserY1** [comment]
You are right, the problem was not only with the flutter_native_splash package. I reinstalled Android Studio with all settings removed, that didn't help either. 
This is what helped me, I created a new project and copied all the files from the previous project into it and then it worked.
