### ISSUE TITLE
Add `android:tileMode` config property for background images for Android

### ISSUE THREAD

**Issue by plencka** [jonbhanson/flutter_native_splash#541]
**Is your feature request related to a problem? Please describe.**
I am experimenting with a background image for my splash screen and I believe that using repeating, seamless images would work best for me. However, the default configuration is squishing the image horizontally instead of repeating it.

I am able to modify the `launch_background.xml` file to include the property that fixes the above issue:
```shell
<item>
      <bitmap android:gravity="fill" android:tileMode="repeat" android:src="@drawable/background"/>
</item>
 ```
The problem is that the plugin keeps replacing my changes when I want to update the image asset and it's becoming repetitive to fix it.

**Describe the solution you'd like**
I would like a new configuration property for pubspec.yml like this:
```shell
android_background_tilemode: "repeat"
```
It should set attribute in `launch_background.xml` to `android:tileMode="repeat"` for item with `@drawable/background` src. 
I think the logic for similar thing is in [lib/android.dart](https://github.com/jonbhanson/flutter_native_splash/blob/9fbc8c976cd6424193e8a2ac7109e8debf1c00c5/lib/android.dart#L334), which is for `android_gravity` for branding image.

**Describe alternatives you've considered**
I have considered merging the splash image and background together, but exporting the results is taking a bit of time, which could be saved with the above solution.
Maybe there is a commonly accepted approach, but I had a hard time finding any information on this, and I am not aware of any disadvantages of repeating images.

Alternatively an ability to lock .xml from changes or an ability to only regenerate images.

**Additional context**
Here's a visual representation of the issue:
"Squished," distorted version:
![image](https://user-images.githubusercontent.com/49527545/232154427-03068d4f-4060-4f0e-8a2f-8200ca80e75f.png)

With repeat `tileMode`, this matches original .png:
![image](https://user-images.githubusercontent.com/49527545/232154382-494cecde-f4bf-46b9-b2d5-b3101e64dd25.png)

The `android:tileMode` is [documented here](https://developer.android.com/guide/topics/resources/drawable-resource) and has four modes: disabled, clamp, repeat, mirror.

**Comment by jonbhanson** [comment]
Sorry, this use case is too specific for this package.

**Comment by peter100u** [comment]
我觉得这个属性，很有必要 android_background_tilemode: "repeat"
