### ISSUE TITLE
Splash image not visible on android

### ISSUE THREAD

**Issue by vm-cheolubak** [jonbhanson/flutter_native_splash#546]
**Describe the bug**

In the Android 12 version LG V50 ThinQ, the background color works normally, but the image is not visible.

**Configuration**

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png

  android_12:
    image: assets/splash.png
    icon_background_color: "#ffffff"

  web: false

**Device (please complete the following information):**
 - Device: LG V50 ThinQ
 - OS: Android 12

**Comment by vm-cheolubak** [comment]
Found a solution to the issue.
In Android 12, it is correct that the code below does not exist, but in the corresponding model, it was confirmed that the splash image is not exposed if the code below is not present.(In AndroidManifest.xml)

```
<meta-data
	android:name="io.flutter.embedding.android.SplashScreenDrawable"
	android:resource="@drawable/launch_background"
/>
```

Please check it.

**Comment by AlthafAslam** [comment]
I'm having a similar issue.
When I install the app on the device for the first time, Only the background colour is loading. The image is missing. 

After the first installation, every time when I kill the app and reopen it, the splash works as expected.  Any resolutions?

**Comment by jtavio** [comment]
I'm having a similar issue.

**Comment by jtavio** [comment]
@vm-cheolubak Does the solution you gave still work with flutter 3.3?

**Comment by jonbhanson** [comment]
> In Android 12, it is correct that the code below does not exist, but in the corresponding model, it was confirmed that the splash image is not exposed if the code below is not present.(In AndroidManifest.xml)

@vm-cheolubak I am not sure I understand what you mean when you mention "the corresponding model".  Are you referring to the LG V50 ThinQ device that you are using?

Are you sure that it is running Android 12?  [This link](https://www.gsmarena.com/lg_v50_thinq_5g-9607.php) states that the device is "upgradable to Android 11".

@sentd94 Are you launching from Android Studio?  As noted in the Android 12 section of the readme,
> **_PLEASE NOTE:_** The splash screen may not appear when you launch the app from Android Studio on API 31. However, it should appear when you launch by clicking on the launch icon in Android. This seems to be resolved in API 32+.

**Comment by sentd94** [comment]
@jonbhanson No, from vscode

**Comment by jonbhanson** [comment]
> @jonbhanson No, from vscode

OK, that is the cause of the missing image.  With API 31, if you launch the app from a remote command (like starting it from Android Studio or VS code) it does not display the splash image.  However, if you launch by selecting the app from the launcher on the device, the splash image should be displayed.

**Comment by bertrandgelinas** [comment]
> > @jonbhanson No, from vscode
> 
> OK, that is the cause of the missing image. With API 31, if you launch the app from a remote command (like starting it from Android Studio or VS code) it does not display the splash image. However, if you launch by selecting the app from the launcher on the device, the splash image should be displayed.

Hey :)

What you say is right. However, i don't think that's the actual issue. I can definitly say that the icon you see when you launch the app (which is not showing when triggering run from vscode) is the actual launcher icon. @vm-cheolubak did you made sure you added something in android12 config?

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.
