### ISSUE TITLE
Add package link to repo

### ISSUE THREAD

**Issue by OutdatedGuy** [jonbhanson/flutter_native_splash#549]
Please add this package's link from the `pub.dev` website to this repo's _About_ section.

**Comment by OutdatedGuy** [comment]
@jonbhanson,

Add the packages pub link (i.e. https://pub.dev/packages/flutter_native_splash) in the website url field of the About section. See below image.

| About Section | Settings of About Section |
|--------|--------|
| <img width="377" alt="Screenshot 2023-05-15 at 10 15 42 PM" src="https://github.com/jonbhanson/flutter_native_splash/assets/74326345/bea7ee0e-8fa3-4cb0-9d86-9be201525d17"> | <img width="641" alt="Screenshot 2023-05-15 at 10 17 57 PM" src="https://github.com/jonbhanson/flutter_native_splash/assets/74326345/1c6aaa85-eae6-48b0-937c-89c9d1ce3a57"> |

**Comment by jonbhanson** [comment]
Ah, I understand, thanks.  Repo updated. 👍
