### ISSUE TITLE
I want to remove `flutter_native_splash` from my project.

### ISSUE THREAD

**Issue by meet7-sagar23** [jonbhanson/flutter_native_splash#553]
I have already removed `flutter_native_splash` from `pubspec.yaml`. Also, the image is also deleted from the `assets` folder.

# Still I am seeing the native splash.

# How do I revert back to the flutter splash screen?

**Comment by pushkar-appdid** [comment]
> ```yaml
>   # To restore Flutter's default white splash screen, run the following command in the terminal:
>   # flutter pub run flutter_native_splash:remove
> ```

Getting this error while executing above command.

Restoring Flutter's default native splash screen...
Unhandled exception:
LateInitializationError: Field '_flavorHelper@20018413' has not been initialized.
#0      _flavorHelper (package:flutter_native_splash/cli_commands.dart)
#1      getConfig (package:flutter_native_splash/cli_commands.dart:246:14)
#2      removeSplash (package:flutter_native_splash/cli_commands.dart:184:18)
#3      main.<anonymous closure> (file:///C:/Users/Appdid/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_native_splash-2.2.0+1/bin/remove.dart:6:49)
#4      Parser.parse.<anonymous closure> (package:args/src/parser.dart:107:15)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#6      MapView.forEach (dart:collection/maps.dart:342:10)
#7      Parser.parse (package:args/src/parser.dart:95:22)
#8      ArgParser.parse (package:args/src/arg_parser.dart:334:42)
#9      main (file:///C:/Users/Appdid/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_native_splash-2.2.0+1/bin/remove.dart:7:10)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
pub finished with exit code 255

**Comment by clragon** [comment]
thats unnecessarily rude.

I dont know about fixing the inbuilt removal, but the easiest way of removing the splash screen is by
(make sure your VCS is engaged):

1. deleteyour android folder
2. run `flutter create your_project` again
3. restore any config files you have altered

by recreating your android folder with the `flutter create` command, you are resetting to the default.
You then just have to restore any files you have adjusted yourself, if any.

**Comment by jonbhanson** [comment]
I had reopened this ticket to investigate the problem.  However, seeing @meet7-sagar23 edit his comment with insults, I will not be helping.  @pushkar-appdid if you are still having a problem, please open an new ticket and include your configuration.

**Comment by nived-s** [comment]
![image](https://github.com/jonbhanson/flutter_native_splash/assets/67747565/071ed2be-1a0f-4567-8fe7-58185f116337)
 **just make sure all the code related to flutter_native_splash still remains in projected not in commented form**

**Comment by jantheok** [comment]
For me, I had to delete also the build / ios / android (and othe platform) folders and remove the flutter_native_splash reference in pubspec.yaml.
My steps were:
1) in Terminal run "flutter pub run flutter_native_splash:remove"
2) run "flutter pub remove flutter_native_splash"
3) delete flutter_native_splash reference in pubspec.yaml
4) delete folders: build / ios / android (and other platform specific folders)
5) run "flutter clean"
6) run "flutter pub get"
7) reenable my platforms (by writting e.g. "Enable android for this project" in the command center

**Comment by dvdnhm** [comment]
@jonbhanson I would be pissed off over such a d..k comment too but this issue is real and this thread comes up in google search.

if there is an update, please update this thread too

**Comment by jonbhanson** [comment]
@dvdnhm please open a new ticket with your config details and instructions on how to reproduce this problem and I will take a look at your ticket.

**Comment by SaanPrasanna** [comment]
> I have already removed `flutter_native_splash` from `pubspec.yaml`. Also, the image is also deleted from the `assets` folder.
> 
>  Still I am seeing the native splash.
>  How do I revert back to the flutter splash screen?

I think this is simplest way to remove  `flutter_native_splash` from your project.

Note: 
1. If you remove the  `flutter_native_splash` package from your `pubspec.yaml` file, need to add again (`flutter pub add flutter_native_splash`).
2. Then if not exist add this two lines to pubspec.yaml file
```
flutter_native_splash:
  android_12:
```
Then run this commands
3. `flutter pub run flutter_native_splash:remove`
4. `flutter clean`
5. `flutter pub get`

**Comment by zainulabdn** [comment]
how can i remove by default native splash screen which is show on android version 12 above?

**Comment by jonbhanson** [comment]
> how can i remove by default native splash screen which is show on android version 12 above?

@zainulabdn you cannot remote the splash screen from Android 12+.  "The splash screen experience brings standard design elements to every app launch, but it's also customizable so your app can maintain its unique branding."  [Splash screens](https://developer.android.com/develop/ui/views/launch/splash-screen).

**Comment by cisplRejjak** [comment]
> ```yaml
> flutter pub run flutter_native_splash:remove
> ```

use this ```dart run flutter_native_splash:remove```

**Comment by adnankovacevic** [comment]
Hi everyone,
I’m experiencing this issue when trying to remove the splash screen using:

`dart run flutter_native_splash:remove`

I've tried all the suggested workarounds but nothing seems to work.

Has anyone found a solution or workaround for this yet?

**Comment by hitchcliff** [comment]
I was able to remove the splash screen but it changes back to `flutter` default splash screen. 

What I did was to delete the following folders (to set back to default):
- `android`
- `linux`
- `macos`
- `windows`
- `ios`

Although I was able to remove it but I had to reconfigure my settings to run the app again because this code doesn't work `dart run flutter_native_splash:remove` 

This method works [https://stackoverflow.com/a/77878850/14071271](https://stackoverflow.com/a/77878850/14071271) btw, I'm not sure if it work in other os

**Comment by Afnanappu** [comment]
If it's not working try to use some other version like 2.3.13 because it's worked for me. Also first flutter clean and pub get after try flutter_native_splash:remove

**Comment by Emperor-One** [comment]
This issue shouldn't be closed and should be investigated properly. 
`flutter pub run flutter_native_splash:remove` does not even run for me.
I just get:
```
Deprecated. Use `dart run` instead.
-h, --[no-]help    Show help
-p, --path         Path to the flutter project, if the project is not in it's default location.
-f, --flavor       Flavor to remove the splash for.
```

And `dart run flutter_native_splash:remove` gives:

```
Because no versions of flutter_native_splash match >2.4.7 <3.0.0 and flutter_native_splash 2.4.7 requires the Flutter SDK,
  flutter_native_splash ^2.4.7 is forbidden.
So, because draxx_labs depends on flutter_native_splash ^2.4.7, version solving failed.

Flutter users should use `flutter pub` instead of `dart pub`.
```

This [stackoverflow answer](https://stackoverflow.com/a/77878850/14071271) from this [comment above](https://github.com/jonbhanson/flutter_native_splash/issues/553#issuecomment-2664656397) is what worked for me.
