### ISSUE TITLE
How to update the previous native splash screen generated by the package?

### ISSUE THREAD

**Issue by GnuaAruht** [jonbhanson/flutter_native_splash#557]
I want to update the previous native splash screen generated by the package. I updated `flutter_native_splash.yml` and run this command  `flutter pub run flutter_native_splash:create` again. The package generated new one. It doesn't override the previous one.

**Comment by FaisaljanBaloch** [comment]
Can we add a new command of `flutter pub run flutter_native_splash:update` which would replace these splash screens with new ones?

**Comment by jonbhanson** [comment]
> I want to update the previous native splash screen generated by the package. I updated `flutter_native_splash.yml` and run this command `flutter pub run flutter_native_splash:create` again. 

This should work to update the splash screen.

> The package generated new one. It doesn't override the previous one.

I don't understand, you first sentence seems to say that the package created an updated splash screen, and your second sentence seems to say that the package did not create an update splash screen

Can you provide more information?

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.
