### ISSUE TITLE
used flutter_native_splash, default splash screen comes.

### ISSUE THREAD

**Issue by krishna-kpa** [jonbhanson/flutter_native_splash#561]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**
used the flutter_native_screen 
but the default flutter splash screen comes

**Configuration**

Paste the flutter_native_splash section of your yaml config.

**Device (please complete the following information):**
 - Device: Pixel 6 Pro API 33
 - OS: Android 13

**Screenshots**
![image](https://github.com/jonbhanson/flutter_native_splash/assets/118350087/76e349f5-fee3-466a-b00a-038db768470d)

**Comment by jonbhanson** [comment]
Android 12+ changed the way the splash works and requires its own configuration section, which is missing in your config.

**Comment by dai10512** [comment]
Same case!

**Comment by haqqi** [comment]
You need to define the specific configuration for Android 12.

Try to add more lines under the config yaml like this (more is in the documentation).

```
  android_12:
    image: assets/splash/logo-production.png
    color: "#183033"
    branding: assets/splash/brand.png
```

For the image size, you need to refer on the official documentation https://developer.android.com/develop/ui/views/launch/splash-screen

**Comment by iAbdulaziz93** [comment]
Same case here, even when using `android_12`.

**Comment by aliyukabir1** [comment]
same issue. solved it by uninstalling the debug apk and running it again.

**Comment by singh3abhi** [comment]
Any updates? I am facing a similar issue in Android 13.

**Comment by jonbhanson** [comment]
@krishna-kpa in your photo it looks like you have too many spaces indented in the `color` parameter and following parameters in your `flutter_native_splash` section.  You need two spaces indent in each subsection in a `yaml` file, and it looks like you have four spaces instead of two.

**Comment by jonbhanson** [comment]
Closed due to inactivity. Feel free to reopen if you are still having trouble.
