### ISSUE TITLE
splash doesn't resize. (flutter web accessed by mobile)

### ISSUE THREAD

**Issue by ranulfo** [jonbhanson/flutter_native_splash#562]
when i build it for flutter web, in the browser on the PC it works perfectly, but when i use the browser on the mobile, the image appears with the same proportion as on the PC, causing the logo to be cut off at the edges.
Can anyone help me with this ?

**Comment by jonbhanson** [comment]
Can you add images showing what you are describing?

**Comment by ranulfo** [comment]
I solved this issue by add a image with `1300x440` and set property` web_image_mode : true` and `web: true`
thank's
