### ISSUE TITLE
On android 12 and 12+, when using "FlutterNativeSplash.preserve" does not show splash icon when open app from deep link

### ISSUE THREAD

**Issue by Abdulah-butt** [jonbhanson/flutter_native_splash#565]
On android 12 and 12+, when using "FlutterNativeSplash.preserve" does not show splash icon when open app from deep link.

**Comment by jonbhanson** [comment]
From this package's readme:
> PLEASE NOTE: The splash screen does not appear when you launch the app from a notification. Apparently this is the intended behavior on Android 12: [core-splashscreen Icon not shown when cold launched from notification](https://issuetracker.google.com/issues/199776339?pli=1).

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.
