### ISSUE TITLE
[v2.3.1] Default splash screen displayed for android < 12

### ISSUE THREAD

**Issue by clementinedeb** [jonbhanson/flutter_native_splash#567]
Hello,

I ran into some issue with using the library with Android version lower than 12.
On IOS and Android 12+, everything works fine, the customized splash screen is displayed.
On Android 10, 9 or older, the default splash screen is displayed: an empty black or white screen.

Maybe I missed some configuration ? 

Thank you for your help.
Clémentine.

PS: Other than this problem, this library is great and really easy to set up 👍 

**Configuration**

```
dependencies:
  flutter_native_splash: ^2.3.1

flutter_native_splash:
  fullscreen: true
  color: "#10B981"
  image: "assets/graphic/splashscreen_logo.png"
  color_dark: "#10B981"
  image_dark: "assets/graphic/splashscreen_logo.png"
  android_12:
    image: "assets/graphic/splashscreen_logo_android12.png"
    image_dark: "assets/graphic/splashscreen_logo_android12.png"
```

**Device :**
 - Device: Xiaomi 8 (real device), Nexus 5X (emulator)
 - OS: Android 9 (SDK 28), Android 10 (SDK 29)
 - tried with dark or light theme

**To Reproduce**
- Add configuration on pubspec.yml
- `dart run flutter_native_splash:create`
- assert that the files in android/app/src/main/res/ are created
- `flutter clean && flutter pub get`
- launch the app on android emulator or device with android < 12
- see the default white or black splash screen instead of the customized one.

**Additionnal informations**

In the android/app/src/main/res/values-v31/style.xml more configuration were added by the command `dart run flutter_native_splash:create` than in android/app/src/main/res/values/style.xml.

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting when the OS's Dark Mode setting is off -->
    <style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">
        <item name="android:forceDarkAllowed">false</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
        <item name="android:windowSplashScreenBackground">#10B981</item>
        <item name="android:windowSplashScreenAnimatedIcon">@drawable/android12splash</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="Theme.MaterialComponents.Light">
        <!-- As required for Stripe lib (flutter_stripe in pubspec.yaml), parent theme needs to be Theme.AppCompat or Theme.MaterialComponents -->
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
```
_android/app/src/main/res/values-v31/style.xml_

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting when the OS's Dark Mode setting is off -->
    <style name="LaunchTheme" parent="@android:style/Theme.Light.NoTitleBar">
        <item name="android:forceDarkAllowed">false</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="Theme.MaterialComponents.Light">
        <!-- As required for Stripe lib (flutter_stripe in pubspec.yaml), parent theme needs to be Theme.AppCompat or Theme.MaterialComponents -->
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
```
_android/app/src/main/res/values/style.xml_

So I tried to add in the android/app/src/main/res/values/style.xml file the same style than in android/app/src/main/res/values-v31/style.xml, but it didn't work. No even with just a color background.

And one last info, before upgrading the library (from ^1.3.2 to 2.3.1) we were using a background-image only for the splashscreen and it worked on every devices no matter the android version.

Here is my flutter doctor, I'm using VScode:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E261 darwin-arm64, locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.1)
[✓] Connected device (4 available)
[✓] Network resources
```

**Comment by clementinedeb** [comment]
Hello,
I fixed the issue.

Look like it was due to this missing line :
`<item name="android:windowBackground">@drawable/launch_background</item>`
In `android/app/src/main/res/values/styles.xml`. (the style file for android < 12)

I copied this line from `android/app/src/main/res/values-v31/styles.xml` (the style file for android > 12), put the corresponding asset instead of the one for android > 12 and it worked.

But if I re-run the command `dart run flutter_native_splash:create` , this line is erased from `android/app/src/main/res/values/styles.xml`, so maybe someone could look into this ?

**Comment by jonbhanson** [comment]
That line is included anytime a new Flutter project is created, so I think it is reasonable for this package to assume that it will be there.  It sounds like in your case it was mistakenly removed at some point.
