### ISSUE TITLE
Logo is being cut 

### ISSUE THREAD

**Issue by delfme** [jonbhanson/flutter_native_splash#569]
**Describe the bug**
The logo is being cut. To help debug issue, I share below a working repo.

**Configuration**
This is my yaml config.

flutter_native_splash:
  color: "#2c5fec"
  image: assets/logo_splash_screen_transparent.png
  android_12:
    color: "#2c5fec"
    image: assets/logo_splash_screen_transparent.png

Note: if I don't add the android_12 section, logo is shown correctly but a grey screen is shown before. You can try it yourself.

**Device (please complete the following information):**
 - Device: [e.g. Xiaomi Mi lite 11]
 - OS: [android 12 SKQ1.211006.001]

**To Reproduce**
Run this example https://github.com/delfme/flutter-native-splash-master-2/tree/main/example

**Screenshots**
Please see video below:

https://github.com/jonbhanson/flutter_native_splash/assets/53510751/63de41bd-1d94-4e75-8199-a23df19d4a5d

This is grey background if android_12 is removed by config:
flutter_native_splash:
color: "#2c5fec"
image: assets/logo_splash_screen_transparent.png

https://github.com/jonbhanson/flutter_native_splash/assets/53510751/ec3b822d-26fa-4ac1-bb6d-040ac1719460

**Comment by ManInTheWind** [comment]
I think there might be a need for a splash icon with different screen densities for android 12. Because I've had this problem all the time

**Comment by delfme** [comment]
Hi @ManInTheWind density was 300, then I set it to 184, which is same number used by official demo icon. But nothing.

Also, it looks like the app loads two different images, the one for android12 for the first 1-2 secs and the main one later on.

I did this experiment.
I created an empty “transparent” png and assigned it to android_12 image like this
```
flutter_native_splash:
  color: "#2c5fec"
  image: "assets/logo/logo.png”
  android_12:
    image: "assets/logo/transparent.png"
```

The result is having only the blue background color for first 1-2 sec and then the logo.png. So maybe android_12 icon is used only for the initial moment or maybe there is conflict between different style files?

**Comment by delfme** [comment]
Just noticed that even demo logo gets cut

![D1A48EC9-16B9-4573-AA7A-14FA39E6E12E](https://github.com/jonbhanson/flutter_native_splash/assets/53510751/72f5b9ed-95d8-4bb0-9f6c-5c42b228da39)

**Comment by delfme** [comment]
This is how I fixed:
1) use more padding between icon and icon-image background
2) rename this very file as `android12splash.png` and use it to overwrite the ones generated by plugin. I mean paste your file inside all res subfolder where plugin generated android12splash.png

**Comment by erperejildo** [comment]
> This is how I fixed:
> 
> 1. use more padding between icon and icon-image background
> 2. rename this very file as `android12splash.png` and use it to overwrite the ones generated by plugin. I mean paste your file inside all res subfolder where plugin generated android12splash.png

how much is "more padding"? I don't want any extra gap
