### ISSUE TITLE
Splash Not working on Android tv

### ISSUE THREAD

**Issue by usman615** [jonbhanson/flutter_native_splash#573]
Flutter Native splash is not showing on Android smart tv

**Comment by jonbhanson** [comment]
Are you launching the app from the icon in the Android TV, or are you launching it from a button in Android studio?

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you still have a problem.

**Comment by usman615** [comment]
> Are you launching the app from the icon in the Android TV, or are you launching it from a button in Android studio?

With Icon
