### ISSUE TITLE
Splash screen not showing and app is stuck

### ISSUE THREAD

**Issue by erperejildo** [jonbhanson/flutter_native_splash#575]
Sorry if this is not a bug related to this package. I've been trying to find a solution but couldn't find anything.

**Describe the bug**
I had to create a new version of my app after a while so first thing I did was update flutter and the packages. I updated this one from 2.2.4 to 2.3.1.
When trying to debug my app I saw an error from Flutter saying that something related to the splash screen was deprecated and I had to check this: https://docs.flutter.dev/release/breaking-changes/splash-screen-migration. Only thing missing was removing that from `AndroidManifest.xml`.

After this I got no errors but the app doesn't work, the stop button changes again to play and it get stuck with the splash screen and splash screen is not longer displayed. I removed it with:
`flutter pub run flutter_native_splash:remove`

and generated it again with:
`flutter pub run flutter_native_splash:create`
but I do not see anything, just a background color.

Apart from this I didn't change anything from last deployment, when it was fine. Anything else that could affect this?

**Configuration**
```
flutter_native_splash:
  image: assets/images/splashscreen.png
  color: "281b60"
  fill_horizontal: true
```

My image:

![splashscreen](https://github.com/jonbhanson/flutter_native_splash/assets/5629919/be17d2c9-1b29-44a3-a7ef-9450e4c459ca)

**Device (please complete the following information):**
Android emulator

**Comment by jonbhanson** [comment]
I am not sure what the cause of your problem is.  Can you send a minimal version of your project that replicates this issue?

**Comment by erperejildo** [comment]
> I am not sure what the cause of your problem is. Can you send a minimal version of your project that replicates this issue?

this fixed it: https://github.com/jonbhanson/flutter_native_splash/issues/576#issuecomment-1674390043
