### ISSUE TITLE
Android 12 splaash screen problem

### ISSUE THREAD

**Issue by batuhansavas-yilmaz** [jonbhanson/flutter_native_splash#576]
flutter_native_splash:
  color: "#000000"
  image: assests/splash_screen/splash_screen.png
  branding: assests/splash_screen/branding.png
  color_dark: "#000000"
  image_dark: assests/splash_screen/splash_screen.png
  branding_dark: assests/splash_screen/branding.png
  android_12:
    image: assests/splash_screen/splash_screen.png
    branding: assests/splash_screen/branding.png
    icon_background_color: "#000000"
    image_dark: assests/splash_screen/splash_screen.png
    icon_background_color_dark: "#000000"
    branding_dark: assests/splash_screen/branding.png
 
 
When you do it this way for Android 12, it shows 2 times the splash screen.
 
How can I do both before android 12 and before android 12? can you show an example

**Comment by batuhansavas-yilmaz** [comment]
Thanks. I try tomorrow


________________________________

**Comment by batuhansavas-yilmaz** [comment]
yes, that's how  codes. I just want to sing this : shows splash_screen for both android 12+ and android 12- for android 12+ devices :( Kimden: Milind GoelGönderilme: 2 Ağustos 2023 Çarşamba 18:15Kime: jonbhanson/flutter_native_splashBilgi: Batuhan Savaş Yılmaz; AuthorKonu: Re: [jonbhanson/flutter_native_splash] Android 12 splaash screen problem (Issue #576) If you are using this code in the same way without proper indentations before each block, it's gonna cause issues. You should write the config file properly. The android_12 block has to be properly indented.flutter_native_splash:  color: "#000000"  image: assests/splash_screen/splash_screen.png  branding: assests/splash_screen/branding.png  color_dark: "#000000"  image_dark: assests/splash_screen/splash_screen.png  branding_dark: assests/splash_screen/branding.png  android_12:    image: assests/splash_screen/splash_screen.png    branding: assests/splash_screen/branding.png    icon_background_color: "#000000"    image_dark: assests/splash_screen/splash_screen.png    icon_background_color_dark: "#000000"    branding_dark: assests/splash_screen/branding.png—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by milindgoel15** [comment]
![Screenshot_2023-08-04-20-16-55-298_com.github.android.jpg](https://github.com/jonbhanson/flutter_native_splash/assets/45682747/8b45484b-5931-4ab5-a50d-98094ee8647e)

Your messages are coming as big spam messages when you reply directly from your email. 

Please use the GitHub app or website. Otherwise it's gonna be hard to understand what you really mean.

**Comment by batuhansavas-yilmaz** [comment]
where can i send message to you  Kimden: Milind GoelGönderilme: 4 Ağustos 2023 Cuma 17:48Kime: jonbhanson/flutter_native_splashBilgi: Batuhan Savaş Yılmaz; AuthorKonu: Re: [jonbhanson/flutter_native_splash] Android 12 splaash screen problem (Issue #576) Your messages are coming as big spam messages when you reply directly from your email.Please use the GitHub app or website. Otherwise it's gonna be hard to understand what you really mean.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by batuhansavas-yilmaz** [comment]
Look codes  please.
Apart from these, do I need to do anything extra in the manifest or build.gradle file?

![Screenshot_3](https://github.com/jonbhanson/flutter_native_splash/assets/71197619/727a0dcc-1c9c-4e35-a3a6-b494a0d8950f)

**Comment by batuhansavas-yilmaz** [comment]
okey i try

**Comment by milindgoel15** [comment]
It should not. Maybe just create a fresh android folder again and add all the necessary files. Make sure you are not creating duplicate entries.

**Comment by batuhansavas-yilmaz** [comment]
Hello , it's me again.  I'm using "color" parameter but I can't give background color in android 12 :(

**Comment by milindgoel15** [comment]
The properties you defined for Android 11 and below have to be defined for Android 12 again. They are not common properties.

**Comment by batuhansavas-yilmaz** [comment]
I add an image using the "image" parameter in android 12, when I use the "color" parameter for the background color, the color I gave is not applied, the default colors of android 12 are applied.  Do I need to apply the "icon_background_color" parameter?  My computer is very slow so I wanted to ask you before I do some trial and error, sorry please.

**Comment by milindgoel15** [comment]
The icon_background_color is for an icon background, not a splash background. Splash background uses the `color:` for light mode and `color_dark:` for dark mode.

In order for me to understand what's happening, answer these for me

What color did you set?
What color are you getting?

Also, show the code of flutter_native_splash.

**Comment by batuhansavas-yilmaz** [comment]
color: '#ffffff' => result: white , i think default white 
color: '#ffffff' => result:  default android 12 gray.


If you are available, can you make a trial project for android 12?

**Comment by milindgoel15** [comment]
> If you are available, can you make a trial project for android 12?

I already have 2 projects running and android 12 works fine for me.

So please show your flutter_native_splash code.

**Comment by batuhansavas-yilmaz** [comment]
Could you please show me the flutter_native_splash, androidmanifest, style codes and files?  I'm not at home right now and it will be very difficult to show the codes

**Comment by milindgoel15** [comment]
> I'm not at home right now and it will be very difficult to show the codes

It's fine. You can show your code when you get back.

**Comment by batuhansavas-yilmaz** [comment]
Okey thanks

**Comment by batuhansavas-yilmaz** [comment]
Hi sir, these are my codes.

`flutter_native_splash:
  color: "#ffffff"
  image: assests/splash_screen/android12-/splash_screen_dark.png
  color_dark: "#ffffff"
  image_dark: assests/splash_screen/android12-/splash_screen_dark.png
  ios: false
  web: false
  android_12:
    image: assests/splash_screen/android12+/and12_splash_screen_light.png
    image_dark: assests/splash_screen/android12+/and12_splash_screen_light.png
    color: "#ff0000"
    color_dark: "#042a49"`

**Comment by batuhansavas-yilmaz** [comment]
Meaninglessly, it's working now...

**Comment by batuhansavas-yilmaz** [comment]
I guess color_dark doesn't support white color :D

**Comment by milindgoel15** [comment]
> I guess color_dark doesn't support white color for xiaomi devices.

About Xiaomi and other devices that are not AOSP-like, they force apps to always use dark mode. So you have to explicitly disallow your app to not use force dark mode or disable force dark mode in your MIUI settings. 

Although, having a light background even in dark mode is not a good user experience.

**Comment by batuhansavas-yilmaz** [comment]
Thanks for everything.

 Finally, 

What size should be for "branding" , for android 12+ and android 12-

**Comment by milindgoel15** [comment]
> What size should be for \"branding\" , for android 12+ and android 12-

Follow the [android docs](https://developer.android.com/develop/ui/views/launch/splash-screen#dimensions)

**Comment by batuhansavas-yilmaz** [comment]
Thanks:)

**Comment by erperejildo** [comment]
> > What size should be for "branding" , for android 12+ and android 12-
> 
> Follow the [android docs](https://developer.android.com/develop/ui/views/launch/splash-screen#dimensions)

I'm a little bit confused with this. I didn't update my app for a while and now I see all of these android 12 articles. I just have a simple image displaying, no animation, but this doesn't seem to work anymore. Do I need to change anything else? I tried to remove and create it again but doesn't work:

```
flutter_native_splash:
  image: assets/images/splashscreen.png
  color: "281b60"
  fill_horizontal: true
```

Only thing I did was update the package to its latest version

**Comment by erperejildo** [comment]
> I used image 400x400. And color is '#.......'. you dont use '#'

nothing, still no image. The documentation says:

```
# The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
```
did this change? What does it mean 4p pixel density exactly?

**Comment by erperejildo** [comment]
This worked:

```
flutter_native_splash:
  color: "#281b60"
  color_dark: "#281b60"
  image: assets/images/splashscreen.png
  image_dark: assets/images/splashscreen.png

  android_12:
    icon_background_color: "#281b60"
    icon_background_color_dark: "#281b60"
    image: assets/images/splashscreen.png
    image_dark: assets/images/splashscreen.png
```

**Comment by batuhansavas-yilmaz** [comment]
There is a bug here, only one of the parameters image and icon_background_color is used. You should use the Background_color parameter for the background color

**Comment by Mashood97** [comment]
You guys can simply avoid the Android 12 default splash screen with Applogo using the below steps:

Goto Android folder -> inside app -> src-> main -> res:
Inside all values directory we have styles.xml file:
Add this item in both of the style attributes:

<item name="android:windowIsTranslucent">true</item>

Add this in all styles.xml files inside the style attribute and see the magic of how it works.

**Comment by mmotkim** [comment]
> You guys can simply avoid the Android 12 default splash screen with Applogo using the below steps:
> 
> Goto Android folder -> inside app -> src-> main -> res: Inside all values directory we have styles.xml file: Add this item in both of the style attributes:
> 
> true
> 
> Add this in all styles.xml files inside the style attribute and see the magic of how it works.

Did you cut off your code?

**Comment by jonbhanson** [comment]
@batuhansavas-yilmaz is your problem resolved now?  OK to close this ticket?

**Comment by batuhansavas-yilmaz** [comment]
> @batuhansavas-yilmazşu an sorununuz çözüldü mü? Bu bileti kapatmam uygun mu?

Yes, thanks.
