### ISSUE TITLE
flutter iOS app is stuck on launchscreen when installed on real device

### ISSUE THREAD

**Issue by pugnoxi** [jonbhanson/flutter_native_splash#577]
**Describe the bug**

I have this flutter app where I've set up a flutter_native_splash screen with the package that is named the same. I've used the command and the description from the installation guide (pub spec.yaml etc.) and my app runs fine when tested on android emulator, real android device and debug mode in iOS simulator (and on real device). Now the confusing thing is, that the app is getting sometimes in the splash screen where the app is opened. This only happens when I'm installing the version from TestFlight. But when I'm trying to open up the app multiple times, it opens the app to the home screen. No error is shown in the console and so on, my flutter doctor is saying that everything is installed correctly.

Here is my main.dart code:

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  //Notifications
  await FirebaseApi().initNotifications();
  HttpOverrides.global = MyHttpOverrides();
  //Hive Database
  await Hive.initFlutter();
  //Analytics init
  FirebaseAnalytics analytics = FirebaseAnalytics.instance;
  final SharedPreferences sharedPreferences =
      await SharedPreferences.getInstance();
  runApp(const AulingerMain());
  // Need await here
  await Future.delayed(const Duration(milliseconds: 1));
  FlutterNativeSplash.remove();
}

class AulingerMain extends StatefulWidget {
  const AulingerMain({super.key});

  @override
  State<AulingerMain> createState() => _AulingerMainState();
}

class _AulingerMainState extends State<AulingerMain> {
  @override
  Widget build(BuildContext context) {
    return OverlaySupport(
      child: MultiProvider(
        providers: [
          ListenableProvider<UserProvider>(create: (_) => UserProvider()),
        ],
        child: ThemeModeHandler(
            manager: ThemeManager(),
            builder: (ThemeMode themeMode) {
              return MaterialApp(
                  title: 'Gasthof zum Sonnenwald',
                  debugShowCheckedModeBanner: false,
                  theme: ThemeData(
                      appBarTheme: const AppBarTheme(
                    centerTitle: true,
                    backgroundColor: Colors.amber,
                  )),
                  darkTheme: ThemeData.dark(),
                  themeMode: themeMode,
                  home: FutureBuilder<bool>(
                    future: checkFirstTime(),
                    builder: (context, snapshot) {
                      if (snapshot.connectionState == ConnectionState.waiting) {
                        return const Center(
                          child: CircularProgressIndicator(color: Colors.amber),
                        );
                      }

                      final isFirstTime = snapshot.data ?? true;

                      return isFirstTime
                          ? const EinfuehrungFrage()
                          : const AutoLoginHandler();
                    },
                  ), //sets home to autologinhandler at start for auto login
                  builder: (context, child) {
                    return MediaQuery(
                      data:
                          MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                      child: child!,
                    );
                  },
                  routes: {
                    Settings.routeName: (ctx) => const Settings(),
                    MainPage.routeName: (ctx) => const MainPage(),
                    Speisekarte.routeName: (ctx) => const Speisekarte(),
                    ContactUsPage.routeName: (ctx) => const ContactUsPage(),
                    LoginScreen.routeName: (ctx) => const LoginScreen(),
                    ImprintScreen.routeName: (ctx) => const ImprintScreen(),
                    SelectionScreenEssen.routeName: (ctx) =>
                        const SelectionScreenEssen(),
                    PrivacyPolicyScreen.routeName: (ctx) =>
                        const PrivacyPolicyScreen(),
                  });
            }),
      ),
    );
  }

  Future<bool> checkFirstTime() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    bool isFirstTime = prefs.getBool('isFirstTime') ?? true;
    return isFirstTime;
  }
}

class MyHttpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext? context) {
    return super.createHttpClient(context)
      ..badCertificateCallback =
          (X509Certificate cert, String host, int port) => true;
  }
}

**Configuration**

This is the code from pubsped.yaml:

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/appstore.png
  image_dark: assets/icons/appstore.png
  color_dark: "#282828"
  android: true
  ios: true

**Device (please complete the following information):**
 - Device: iphone 6s
 - OS: 15.2.1

**Additional context**
This only happens on real device on ios with this phone and other phones. When connected via cable and with the debug enabled, nothing goes wrong

**Comment by clevonnoel** [comment]
I am also experiencing this issue

**Comment by pugnoxi** [comment]
@clevonnoel oh i'm so happy that i'm not alone with that issue... can you tell me on what xcode version and macos version you're on?

**Comment by flavio-silva** [comment]
I am also experiencing this issue only IOS. Some of our customers cannot use the app because it gets stuck on the splash screen.

I don't know if this is related to the library or some IOS recent updates.

**Comment by flyj222** [comment]
Same issues here, the iOS app simply can't be tested by others through TestFlight.

The app was archived with XCode 14.3.1 and macOS 13.4.1.
Feels like some issues related to XCode since I didn't make major changes to my app.

**Comment by pugnoxi** [comment]
I've just got the "fix". 

Just reinstall Xcode from scratch, then everything works fine! :)

**Comment by gikwegbu** [comment]
So I just faced this issue, and it help me up for hours.
Nothing was wrong with my Xcode or anything.

Tip to Resolve.

1. If you're unable to see the error log in your editor or IDE console, it's normal.
2. Add `firebase crashlytics` to your app. There you'd catch the exception being thrown.

In my case,I was trying to `await _firebaseMessaging.subscribeToTopic(Topic)`, and for this to work on IOS, I have to first get the APNS Token. Which in turn caused an error. To solve this, 


if (Platform.isIOS) {
      String? apnsToken = await _firebaseMessaging.getAPNSToken();
      if (apnsToken != null) {
        // await _firebaseMessaging.subscribeToTopic("notificationChannel");
        try {
          await _firebaseMessaging.subscribeToTopic('notificationChannel');
        } on FirebaseException catch (e) {
          debugPrint("George here is the error: $e");
        }
      } else {
        await Future<void>.delayed(const Duration(seconds: 3));
        apnsToken = await _firebaseMessaging.getAPNSToken();
        if (apnsToken != null) {
          try {
            await _firebaseMessaging.subscribeToTopic('notificationChannel');
          } on FirebaseException catch (e) {
            debugPrint("George here is the error: $e");
          }
        }
      }
    } else {
      try {
        await _firebaseMessaging.subscribeToTopic('notificationChannel');
      } on FirebaseException catch (e) {
        debugPrint("George here is the error: $e");
      }
    }


The summary of my comment is;

Track all the functions you are calling before you hit your splash screen.

**Comment by mc-stephen** [comment]
> So I just faced this issue, and it help me up for hours. Nothing was wrong with my Xcode or anything.
> 
> Tip to Resolve.
> 
> 1. If you're unable to see the error log in your editor or IDE console, it's normal.
> 2. Add `firebase crashlytics` to your app. There you'd catch the exception being thrown.
> 
> In my case,I was trying to `await _firebaseMessaging.subscribeToTopic(Topic)`, and for this to work on IOS, I have to first get the APNS Token. Which in turn caused an error. To solve this,
> 
> ```dart
> if (Platform.isIOS) {
>       String? apnsToken = await _firebaseMessaging.getAPNSToken();
>       if (apnsToken != null) {
>         // await _firebaseMessaging.subscribeToTopic("notificationChannel");
>         try {
>           await _firebaseMessaging.subscribeToTopic('notificationChannel');
>         } on FirebaseException catch (e) {
>           debugPrint("George here is the error: $e");
>         }
>       } else {
>         await Future<void>.delayed(const Duration(seconds: 3));
>         apnsToken = await _firebaseMessaging.getAPNSToken();
>         if (apnsToken != null) {
>           try {
>             await _firebaseMessaging.subscribeToTopic('notificationChannel');
>           } on FirebaseException catch (e) {
>             debugPrint("George here is the error: $e");
>           }
>         }
>       }
>     } else {
>       try {
>         await _firebaseMessaging.subscribeToTopic('notificationChannel');
>       } on FirebaseException catch (e) {
>         debugPrint("George here is the error: $e");
>       }
>     }
> ```
> 
> The summary of my comment is;
> 
> Track all the functions you are calling before you hit your splash screen.

Wow, this seems to help, thanks.

**Comment by pKm49** [comment]
> ```dart
> if (Platform.isIOS) {
>       String? apnsToken = await _firebaseMessaging.getAPNSToken();
>       if (apnsToken != null) {
>         // await _firebaseMessaging.subscribeToTopic("notificationChannel");
>         try {
>           await _firebaseMessaging.subscribeToTopic('notificationChannel');
>         } on FirebaseException catch (e) {
>           debugPrint("George here is the error: $e");
>         }
>       } else {
>         await Future<void>.delayed(const Duration(seconds: 3));
>         apnsToken = await _firebaseMessaging.getAPNSToken();
>         if (apnsToken != null) {
>           try {
>             await _firebaseMessaging.subscribeToTopic('notificationChannel');
>           } on FirebaseException catch (e) {
>             debugPrint("George here is the error: $e");
>           }
>         }
>       }
>     } else {
>       try {
>         await _firebaseMessaging.subscribeToTopic('notificationChannel');
>       } on FirebaseException catch (e) {
>         debugPrint("George here is the error: $e");
>       }
>     }
> ```

Thanks mate, saved my day.
