### ISSUE TITLE
Android 12 - Splash screen image is getting enlarged

### ISSUE THREAD

**Issue by NilukaBandara** [jonbhanson/flutter_native_splash#578]
I tried to change the image and background colour of the native flutter splash screen. In Android 12 it is appearing as second image. But I am expecting it as first image. Seems like the image has got enlarged.

The flutter_native_splash section of your yaml config.
flutter_native_splash:
  color: "#000000"
  image: "assets/kix/kix_new.png"
  android_12:
    image: "assets/kix/KIX_Word_X.png"
    icon_background_color: "#000000"

Device
 - Samsung S10e
 - Android 12

<img width="401" alt="image1" src="https://github.com/jonbhanson/flutter_native_splash/assets/14539646/d87affd4-2652-45a1-89e4-22b39f6576e2">
<img width="353" alt="image2" src="https://github.com/jonbhanson/flutter_native_splash/assets/14539646/a73ab943-5a73-4f43-aa3a-4fc2c97fe08f">

**Comment by awaisjamil-vd** [comment]
any update on it?

**Comment by jonbhanson** [comment]
Did you size your Android image according to the instructions in the readme?
>    # Please note that the splash screen will be clipped to a circle on the center of the screen.
>    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
>    # 640 pixels in diameter.
>    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
>    # 768 pixels in diameter.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you still have a problem.

**Comment by lincolnzera1** [comment]
same error here

**Comment by PatrykIZajac** [comment]
@jonbhanson Do you mean that we should clip especially for android 12 image for square  768 x 768? I cropped it and still have problems with clipping by android 12 my image. Have you any advices on it?

**Comment by PatrykIZajac** [comment]
@lincolnzera1 I figure out why is this not working. In docs u have strict measures that you should use. Try to make in design editor like figma square 1052 x 1052. In this square in his center make circle 768 x 768. Now image that u want inject to splash inject to circle. Layer of circle u can later mute so u will export splash icon without it. For me it works fine for both platforms :)

**Comment by TClaius** [comment]
> @lincolnzera1 I figure out why is this not working. In docs u have strict resolution that you should use. Try to make in design editor like figma square 1052 x 1052. In this square in his center make circle 768 x 768. Now image that u want inject to splash inject to circle. Layer of circle u can later mute so u will export splash icon without it. For me it works fine for both platforms :)

You nail it! thanks i could make it too!

**Comment by houssam15** [comment]
> @lincolnzera1 I figure out why is this not working. In docs u have strict resolution that you should use. Try to make in design editor like figma square 1052 x 1052. In this square in his center make circle 768 x 768. Now image that u want inject to splash inject to circle. Layer of circle u can later mute so u will export splash icon without it. For me it works fine for both platforms :)

worked for me I test in in android 13 and android 10

**Comment by SaqibWani273** [comment]
> @lincolnzera1 I figure out why is this not working. In docs u have strict resolution that you should use. Try to make in design editor like figma square 1052 x 1052. In this square in his center make circle 768 x 768. Now image that u want inject to splash inject to circle. Layer of circle u can later mute so u will export splash icon without it. For me it works fine for both platforms :)
Thanks, it worked for me

**Comment by beloufaimededdine** [comment]
> [@lincolnzera1](https://github.com/lincolnzera1) I figure out why is this not working. In docs u have strict resolution that you should use. Try to make in design editor like figma square 1052 x 1052. In this square in his center make circle 768 x 768. Now image that u want inject to splash inject to circle. Layer of circle u can later mute so u will export splash icon without it. For me it works fine for both platforms :)

Perfect!!!! thank you <3

**Comment by IC-XOrbit-07** [comment]
@houssam15 Size Should be 1152x1152 for square
