### ISSUE TITLE
Change Framerate for GIF in for flutter web

### ISSUE THREAD

**Issue by DragonSlayer88** [jonbhanson/flutter_native_splash#579]
i have a gif that works as a splashscreen, and it has a framerate of 24. but when i see it on the app it seems to be like 5 or 10 and its very choppy. Can you add a feature to change that. or make it smoother?

**Comment by jonbhanson** [comment]
Is this problem on web?  Can you add your source GIF?

**Comment by DragonSlayer88** [comment]
Yes it's an issue on web. And I can't share the gif because it has a company logo on it. But you can try it with any gif that has a high frame rate.

**Comment by jonbhanson** [comment]
@OutdatedGuy can you look at this?

**Comment by OutdatedGuy** [comment]
It looks like the problem might be in the [image](https://pub.dev/packages/image) package [here](https://github.com/brendan-duncan/image/blob/c4a8783e5a1d5e80b93ec33c571b1749a5951713/lib/src/formats/gif_encoder.dart#L120-L136) that we use to [encode gif](https://github.com/jonbhanson/flutter_native_splash/blob/677dbd47d87ee250cc3c6ab343d18a7b61acbbd3/lib/web.dart#L253).

So I don't think we can do anything about this at the moment.

**Comment by jonbhanson** [comment]
@DragonSlayer88 it looks like there was a framerate fix that [was added](https://github.com/brendan-duncan/image/issues/511#issuecomment-1539465802) in the `image` package.  Can you confirm that the problem has been resolved?

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having a problem.
