### ISSUE TITLE
Allow adding custom widget and logic to the splash screen

### ISSUE THREAD

**Issue by BadPistol97** [jonbhanson/flutter_native_splash#580]
**Is your feature request related to a problem? Please describe.**
I need to display an ad banner at the bottom of the splash screen and wait for a few seconds. 

**Describe the solution you'd like**
Expose the splash screen logic and allow widgets to show on splash screen. 

**Describe alternatives you've considered**
Allow ad banner feature

**Additional context**

**Comment by jonbhanson** [comment]
Sorry, this feature will not be added.
