### ISSUE TITLE
The lower bound of "sdk: '>=2.0.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.

### ISSUE THREAD

**Issue by zhakypovmaksatbek** [jonbhanson/flutter_native_splash#581]
The lower bound of "sdk: '>=2.0.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.

**Comment by jonbhanson** [comment]
I'm not sure why you have opened this ticket because this package uses
```yaml
  sdk: '>=2.19.0 <4.0.0'
```

**Comment by kangminjiiiii** [comment]
I wrote "flutter_swiper: ^1.1.6" in pubspec.yaml to use "flutter swiper." And I used the "flutter pub get" command, but I get a null-safety error with the same phrase as yours. How did you fix it?

**Comment by gyan7470** [comment]
The current Dart SDK version is 3.4.0-99.0.dev.

Because chat depends on rethinkdb_dart any which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=1.20.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.

how i can fix thi error

**Comment by jonbhanson** [comment]
@gyan7470 the problem is that you are trying to use `rethinkdb_dart`, which has not been updated in 4 years and is not compatible with current versions of Flutter.

**Comment by gyan7470** [comment]
Is there any better options rather than docker and rithink.

**Comment by jonbhanson** [comment]
You will not get good advice about docker and rithink by asking advice from the maintainer of a Flutter Splash Screen package.  Maybe ask on reddit or stackoverflow docker/rithink communities.
