### ISSUE TITLE
Deprecated API Usage on Android

### ISSUE THREAD

**Issue by behnamsattar** [jonbhanson/flutter_native_splash#582]
Based on the warning message I got while building for Android, this package uses deprecated API.

```
Note: /Users/behnam/.pub-cache/hosted/pub.dev/flutter_native_image-0.0.6+1/android/src/main/java/com/example/flutternativeimage/FlutterNativeImagePlugin.java uses or overrides a deprecated API.
```

To reproduce, simply do an Android build with the latest version of the plugin included.

**Comment by jonbhanson** [comment]
It looks like you opened this ticket with the wrong package.  This is `flutter_native_splash`, but your error is for `flutter_native_image`.
