### ISSUE TITLE
gif not playing in splash screen

### ISSUE THREAD

**Issue by asifwebmobril** [jonbhanson/flutter_native_splash#583]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

**Configuration**

Paste the flutter_native_splash section of your yaml config.

**Device (please complete the following information):**

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to '...'
2. Run in an emulator configured with '...'
3. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.  If in doubt, attach a screenshot.

**Additional context**

**Comment by jonbhanson** [comment]
No details.

**Comment by asifwebmobril** [comment]
if i put gif file as a splash it should play not a static screen but in your package no way to play gif file 
so what kind of details you need to understand of playing the gif

**Comment by rajesh-h** [comment]
@asifwebmobril did you get any solution here?
