### ISSUE TITLE
Gif Splash Screen

### ISSUE THREAD

**Issue by batuhansavas-yilmaz** [jonbhanson/flutter_native_splash#587]
Is it currently possible to use gif content? If not, when will it be supported?

**Comment by Faiizii** [comment]
gifs are not supported by the native platform so far. read following links for SplashScreen APIs & Supported Drawables. 

1. https://developer.android.com/develop/ui/views/launch/splash-screen
2. https://developer.android.com/reference/android/graphics/drawable/AnimatedVectorDrawable

Once, the gif files are accepted by the native platform, somebody will integrate gif files in this library package.

**Comment by batuhansavas-yilmaz** [comment]
Thanks sir.

**Comment by rajesh-h** [comment]
I was excited based on this answer - https://stackoverflow.com/questions/76162137/flutter-how-to-give-gif-image-on-the-native-splash-screen
But looks like it is no more relevant

**Comment by batuhansavas-yilmaz** [comment]
> I was excited based on this answer - https://stackoverflow.com/questions/76162137/flutter-how-to-give-gif-image-on-the-native-splash-screen But looks like it is no more relevant

Thanks anyway, friend.
