### ISSUE TITLE
Custom splash background image not visible on app startup

### ISSUE THREAD

**Issue by pranay289** [jonbhanson/flutter_native_splash#597]
Hi I wanted to add a custom splash background image on the default splash screen but it is not showing I tried this below in my `pubspec.yaml` file 

`flutter_native_splash: ^2.0.5`

```flutter_native_splash:
  android: true
  ios: false
  web: false
  background_image: assets/background_image.png

  android_12: 
    android: true
    ios: false
    web: false
    background_image: assets/background_image.png
```

But instead of a custom image, it shows the default splash screen and If I use `color` property it works but `background_image` not working can you help me with this

**Comment by jonbhanson** [comment]
`android_12` does not have a `background_image`.  You may want to read the readme.
