### ISSUE TITLE
requires SDK version >=3.1.0 <4.0.0, version solving failed.

### ISSUE THREAD

**Issue by mazab99** [jonbhanson/flutter_native_splash#599]
dart run flutter_native_splash:create

when I made it , I got this error 

environment:
  sdk: '>=3.1.0 <4.0.0'

**Comment by jonbhanson** [comment]
I was not able to reproduce the error.  Please include your `flutter doctor` output and your `pubspec.yaml` contents.

**Comment by mazab99** [comment]
flutter_native_splash:
  image: assets/images/splash_logo.png
  #color: "#ffffff"
  background_image: assets/images/splashBackground.png
  image_dark: assets/images/splashLogo.png
  #color_dark : "#000000"
  background_image_dark: assets/images/splashBackground.png
  android: true
  ios: true

**Comment by mazab99** [comment]
[!] Flutter (Channel stable, 3.13.5, on macOS 13.4 22F66 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by mazab99** [comment]
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

**Comment by jonbhanson** [comment]
What is your output to `dart --version`?

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.

**Comment by amirovsunnat** [comment]
environment:
  sdk: '>=3.4.3 <4.0.0'

still having problem using workflow build fails because of Resolving dependencies...
The current Dart SDK version is 3.3.0.
Because redder_taxi requires SDK version >=3.4.3 <4.0.0, version solving failed.
Error: Process completed with exit code 1.
