### ISSUE TITLE
branding icon is squeezed

### ISSUE THREAD

**Issue by laterdayi** [jonbhanson/flutter_native_splash#605]
branding icon is squeezed
branding icon on android12 or below how many pixels should be set, now the icon size is always compressed

**Comment by jonbhanson** [comment]
Closed due to lack of details.

**Comment by sagimann** [comment]
may I add some details: the branding image resolution is not documented in the yaml comments hence an attempt to add an image of some size might appear squeezed or streched. If we know the resolution, we'll adapt the image accordingly

**Comment by yanghoonkim** [comment]
5:2 maybe. https://github.com/jonbhanson/flutter_native_splash/issues/341#issuecomment-1699289300
