### ISSUE TITLE
White screen on web when using "FlutterNativeSplash.remove()"

### ISSUE THREAD

**Issue by eggp** [jonbhanson/flutter_native_splash#607]
Hello,

On the web, when I want to use "FlutterNativeSplash.remove()", a white screen appears for a moment after the splash screen is removed. Example code: https://github.com/eggp/flutter_native_splash_web_flickering_fix/blob/main/lib/main.dart | demo app: https://eggp.github.io/flutter_native_splash_web_flickering_fix/flickering/

I think the solution is simple. Because of the JavaScript eventloop, you have to use the setTimeout(0) trick, which I usually achieve using SchedulerBinding in flutter. Example code: https://github.com/eggp/flutter_native_splash_web_flickering_fix/blob/fix/lib/main.dart#L13 | demo app: https://eggp.github.io/flutter_native_splash_web_flickering_fix/fix/

The problem arises from the fact that Timer is in the widgetsBinding.allowFirstFrame->scheduleWarmUpFrame call chain.

**Comment by jonbhanson** [comment]
@eggp This is excellent, thanks!  I will push an update soon that adds this.
