### ISSUE TITLE
Image does not show on iOS

### ISSUE THREAD

**Issue by BeanBagGamer** [jonbhanson/flutter_native_splash#61]
Hello, All working fine on android but on iOS sim and device the colour displays fine but the image does not show. 

any ideas on what the issue could be?

**Comment by abdullah-alamin-inme** [comment]
same here

**Comment by lauralarez** [comment]
For me, this issue was because the Launch Images created were unassigned so I had to manually set them in Xcode.

     In Xcode, Click on your Assets file (Images.xcassets) in the left sidebar. You should see the list of assets (AppIcon, LaunchImage..), right click there and select New Image Set, now you can drop the images. 
     Finally you'll need to rename the "Image" set to "LaunchImage" and delete the one that was previously created.

**Comment by AntonyLeons** [comment]
I also have this, dragging the children to replace the parents in xcode worked for me

**Comment by jonbhanson** [comment]
I think this should be resolved by recent updates.  Please reopen the issue if you experience any other troubles.
