### ISSUE TITLE
failure when generating app

### ISSUE THREAD

**Issue by andishmandsaadi** [jonbhanson/flutter_native_splash#610]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_native_splash:parseReleaseLocalResources'.
> Could not resolve all files for configuration ':flutter_native_splash:androidApis'.
   > Failed to transform android.jar to match attributes {artifactType=android-platform-attr, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for PlatformAttrTransform: /Users/asdfasdf/Library/Android/sdk/platforms/android-31/android.jar.
         > /Users/asdfasdf/Library/Android/sdk/platforms/android-31/android.jar

**Comment by jonbhanson** [comment]
This looks like an IDE or project configuration issue, rather than an issue with this package.  Maybe `flutter clean` will resolved it?

**Comment by andishmandsaadi** [comment]
I applied every possible option but no solution. now I use flutter_native_splash: ^1.2.0 version and it has no problem

**Comment by jonbhanson** [comment]
Could you provide a minimal project that reproduces this error so I can try to resolve it?

**Comment by andishmandsaadi** [comment]
[otoparcasan.zip](https://github.com/jonbhanson/flutter_native_splash/files/13456284/otoparcasan.zip)

**Comment by jonbhanson** [comment]
I ran your minimal project, but I didn't see the error that you mentioned above.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you're still having trouble.
