### ISSUE TITLE
Splash screen shows two images, a small one then a large one.

### ISSUE THREAD

**Issue by c-lamont** [jonbhanson/flutter_native_splash#611]
**Describe the bug**

On iOS, when the splash screen appears, it first shows a very small version of my image, then shows a big version of my image.

**Configuration**

```yaml
flutter_native_splash:
  image: assets/images/splash_logo.png
  color: "#000000"
```

**Device (please complete the following information):**
 - Device: iPhone 14
 - OS: 16.4

**To Reproduce**
Steps to reproduce the behavior, using the example app:
I can't find your sample app.

I added the package in my yaml file under Dev Dependencies.
Added the configuration above.
Then ran `flutter clean && flutter pub get && dart run flutter_native_splash:create`
Then launched my app.

**Screenshots**
First image: https://ibb.co/kS1cQ3B
Second image: https://ibb.co/VL6Pk4R

**Additional context**
None

**Comment by jonbhanson** [comment]
Can you add a minimal stripped out project here that has the problem?

**Comment by c-lamont** [comment]
No idea why, but trying again today it is working.
