### ISSUE TITLE
Screen splash logo is icon launch, not is configured logo

### ISSUE THREAD

**Issue by deverlex** [jonbhanson/flutter_native_splash#613]
My device on Android 13

I set icon_launch.png in mipmap...
I set other image for flutter_native_splash
I had generated images, and I have seen generated images on drawable-xxx

But image on splash screen is icon_launch.png

version
flutter_native_splash: ^2.3.5

**Comment by jonbhanson** [comment]
Please add you config details.

**Comment by hadi7khan** [comment]
@deverlex can you please share how you configured it. I want to do the same

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.
