### ISSUE TITLE
(FlutterSplashPackageError) Execution failed for task ':flutter_native_splash:parseDebugLocalResources'. ( Android flutter)

### ISSUE THREAD

**Issue by OmarAzzam02** [jonbhanson/flutter_native_splash#616]
installed the `flutter_naitive_splash `package i ran the` flutter pub get `and i ran into no problems when i ran `dart run flutter_native_splash:create` in the command line it was all fine the problem occurred when I ran `flutter run`

error list:
![Screenshot (47)](https://github.com/jonbhanson/flutter_native_splash/assets/93334715/265c0f40-76ac-40d6-b6b5-c45a8269f2a6)

flutter plugins:
![Screenshot (48)](https://github.com/jonbhanson/flutter_native_splash/assets/93334715/395bfaa0-009f-4731-979b-726f5a5bbfeb)

build.Gradel: 
![Screenshot (49)](https://github.com/jonbhanson/flutter_native_splash/assets/93334715/f6cf89a8-1e69-4b42-b890-569367e0aa50)

setting.gradle :
![Screenshot (50)](https://github.com/jonbhanson/flutter_native_splash/assets/93334715/093d4dd1-76b4-467c-a806-1076d7cc569d)

t said something about Gradle tried updating and said i was up to date but the last version is V8.4 it was confusing i just downloaded flutter 2 days ago (`flutter upddate `=>  all up to date same as dart )`(flutter doctor`=> no issues found) and tried this splash package to inset an image before running the home page the dependencies work just fine but when I just installed the package the flutter run won't work can you please help me with this issue

**Comment by jonbhanson** [comment]
Please add your `flutter_native_splash` config from your `pubspec.yaml`.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you're still having trouble.
