### ISSUE TITLE
Some requests for bugs

### ISSUE THREAD

**Issue by joh9911** [jonbhanson/flutter_native_splash#617]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

I spent so many times for solving issues where flutter's default splash shows before splash page that I added shows out.
It's related to Android 12.

First, (I don't know whether It's only for me or not) Flutter_native_splash library doesn't add the feature to V31 - styles.xml.
I just got to know that truth after reading the closed issues.

After adding the code, `<item` `name="android:windowBackground">@drawable/launch_background</item>` in every styles file,
then default splash page background changed, except for icon.

Second, the default splash page's icon only shows default flutter icon even if I add some codes in launch_background.xml.
It only changes to Icon that I set when I add the code `<item` `name="android:windowIsTranslucent">true</item>` in evey styles file.

It was solved though, I just want to know that kinds of issues only appear to me.

**Configuration**
**Flutter_native_splash.yaml,**

```yaml
flutter_native_splash:

  background_image: assets/splash_logo.png

  android_12:

  image: assets/splash_logo.png
  color: "#1EAD5E"
  icon_background_color: "#1EAD5E"

  android: true
  ios: true
```

 
  **pubspec.yaml,**
  
![image](https://github.com/jonbhanson/flutter_native_splash/assets/102031783/24374c56-48ad-4b18-93c9-4b639c5041d3)

    
**AndroidMenifest,**
![image](https://github.com/jonbhanson/flutter_native_splash/assets/102031783/772946b2-dd97-406a-97b3-7cca51e30f1e)
              

**launch_background.xml,**
![image](https://github.com/jonbhanson/flutter_native_splash/assets/102031783/877df87d-faeb-496a-b36f-acc67ca34f7c)

**Styles.xml** (all same with the other styles.xml)
![image](https://github.com/jonbhanson/flutter_native_splash/assets/102031783/6c0bfae3-cecb-49c1-9ea4-b657372c483d)

**Device (please complete the following information):**
 - Device: Galaxy Note 20

**To Reproduce**
Steps to reproduce the behavior, using the example app:

I use the real phone.

**Screenshots**
With  `<item name="android:windowIsTranslucent">true</item>`
![image](https://github.com/jonbhanson/flutter_native_splash/assets/102031783/0a79fcbc-f1f3-4170-883d-e21b4a8b33ad)

Without

![image](https://github.com/jonbhanson/flutter_native_splash/assets/102031783/fb09232a-a6e7-40bf-a9d1-54b90bf31e69)
![image](https://github.com/jonbhanson/flutter_native_splash/assets/102031783/f4dcc0e9-c64e-4690-a75e-ebeb96f88299)

**Additional context**

**Comment by jonbhanson** [comment]
Do you have the following code in your android/app/src/main/AndroidManifest.xml?

```xml
<meta-data
 android:name="io.flutter.embedding.android.SplashScreenDrawable"
 android:resource="@drawable/launch_background"
 />
```

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you're still having trouble.
