### ISSUE TITLE
bug in flutter 3.16

### ISSUE THREAD

**Issue by hatemragab** [jonbhanson/flutter_native_splash#625]
bug in flutter 3.16 
i try to build with flutter 3.16  
and i have updated to 
```
window.flutterWebRenderer is now deprecated.
Use engineInitializer.initializeEngine(config) instead.
```
but the web get stuck in the splash screen if i return the 
```
window.flutterWebRenderer is now deprecated.
```
it works!

**Comment by jonbhanson** [comment]
I'm sorry, I don't understand the problem.  Can you attach a minimal project that demonstrates the problem?

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you're still having trouble.
