### ISSUE TITLE
FlutterNativeSplash.preserve not working on flutter 3.16

### ISSUE THREAD

**Issue by anokabb** [jonbhanson/flutter_native_splash#627]
After upgrading to flutter 3.16 and also using the latest flutter native splash version after the splash displayed it's disappears and shows a black screen until you call `FlutterNativeSplash.remove();`

**Configuration**

flutter_native_splash:
  color: "#000f55"
  image: images/splash.png

 - Device: Pixel 7 Pro
 - OS: Android 12

**To Reproduce**
1. Setup `FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding)` on main
2. Remove or comment `FlutterNativeSplash.remove();`
3. then you will be stuck on black screen

**Comment by anokabb** [comment]
@jonbhanson still getting this issue, i'm using latest versions flutter_native_splash: ^2.3.10 and flutter:3.16.9

**Comment by jonbhanson** [comment]
@anokabb I was not able to reproduce this.  Can you supply a minimal project that demonstrates this error?

**Comment by kane-knowby** [comment]
I am also experiencing on 3.16.4

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen with information on how to reproduce if you are still having trouble.

**Comment by chepFlutter** [comment]
@anokabb @kane-knowby I reprodused it and resolved. Problem was in activity inside AndroidManifest.
I replaced activity with this and everything starts work fine:
`<activity android:name="io.flutter.embedding.android.FlutterActivity"
          android:theme="@style/LaunchTheme"
 android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale"
          android:hardwareAccelerated="true"
          android:exported="true"
          android:windowSoftInputMode="adjustResize">
          <meta-data
              android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
              android:value="true" />
          <intent-filter>
              <action android:name="android.intent.action.MAIN"/>
              <category android:name="android.intent.category.LAUNCHER"/>
          </intent-filter>
      </activity>`
      
      I took this activity from here: https://docs.flutter.dev/release/breaking-changes/plugin-api-migration

**Comment by UmidjonOkhunov** [comment]
I'm experiencing the same issue after upgrading flutter from 3.10.7 to 3.19.6

**Comment by Artein** [comment]
The same for me on Flutter 3.24.0. I do call `FlutterNativeSplash.preserve();` and intentionally don't call `FlutterNativeSplash.remove();`, still see that LaunchBackground (or LaunchScreen.storyboard?) fades out into black.

For now, I don't even know what to check for possible solutions

**Comment by dunt-96** [comment]
> [@jonbhanson](https://github.com/jonbhanson), doesn't work for me either.
> 
> I do call `FlutterNativeSplash.preserve();` and intentionally don't call `FlutterNativeSplash.remove();`, but still see that LaunchBackground (or LaunchScreen.storyboard?) fades out into black.
> 
> For now, I don't even know what to check for possible solutions
> 
> Target: iOS only Flutter: 3.24.0 Package: 2.4.1
> 
> **EDIT:** 6 hours spent figuring out the issue, and after adding this comment I've nailed it. Magic. So, the issue was in selection `LaunchScreen.storyboard` from XCode UI (I specidied it in `Runner -> Runner (under Targets) -> General tab -> App Icons and Launch Screens -> Launch Screen File`). This change updated my `Info.plist` files with the following changes:
> 
> ```
> <key>UILaunchStoryboardName</key>
> <string>LaunchScreen.storyboard</string>
> ```
> 
> Removing the extension `.storyboard` fixed the issue:
> 
> ```
> <key>UILaunchStoryboardName</key>
> <string>LaunchScreen</string>
> ```
> 
> I hope this will help [@UmidjonOkhunov](https://github.com/UmidjonOkhunov) [@jonbhanson](https://github.com/jonbhanson), you can re-check this behavior and add a notice to the readme.
> 
> **EDIT 2:** Well, now I see the difference. For some reason, now the launch screen starts fading in from the black color the the background image. I don't know why adding/removing extension changes this behavior

Sincerely thank you.
i spent 1day for this. 👍
