### ISSUE TITLE
Status bar isn't showing on iOS after fullscreen mode

### ISSUE THREAD

**Issue by alexursul** [jonbhanson/flutter_native_splash#631]
Flutter v3.16, iOS 17.

In pubspec:
```
flutter_native_splash:
  fullscreen: true
  ...
```

In code:
```
    FlutterNativeSplash.remove();
    await SystemChrome.setEnabledSystemUIMode(
      SystemUiMode.manual,
      overlays: [SystemUiOverlay.bottom, SystemUiOverlay.top],
    );
```

However, the status bar (with clock, wifi indicator, etc) isn't showing.

**Comment by wujek-srujek** [comment]
This is broken in Flutter 3.16, fixed in main but not backported, see https://github.com/flutter/flutter/issues/138604

**Comment by jonbhanson** [comment]
Closing as this problem appears to come from Flutter, not this package.
