### ISSUE TITLE
Getting a 'module flutter_native_splash' not found error while I see it in pubspec?

### ISSUE THREAD

**Issue by Siyaho** [jonbhanson/flutter_native_splash#633]
Getting a 'module flutter_native_splash' not found error while I see it in pubspec. I have installed it, created it again, I see the assets but when I try to build it in Xcode, I am getting the 'Module 'flutter_native_splash' not found error. 

Any chance someone knows why? Using the latest dep version (flutter_native_splash: ^2.3.8 in pubspec.yaml). I made the upgrade from version 2.1.6.

**Device (please complete the following information):**
 - Device: iPhone 15 simulator
 - OS: latest MacOS on M2 Pro

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Build app in Xcode
2. Getting error  'Module 'flutter_native_splash', preventing it from building it in Runner > GeneratedPluginRegistrant

Note that it also changed / removed my logos, which I had set previously.

It is closely related to the issue here, but none of the solutions there are working for me:
https://github.com/flutter/flutter/issues/53573

**Comment by q3920687** [comment]
Yes, I have the same problem

**Comment by q3920687** [comment]
I see why you need to manually create the flutter_native_splash.yaml file and then run that command

**Comment by Siyaho** [comment]
I fixed it. Apparently, I had to do `pod install` in the ios folder. That fixed it for me.

**Comment by lreardon** [comment]
I encountered the same issue and had the same solution

**Comment by mirkomartino** [comment]
i have the same error.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (4 available)
[✓] Network resources
