### ISSUE TITLE
image does not show

### ISSUE THREAD

**Issue by disburden** [jonbhanson/flutter_native_splash#636]
The color can be set, but the setting image is invalid, and neither the setting image nor the background_image is not displayed on either the real machine or the emulator.
I thought it was my project, but I cloned the official example project without making any changes, with the same result. So I can't figure out what went wrong?

Yaml file configuration I will not post, because it is directly clone the official project, without any changes.

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.3, on Deepin 20.9 5.15.24-amd64-desktop, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.85.1)
[✓] Proxy Configuration
[✓] Connected device (4 available)
[✓] Network resources

**Describe the bug**

**Configuration**

Paste the flutter_native_splash section of your yaml config.

**Device (please complete the following information):**
 - Device: emulator Pixel 6a 
 - OS:API 31

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to '...'
2. Run in an emulator configured with '...'
3. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.  If in doubt, attach a screenshot.

**Additional context**

**Comment by disburden** [comment]
Can anyone give me some advice? Can you display pictures normally on your flash screen? I'm talking about the official example. Will the project work?

**Comment by disburden** [comment]
Can anyone normally use a full-screen picture as a splash screen background image? Can you send me a simple demo? Thank you very much!
email:disburden@gmail.com

**Comment by jonbhanson** [comment]
Did you check the [notes on Android 12](https://pub.dev/packages/flutter_native_splash#android-12-support)?  API 31 and later do not support a full screen image.

**Comment by disburden** [comment]
@jonbhanson 
Does this mean that the library can no longer use a full-screen image as a splash screen page by setting the background_image?
Maybe I have to make a splash page by myself?

**Comment by jonbhanson** [comment]
> @jonbhanson Does this mean that the library can no longer use a full-screen image as a splash screen page by setting the background_image?

This package can use a full screen image as a splash screen by setting `background_image`.  However Android 12 and later do not support full screen images which is why this package has a special Android 12+ configuration section which does not include `background_image`.

**Comment by disburden** [comment]
I'm definitely considering android 12 and late, so if I insist on using a full-screen image as a splash screen, I won't be able to use the package, right?

**Comment by jonbhanson** [comment]
Android 12 and later do not support full screen images.
