### ISSUE TITLE
Flutter Native Splash Screen by default Setting Image from icon launcher in center with background color for android 13

### ISSUE THREAD

**Issue by rutvi-kava** [jonbhanson/flutter_native_splash#639]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**
i have added my image ic_splash_screen which I want to display on splash screen. but instead of showing this image it is showing background color and setting app icon in center.

**Configuration**
i have aaded image in launch_background.xml also :                                                                             
 <?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
   <item>
        <shape android:shape="rectangle">
            <gradient
                android:angle="-90"
                android:endColor="#F89624"
                android:startColor="#B53B89"/>
        </shape>
    </item>

    <item>
        <bitmap
            android:gravity="fill"
            android:src="@drawable/ic_splash_screen" />
    </item>
</layer-list>

Paste the flutter_native_splash section of your yaml config.
 
dependencies:
  flutter:
    sdk: flutter

  #Icons
  cupertino_icons: 1.0.6

  flutter_native_splash: ^2.3.8

 
description:

**Device (please complete the following information):**
 - Device: OppoA58 (version: Android 13)  
 - OS: Android

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Set the config on the example app to '...'
3. Run in an emulator configured with '...'

**Screenshots**
If applicable, add screenshots to help explain your problem.  If in doubt, attach a screenshot.

i want to show this image which i have set but still not showing
![Screenshot_1703054140](https://github.com/jonbhanson/flutter_native_splash/assets/137261912/fa0e4fba-324a-45e3-baa9-4b538b32b8ce)

this is I am getting which is not my desired output
 ![Screenshot_1703055385](https://github.com/jonbhanson/flutter_native_splash/assets/137261912/4c2a3b99-9fd7-44aa-9bb5-1a6b5c5a9a02)

**Additional context**
this is video link for the issue : https://drive.google.com/file/d/10EUDG04mL85_QFmizC55-NUFSuj8MTDt/view

**Comment by jonbhanson** [comment]
Did you check the [notes on Android 12](https://pub.dev/packages/flutter_native_splash#android-12-support)?

**Comment by jonbhanson** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble.
