### ISSUE TITLE
Allow users to set a GIF file format for splash icon

### ISSUE THREAD

**Issue by nakulbisht** [jonbhanson/flutter_native_splash#648]
Hi, I have stumbled upon your flutter package and truly believe it is the best solution for every splash screen related problem. 

Although great, I want to bring your attention to my one simple request and that is, with addition to allowing .png file formats inside Android and iOS, please allow us to add .gif or .mp4 file format for our splash image.

I hope this should be simple, as you already allow fellow developers to add .gif file format splash images for web development.

**Comment by Zhamshid** [comment]
> Hi, I have stumbled upon your flutter package and truly believe it is the best solution for every splash screen related problem.
> 
> Although great, I want to bring your attention to my one simple request and that is, with addition to allowing .png file formats inside Android and iOS, please allow us to add .gif or .mp4 file format for our splash image.
> 
> I hope this should be simple, as you already allow fellow developers to add .gif file format splash images for web development.

+, or can you add new line after images that can be any loader place for custom animation in that formats,

**Comment by jonbhanson** [comment]
You can add your support for GIF on Android and iOS to https://github.com/jonbhanson/flutter_native_splash/issues/245.

**Comment by nakulbisht** [comment]
> You can add your support for GIF on Android and iOS to https://github.com/jonbhanson/flutter_native_splash/issues/245.

Thank you for the reply @jonbhanson 

So, are the .gif files not supported currently for Android or IOS, as I was unable to find any solution regarding my problem?

**Comment by jonbhanson** [comment]
Currently .gif files are only supported on web.

**Comment by nakulbisht** [comment]
> Currently .gif files are only supported on web.

Could you please provide information regarding the current status of .gif file support for Android and iOS platforms in your development timeline?

**Comment by jonbhanson** [comment]
I don't have plans to add .gif support.
