### ISSUE TITLE
Allow status bar hidden to be configurable

### ISSUE THREAD

**Issue by kwellman** [jonbhanson/flutter_native_splash#65]
The following code that gets added to AppDelegate.swift by this plugin should be configurable:

     UIApplication.shared.isStatusBarHidden = false

For apps like mine that are hiding the status bar, this code causes the status bar to be shown temporarily during the launch screen, which is obviously unwanted. Unless I’m missing something, there’s no way to configure this with the plugin so I have to manually remove it after running the plugin. An easy workaround, but not ideal.

**Comment by jonbhanson** [comment]
This feature has been added in the latest update.
