### ISSUE TITLE
Back button didn't work until FlutterNativeSplash.remove() is called leading to a possible PlayStore rejection

### ISSUE THREAD

**Issue by EArminjon** [jonbhanson/flutter_native_splash#651]
**Describe the bug**

```dart
final WidgetsBinding binding = WidgetsFlutterBinding.ensureInitialized();
FlutterNativeSplash.preserve(widgetsBinding: binding);
// Some codes
// ...
// Device back button will not work until remove() is called.
FlutterNativeSplash.remove();
```

Android device back button will not work until remove() is called.
Most of the time, remove() is called quickly after by developers by inside main. But, in my apps, I keep the splash screen displayed for many seconds. During this period, device back button didn't work.

I should be able to use as soon as possible the device back button and this package hang the back button. Please find bellow a reproductible example.

Because of this issue, PlayStore seems to reject my app.

**Configuration**

```yaml
flutter_native_splash:
  image: what_do_you_want
  color: "#094A9F"
  android_12:
    color: "#094A9F"
```

**Device (please complete the following information):**
 - Device: Resizable Android Studio Emulator
 - OS: Android API 34

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. Run app
2. CLick on back button
3. Your app remain in first plan, back button didn't work

```dart
import 'package:flutter/material.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';

void main() {
  final WidgetsBinding binding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: binding);

  // If remove is commented, back button will not work
  //FlutterNativeSplash.remove();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(final BuildContext context) {
    return const MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  const Home({super.key});

  @override
  Widget build(final BuildContext context) {
    WidgetsBinding.instance.addPostFrameCallback((final _) {
      print("Home first build is done !");
    });
    return Scaffold(
      appBar: AppBar(),
      body: const Center(
        child: Text("Hello"),
      ),
    );
  }
}
```

**Comment by jonbhanson** [comment]
The behavior you are describing is not caused by this package.  This package allows users to configure the splash screen, but the execution of the splash screen is carried out by the native OS.  I assume you are using Android 12 or later?  Here is a user with the same problem, but without Flutter: [Back button not responsive when the splash screen is showing (new Splash API for Android 12)](https://stackoverflow.com/questions/73186168/back-button-not-responsive-when-the-splash-screen-is-showing-new-splash-api-for).

**Comment by EArminjon** [comment]
Ty for your answer, i will look this way.
