### ISSUE TITLE
Issue setting background images for specific OS

### ISSUE THREAD

**Issue by Dsoji** [jonbhanson/flutter_native_splash#652]
I tried setting up my splash screen for the different OS for the project I'm working on but I keep getting this error in terminal
![image](https://github.com/jonbhanson/flutter_native_splash/assets/80987998/812e0463-dbf0-4cb0-a8eb-b7ba78d81866)

**Comment by jonbhanson** [comment]
I will push out an update soon that resolves this.

**Comment by Dsoji** [comment]
Alright thank you, can't wait

**Comment by jonbhanson** [comment]
No need to wait, I pushed out the update 3 days ago.

**Comment by Dsoji** [comment]
Checking out now, thank you

**Comment by Dsoji** [comment]
Still the same issue

**Comment by jonbhanson** [comment]
I was not able to reproduce this problem.  When I specified the `background_image_android` parameter in the example project's `pubspec.yaml`, the create command completed fine.  Can you provide a minimal project that demonstrates the problem?

**Comment by Dsoji** [comment]
Here is a new project i mage today and had the same issue: [https://github.com/Dsoji/splashScreen](url)
![image](https://github.com/jonbhanson/flutter_native_splash/assets/80987998/0d3a5899-f0de-4ca8-93f2-cdf4dbfd002f)

**Comment by Dsoji** [comment]
Hi, where you able to test and see if you were having the same issue on the project

**Comment by mainajonny** [comment]
Issue still persists

`john@MacBook-Pro flutterapp % dart run flutter_native_splash:create
Building package executable... (1.6s)
Built flutter_native_splash:create.
⚠️ The parameter "background_image_ios" was found in your flutter_native_splash config, but "background_image_ios" is not a valid flutter_native_splash parameter.
john@MacBook-Pro flutterapp % `

**Comment by waslost0** [comment]
Same
 flutter_native_splash: ^2.3.10
 ```⚠️ The parameter "background_image_ios" was found in your flutter_native_splash config, but "background_image_ios" is not a valid flutter_native_splash parameter.```

**Comment by Sameer330** [comment]
I got the same issur, any solutions??

```
$ dart run flutter_native_splash:create
Building package executable... (7.3s)
Built flutter_native_splash:create.
⚠️ The parameter "background_image_ios" was found in your flutter_native_splash config, but "background_image_ios" is not a valid flutter_native_splash parameter.
```

**Comment by jonbhanson** [comment]
Version 2.3.12 will resolve this.  Please update the version of `flutter_native_splash` in your `pubspec.yaml` and try again.
