### ISSUE TITLE
Readme Android 12 vs Android 12+

### ISSUE THREAD

**Issue by Mercutio1243** [jonbhanson/flutter_native_splash#658]
Dear team, for first time users as myself, I would suggest to update the readme explanations in section "1. Setting the splash screen" on "Android 12" to emphasize that it is actually relevant from Android version 12 onwards and not only for Android 12:

**Current explanation:**

>  Android 12 handles the splash screen differently than previous versions.  Please visit
>  https://developer.android.com/guide/topics/ui/splash-screen
>  Following are Android 12 specific parameter.

**Proposed change:**
>  From Android 12 onwards, the splash screen is handled differently than in previous versions.  Please visit
>  https://developer.android.com/guide/topics/ui/splash-screen
>  Following are specific parameter for Android 12+.

(Omitted #-sign here because of quotations)

**Comment by jonbhanson** [comment]
Thank you for the suggestion. I will push out an update soon that includes this.
