### ISSUE TITLE
Variable was never used (?)

### ISSUE THREAD

**Issue by Ahmadre** [jonbhanson/flutter_native_splash#66]
I am getting this warning during the ios build-phase:

```dart
[01:19:29]: ▸ ⚠️  /Users/**/**/**/**/ios/Runner/AppDelegate.swift:10:9: initialization of variable 'flutter_native_splash' was never used; consider replacing with assignment to '_' or removing it
[01:19:29]: ▸     var flutter_native_splash = 1
```

Why is this variable there? Do we need it?

Thanks for this package 📦

**Comment by frasza** [comment]
Same problem here. Any solution?

**Comment by deandreamatias** [comment]
This is a warning, not a error. 
The message is clear
> initialization of variable 'flutter_native_splash' was never used; consider replacing with assignment to '_' or removing it
Maybe have some error when generating this code to iOS. We need wait for a creator feedback

**Comment by Ahmadre** [comment]
> This is a warning, not a error. 
> The message is clear
> > initialization of variable 'flutter_native_splash' was never used; consider replacing with assignment to '_' or removing it
> Maybe have some error when generating this code to iOS. We need wait for a creator feedback

Yeah sure, but doesn't clearify the purpose question.

**Comment by jonbhanson** [comment]
This has been fixed in the latest update.
