### ISSUE TITLE
⚠️ The parameter "fill" was found in your flutter_native_splash config, but "fill" is not a valid flutter_native_splash parameter.

### ISSUE THREAD

**Issue by Obada2020** [jonbhanson/flutter_native_splash#661]
![image](https://github.com/jonbhanson/flutter_native_splash/assets/59412362/17963cc1-cf8b-4df8-a941-32ca116d0606)

**Comment by jonbhanson** [comment]
As stated in the bug template, 
> Attention: If you open a bug report without sufficient details, it will be closed.

The message looks like a configuration problem, but you did not include your configuration as requested in the bug template.

**Comment by ObidjonJoraboyev** [comment]
what should we do , now i have also this type of error

**Comment by jonbhanson** [comment]
@ObidjonJoraboyev open a new ticket and include all the details including your configuration.
