### ISSUE TITLE
When running the app on Android emulator, the following error occurs.

### ISSUE THREAD

**Issue by nnsyu** [jonbhanson/flutter_native_splash#663]
Attention: If you open a bug report without sufficient details, it will be closed.  Is your question
related to Android 12?  Please check the notes on Android 12 first (https://pub.dev/packages/flutter_native_splash#android-12-support).

**Describe the bug**

When running the app on Android emulator, the following error occurs.

\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:24: error: package net.jonhanson.flutter_native_splash does not exist
      flutterEngine.getPlugins().add(new net.jonhanson.flutter_native_splash.FlutterNativeSplashPlugin());

**Configuration**

flutter_native_splash:
  color: "#EEE8DC"
  image: assets/images/splash_bear.png

  android_12:
    color: "#EEE8DC"
    image: assets/images/splash_bear.png

**Device (please complete the following information):**
 - Device: [Pixel 7 pro API 33 (android avd)]
 - OS: [android 13]

**To Reproduce**
Steps to reproduce the behavior, using the example app:
1. add this line in pubspec.yaml 
dependencies:
  flutter_native_splash: ^2.3.11
2. run flutter pub get
3. add file "flutter_native_splash.yaml" in root dir
4. run command "dart run flutter_native_splash:create" in terminal
3. Run in an emulator
5. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.  If in doubt, attach a screenshot.

![image](https://github.com/jonbhanson/flutter_native_splash/assets/34337539/057eadfd-61ce-41f3-b81f-4c7a987d6ff1)

**Additional context**

**Comment by jonbhanson** [comment]
Based on #645, rebooting your computer and running `flutter clean && flutter pub get` may resolve the problem.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.

**Comment by FuadEfendi** [comment]
Rebooting didn't help, please reopen it still happens.

**Comment by FuadEfendi** [comment]
To confirm: it does not happen with `flutter build appbundle`. After this run I was able to do final "--obfuscate" run; but before, I always had issue above, even after restart. SOme "black magic" ;)
