### ISSUE TITLE
On iOS, when native splash screen is visible, Flutter can receive gesture events.

### ISSUE THREAD

**Issue by vincendep** [jonbhanson/flutter_native_splash#665]
On iOS is possible to interact with Flutter UI when the native splash screen is still visible.

**To Reproduce**

```
import 'package:flutter/material.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:url_launcher/url_launcher.dart';

final Uri _url = Uri.parse('https://flutter.dev');

void main() {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  runApp(
     GestureDetector(
      onTap: _launchUrl,
      child: const MaterialApp(home: Material()),
    ),
  );
}

Future<void> _launchUrl() async {
  if (!await launchUrl(_url)) {
    throw Exception('Could not launch $_url');
  }
}
```

https://github.com/jonbhanson/flutter_native_splash/assets/37916223/74d4706b-f2ee-413f-aa0a-a7d4dfec418e

**Comment by jonbhanson** [comment]
That is very interesting.  However, this package only configures the appearance of the splash screen (command line util) and controls when it is removed (with the .remove method).  This behavior would have to be addressed by the Flutter team.  Or it might even be iOS related.

**Comment by vincendep** [comment]
I was suspecting it...I guess it should be addressed by the flutter team then
