### ISSUE TITLE
light mode background before dark mode background is shown

### ISSUE THREAD

**Issue by rjahn** [jonbhanson/flutter_native_splash#667]
iOS 16
iPhone 14

My config is:

flutter_native_splash:
  background_image: assets/bg.png
  background_image_dark: assets/bg_dark.png
  image: assets/logo.png
  branding: assets/branding.png
  branding_dark: assets/branding_dark.png

 android_12:
    image: assets/logo.png
    color: "#78C9D8"
    color_dark: "#575757"
    branding: assets/branding.png
    branding_dark: assets/branding_dark.png

In dark mode phone setting, the deployed app-start shows the light mode background for some millis and fades to the back mode background. The light mode background is always shown in dark mode.

Is there a setting for hiding the light mode background in dark mode?

**Comment by jonbhanson** [comment]
Did you check out this question in the FAQ: [I see a flash of the wrong splash screen on iOS](https://pub.dev/packages/flutter_native_splash#i-see-a-flash-of-the-wrong-splash-screen-on-ios).
