### ISSUE TITLE
Flutter Create Splash Error

### ISSUE THREAD

**Issue by ifoxbr** [jonbhanson/flutter_native_splash#670]
Hello

Need help with your package. flutter_native_splash

Search Google, but did not find solution

When I execute: dart pub run flutter_native_splash:create

I receive this error: The parameter "flutter_launcher_icons" was found in your flutter_native_splash config, but "flutter_launcher_icons" is not a valid flutter_native_splash parameter.

Attached yaml file

Regards
[yaml.txt](https://github.com/jonbhanson/flutter_native_splash/files/14452357/yaml.txt)

**Comment by jonbhanson** [comment]
The text 'flutter_launcher_icons' does not appear in the config file you have attached, so the package is finding that text from somewhere else.  Are there other yaml files in your apps files?

**Comment by ifoxbr** [comment]
Sorry... attached FULL yaml file.

[fullyamlfile.txt](https://github.com/jonbhanson/flutter_native_splash/files/14452618/fullyamlfile.txt)

**Comment by jonbhanson** [comment]
In this configuration, flutter_launcher_icons: ^0.13.1 is a child of the flutter_native_splash section because it is under that section and indented two spaces.  Instead it should be placed under the dev_dependencies section.

**Comment by ifoxbr** [comment]
I did not know that...
This solved.  thank you very much

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

**Comment by jonbhanson** [comment]
You're welcome.
