### ISSUE TITLE
SplashScreen freezes on API 33 and below

### ISSUE THREAD

**Issue by myyvee** [jonbhanson/flutter_native_splash#673]
**Describe the bug**
One of my apps has the problem that (only) on Android (on emulator, on connected real device, on real device after downloading the app from Google Play Store) the GDPR-dialog had to be displayed after the splash screen, but it does not come to the foreground - the SplashScreen kind of freezes. I use flutter_native_splash: ^2.3.8 in the app and have compiled against API 34. Only when the phone was switched off (screen off) and then on again the GDPR-dialog did manage to come to the foreground. iPad and iPhone had no problems at all with the same version of the app. The GDPR-dialog has already been checked and is not causing the problem. Hence my question if such a behavior is known or possibly even a solution exists? Thanks in advance for any ideas!
This behaviour appears only with API 33 and below - from API 34 this issue is not replicable.

**Configuration**
dependencies:
  flutter:
    sdk: flutter
  [...]
  flutter_native_splash: ^2.3.6

flutter_native_splash:
  color: "#62EAFF" # set the background of splash screen to a solid color
  image: assets/android_launchscreens/splash.png # specify an image used in the splash screen 512×512
  android: true # platform
  ios: false # platform
  web: false # platform
  android_12:
    image: assets/android_launchscreens/splash_1152x1152.png
    color: "#62EAFF"
    icon_background_color: "#62EAFF"

**Device (please complete the following information):**
 - Device/OS: Pixel 6 API 29 Android 10 or Samsung s10e Android 12

**To Reproduce**
see description

**Comment by jonbhanson** [comment]
Whenever I have seen problems with the app freezing after the splash screen, it has been due to some other problem causing the app to freeze and thus the splash screen or a blank screen remains.  Adding Crashlytics or Sentry to your app may help diagnose unexplained crashes.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.
