### ISSUE TITLE
flutter_native_splash-development.yaml` appears to be empty or malformed

### ISSUE THREAD

**Issue by srijanC2306** [jonbhanson/flutter_native_splash#674]
Unhandled exception:
Exception: Your `flutter_native_splash-development.yaml` appears to be empty or malformed.
#0      getConfig (package:flutter_native_splash/cli_commands.dart:354:5)
#1      createSplash (package:flutter_native_splash/cli_commands.dart:42:18)
#2      main (file:///Users/srijanmukhopadhyay/.pub-cache/hosted/pub.dev/flutter_native_splash-2.3.13/bin/create.dart:18:5)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by jonbhanson** [comment]
As stated in the bug template,
> Attention: If you open a bug report without sufficient details, it will be closed.
