### ISSUE TITLE
_TypeError (type 'Null' is not a subtype of type 'Map<dynamic, dynamic>') dart flutter

### ISSUE THREAD

**Issue by mohamad7575** [jonbhanson/flutter_native_splash#675]
Hi, when I fetching data from Hive database  in flutter application I got this error , actually it happened every time I deleted an index from my hive data base and I added another  data to database , it not replacing with what I deleted before and  it become null , and after that when I want to fetch from database this error shown. And application crashed

**Device (please complete the following information):**
 - Device: emulator
 - OS: android 12
 - 
code:
for deleting
-------------------------------------------
```
  Future delete(int value, l) async {
    await lasttest.delete(value);
  }
```
-------------------------------------------
and for fetching 
------------------------------------------
```
  Future<Map> fetch() async {
    if (lasttest.values.isEmpty) {
      return Future.value({});
    } else {
      return Future.value(lasttest.toMap());
    }
  }
```
--------------------------------------

**Screenshots**
![image](https://github.com/jonbhanson/flutter_native_splash/assets/63646349/fc62dfa6-7d6b-4b6a-a71c-c9331a8d791d)
![image](https://github.com/jonbhanson/flutter_native_splash/assets/63646349/255585f8-ebaa-419c-b613-e37a7d04e30f)

please help me with that , I'm struggling with that for couple of days

**Comment by jonbhanson** [comment]
I don't understand how this problem is related to the `flutter_native_splash` package.  Can you explain?

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.

**Comment by mohamad7575** [comment]
sorry I just posted in wrong place, but my issue not solved yet .
