### ISSUE TITLE
Logo is not displaying for the first time after installing APK. Display at successive times. - Android

### ISSUE THREAD

**Issue by AjithRBT** [jonbhanson/flutter_native_splash#685]
Generating APK with following command
flutter build apk --flavor staging --no-tree-shake-icons --release

Installing this APK on a physical device. 

When opening the application for the first time, it shows only a screen with a background color without a logo.

When opening the application after that, it shows a logo with background color.

But this issue is not occurring in the emulator.

**Configuration**
```yaml
flutter_native_splash-staging.yaml
flutter_native_splash:
  color: "#22374a"
  image: "assets/images/splash.png"
  android: true
  ios: true
  web: false
  android_12:
    color: "#22374a"
    image: "assets/images/splash.png"
```

**Device (please complete the following information):**
 - Device: Samsung s23, IQOO Z7
 - OS: Android 13 

**Additional context**
flutter doctor -v
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.3 23D56 darwin-arm64, locale en-IN)
    • Flutter version 3.19.0 on channel stable at /Users/ajith/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (7 weeks ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ajith/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio 2.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • I2207 (mobile)  • 10BD4A0R9B0004Y • android-arm64  • Android 13 (API 33)
    • macOS (desktop) • macos           • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    • Chrome (web)    • chrome          • web-javascript • Google Chrome 123.0.6312.106
    ! Error: Browsing on the local area network for Ajith’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by jonbhanson** [comment]
Looks like this may be an Android bug judging from [this bug report](https://issuetracker.google.com/issues/244063660?pli=1).
