### ISSUE TITLE
Image_background not working

### ISSUE THREAD

**Issue by LincolnFerreira** [jonbhanson/flutter_native_splash#688]
When I try to put the image_background in the pubspec and recreate the splash, my image does not appear on my screen, is there a size limit or something else? because I want to use gradient in my initial background

**Configuration**

pubspec:
`flutter_native_splash:
  android: true
  ios: true
  background_image: "assets/gradient.jpg"
  android_12:
    background_image: "assets/gradient.jpg"
`

 - Device: android 12+

**Comment by jonbhanson** [comment]
[As stated in the readme](https://pub.dev/packages/flutter_native_splash#android-12-support), Android 12 (and later) does not support a background image.
