### ISSUE TITLE
 Splash screen image is cropped on Android 13 

### ISSUE THREAD

**Issue by Admave13** [jonbhanson/flutter_native_splash#691]
It happened to me too, the image is cropped in a square and in a lower resolution, but only in my real device, in the emulator works fine.  The image is 1152x1152 and follows the image size guidelines.
![53630273105_6b4b97bed2_6k](https://github.com/jonbhanson/flutter_native_splash/assets/103357825/6ce12739-a268-49df-9850-aa9ad9075902)

_Originally posted by @Admave13 in https://github.com/jonbhanson/flutter_native_splash/issues/495#issuecomment-2052629269_

**Comment by jonbhanson** [comment]
As the bug template states, "If you open a bug report without sufficient details, it will be closed."
