### ISSUE TITLE
Android 12 You colors as background

### ISSUE THREAD

**Issue by JHubi1** [jonbhanson/flutter_native_splash#697]
**Is your feature request related to a problem? Please describe.**
Android 12 introduced material you color. In flutter, we have a package that lets us theme the app after it. Other (non flutter) apps use the material color in the splash screen.

**Describe the solution you'd like**
An option to use the color, something like that:
```
android:
    color: "you"
```

**Describe alternatives you've considered**
A new option, like
```
android:
    you_color: true
```

**Comment by jonbhanson** [comment]
This would require a PR, as I do not have the bandwidth to implement it.

**Comment by rares45** [comment]
This is impossible because Monet colours don't load in the splash screen. I've tried natively and had no success. Not even Google's apps use Material You colours in their splash screens
