### ISSUE TITLE
Good way to add Text at the bottom (need guide)?

### ISSUE THREAD

**Issue by md-rifatkhan** [jonbhanson/flutter_native_splash#704]
I know there is no feature to add text at the bottom by default.

But in which image should i add text for show in bottom? image or background_image? and what is the recommended resolution for it?

Example like whatsapp, instagram
![download](https://github.com/jonbhanson/flutter_native_splash/assets/102645154/fdc90a1b-242c-4201-9f55-fcf9a3f3b308)

**Comment by md-rifatkhan** [comment]
> Use the `branding` feature.

thanks, whats the recommended resolution for branding image?

**Comment by jonbhanson** [comment]
There is not a recommended resolution.  You should choose a resolution based on the desired size of your branding image.
