### ISSUE TITLE
favicon.png not regenerated

### ISSUE THREAD

**Issue by CordMemescape** [jonbhanson/flutter_native_splash#706]
**Describe the bug**

If the `favicon_path` parameter in the `web` settings is changed and `dart run flutter_native_splash:create` is rerun, the favicon.png file is not regenerated in the project's web folder.

If the `favicon_path` file is deleted and `dart run flutter_native_splash:create` is rerun, the favicon.png file is not regenerated in the project's `web` folder.

**Configuration**

```
icons_launcher:
  platforms:
    web:
      enable: true
      image_path: 'assets/icons/web/app_icon_512x.png'
      favicon_path: 'assets/icons/web/favicon_512x.png'
```

**Device (please complete the following information):**
 - Device: MacBook Pro (M1)
 - OS: macOS Sonoma 14.5

**To Reproduce**
1. Create a config similar to the above.
2. Run `dart run flutter_native_splash:create` to generate splash screens.
3. Check `favicon.png` file in the project's `web` folder.
4. Change the `favicon_path` parameter to use a different image.
5. Rerun `dart run flutter_native_splash:create` to regenerate splash screens.
6. Check the `favicon.png` file in the project's `web` folder - this will be the identical image to Step 3.
7. Delete the `favicon.png` file from the project's `web` folder
8. Rerun `dart run flutter_native_splash:create` to regenerate splash screens.
9. Check `favicon.png` file in project's `web` folder - the file is not regenerated.

**Additional context**
Output from `dart run flutter_native_splash:create`:

```
Regenerating application splash screens...
Building package executable... (1.1s)
Built flutter_native_splash:create.
[Android] Creating default splash images
[Android] Updating launch background(s) with splash image path...
[Android]  - android/app/src/main/res/drawable/launch_background.xml
[Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
[Android] Updating styles...
[Android]  - android/app/src/main/res/values-v31/styles.xml
[Android]  - android/app/src/main/res/values-night-v31/styles.xml
[Android]  - android/app/src/main/res/values/styles.xml
[Android]  - android/app/src/main/res/values-night/styles.xml
[iOS] Creating  images
[iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
[Web] Creating images
[Web] Creating images
[Web] Creating background images
[Web] Creating CSS
[Web] Updating index.html

✅ Native splash complete.
Now go finish building something awesome! 💪 You rock! 🤘🤩
Like the package? Please give it a 👍 here: https://pub.dev/packages/flutter_native_splash
```

**Comment by jonbhanson** [comment]
Did you open this ticket against the wrong package?  This package does not generate the `favicon.png` image.

**Comment by CordMemescape** [comment]
Jon, you're absolutely right! Apologies, this was supposed to be logged against a different package. It must have been a very, very long day!
