### ISSUE TITLE
Implement Function After FlutterNativeSplash.remove();

### ISSUE THREAD

**Issue by KyawSoeW1n** [jonbhanson/flutter_native_splash#714]
removeAfter() is deprecated. I would like to make redirection after splash screen.

**Comment by jonbhanson** [comment]
I do not understand this ticket.  Please explain clearly what your question is.

**Comment by KyawSoeW1n** [comment]
@jonbhanson 

Right now , removeAfter() method is deprecated. I would like to make a function after doing FlutterNativeSplash.remove().

**Comment by jonbhanson** [comment]
With the `.remove()` function, you control when the splash screen is removed.  If there is something that you want done after the `.remove()` function, why can't you just create your own function and call it after `.remove()`?

**Comment by KyawSoeW1n** [comment]
because previous version provide .removeAfter() function. I can create own function. @jonbhanson
