### ISSUE TITLE
image_dark is requiere but example says otherwise 

### ISSUE THREAD

**Issue by ghost** [jonbhanson/flutter_native_splash#720]
**Describe the bug**

image_dark is requiere when the device is in dark mode even if the example [here](https://docs.flutter.dev/platform-integration/android/splash-screen) says otherwise.

**Device (please complete the following information):**
 - Device: CAT S42
 - OS: Android10

**Comment by jonbhanson** [comment]
Can you please explain in more detail?  I do not understand.

**Comment by knemay** [comment]
Yes, sorry. In an Android 10 using dark mode the image is not shown if you dont specify the 'image_dark', but in the example [here](https://pub.dev/packages/flutter_native_splash) it says 'The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background and image when the device is in dark mode. If they are not specified, the app will use the parameters from above.'
