### ISSUE TITLE
UnmodifiableUint8ListView

### ISSUE THREAD

**Issue by paulobreim** [jonbhanson/flutter_native_splash#722]
I don't know if this is a BUG, ​​but since I didn't find a question and answer section, I'm posting it here:

After updating the flutter version to version 3.24.0, when I run the command dart run flutter_native_splash:create I get the error:
Error: Method not found: 'UnmodifiableUint8ListView'.
UnmodifiableUint8ListView(Uint8List(0));

In my program, and in many other programs on the web, this error also started to appear and the solution was to put in pubspec.yaml dependencies:
win32: ^5.5.3

thanks,
paulo

**Comment by jonbhanson** [comment]
When I tested the example app with Flutter 3.24.0, it ran without any errors.  Please upload a minimal project that demonstrates this error in order to analyze further.

**Comment by joseminelli** [comment]
add dependency : `win32: ^5.5.3 ` . It worked for me

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.
