### ISSUE TITLE
in android splash image not show.

### ISSUE THREAD

**Issue by nikunjshaligram** [jonbhanson/flutter_native_splash#723]
flutter_native_splash:
  background_image: assets/images/splash_image.png
  color: "#ffffff"
  android: true
  ios: true
  fullscreen: true
  ios_content_mode: scaleAspectFill 
  android_gravity: fill

  android_12:
    color: "#ffffff"
    background_image: assets/images/splash_image.png
    fullscreen: true
    android_gravity: fill
    ios_content_mode: center
    
    This is my code for native splash. issue is my image not show in splash screen. flutter default white screen show.

**Comment by jonbhanson** [comment]
Android 12 and later do not support a background image.

**Comment by nikunjshaligram** [comment]
How to manage splash screen with background image?
