### ISSUE TITLE
Blurred image with correct size

### ISSUE THREAD

**Issue by erperejildo** [jonbhanson/flutter_native_splash#725]
This is my circle/container (the canvas is 1152×1152):
![image](https://github.com/user-attachments/assets/b390fde7-fb86-469a-b2be-266c26c6d5a9)

The image exported has enough quality:
![splash_android12](https://github.com/user-attachments/assets/8db205b6-bcab-4f0f-b3c0-9e591be6f860)

but not the generated icon:
![WhatsApp Image 2024-08-28 at 16 57 09_e02c4c98](https://github.com/user-attachments/assets/888cb540-1c8b-430c-bb37-5c3d2a9123c5)

Also, what should be the size for the branding image? I don't find any related information in the documentation

**Comment by Mkohm** [comment]
Same here, it appears blurred.

**Comment by ron-diesel** [comment]
I have the same problem.

**Comment by Jatoxo** [comment]
Same here

**Comment by charleshan** [comment]
Same issue as #724

**Comment by hayatbangash55** [comment]
Do we have any solution for blur image?

**Comment by erperejildo** [comment]
> Do we have any solution for blur image?

we don't even have a response

**Comment by SpyrosGashel** [comment]
Same problem here. I have the exactly same icon's dimensions. On Android 11, it is shown perfect, but on android 12 and above the image is blurring.

**Comment by hayatbangash55** [comment]
I guess we have to wait then

**Comment by erperejildo** [comment]
> I guess we have to wait then

original issue created in January
https://github.com/jonbhanson/flutter_native_splash/issues/650

**Comment by jonbhanson** [comment]
@erperejildo your source image should be 1152×1152 pixels but the one you posted is 8000x8000 pixels.

**Comment by jonbhanson** [comment]
Here is your splash with the resolution you uploaded:

<img width="429" alt="API35" src="https://github.com/user-attachments/assets/0c5c214e-1130-4ce1-9834-02498d4d1892">

Here is the splash after I resized the source to 1152×1152:
<img width="441" alt="Corrected" src="https://github.com/user-attachments/assets/caaa9cd8-cc14-4fb6-9099-e1e24d62c5b3">

**Comment by jonbhanson** [comment]
I will close this as I believe I have given the solution for @erperejildo's original trouble.  If any of the follow up posters have a blurred image problem that is not related to an incorrect source resolution, feel free to open a new ticket and please attach your source image.
