### ISSUE TITLE
Android branding sizing ratio

### ISSUE THREAD

**Issue by JudahMcNicholl** [jonbhanson/flutter_native_splash#729]
It would be nice if the yaml says a good ratio size for the branding on android
In this [article](https://medium.com/@radomir9720/android-splash-screen-easy-setup-for-both-11-version-and-lower-and-12-287ccb86f9c7) it explains that the ratio should be 5:2

**Comment by jonbhanson** [comment]
Is this an official recommendation of Android?

**Comment by divan** [comment]
Please add it to README.
We used logo as a branding, and it was crucial that the branding image is not distorted. On some Android phones it looks right, but on some it gets distorted if not followed the 5:2 rule. It's not even easy to catch this.

Quote from the article:
> Aspect ratio of the branding image should be 5:2. For example, if the width is 200, then the height should be 80(200/2,5).

**Comment by divan** [comment]
>  Is this an official recommendation of Android?

Yes. It's not even 'reccomendation'. They use the word 'must'.

> Branded image: this **must** be 200×80 dp.

https://developer.android.com/develop/ui/views/launch/splash-screen
