### ISSUE TITLE
showDialog problem

### ISSUE THREAD

**Issue by xusir000** [jonbhanson/flutter_native_splash#732]
Why can't showDialog pop up before the launch page closes

**Comment by xusir000** [comment]
Please, there is a way to solve the problem that showDialog cannot pop up

**Comment by jonbhanson** [comment]
Related: #590. I don't think it is possible to display a dialog over the splash screen.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.
