### ISSUE TITLE
Android 12 Customization

### ISSUE THREAD

**Issue by mo7amedaliEbaid** [jonbhanson/flutter_native_splash#733]
I am using `flutter_native_splash` plugin v `^2.4.0` in my app and it has these specifications for `android 12`
```
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter
 ```

now if I want to make the icon with bigger dimensions or make it fill or fit width of the screen How to custom this native splash ?

**Comment by jonbhanson** [comment]
For Android 12 and later, it is not possible to use bigger dimensions or make the image feel or fit the width of the screen.
