### ISSUE TITLE
Android 14 shows a black screen between the native splash and the first flutter widget

### ISSUE THREAD

**Issue by mako-yolo** [jonbhanson/flutter_native_splash#735]
**Describe the bug**
Android 14 shows a black screen after the native Android splash screen and before showing the first Flutter widget.
All lower Android versions work well.
For Android 12 everything was configured corresponding to the official library documentation and the accompanying links of the README section. Only Android 14 has this issue.

**Library version**: 2.4.1

**Device/OS**: Android 34

**Comment by mesaglam** [comment]
Did you use 

`  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);`

in main section?

**Comment by mako-yolo** [comment]
Yes, I do, and i hide it in the initState method later. It works as expected for v<34

**Comment by marvelaman** [comment]
can you provide code from main activity native code?
I followed steps from official docs and it helped to fix my issue:
https://docs.flutter.dev/platform-integration/android/splash-screen
https://docs.flutter.dev/release/breaking-changes/splash-screen-migration

**Comment by jonbhanson** [comment]
I tested this packages example with API34 but was not able to reproduce the problem. Can you advise how to reproduce the problem with the example or post a minimal example that reproduces the problem.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen with instructions to reproduce if you are still having trouble.
