### ISSUE TITLE
Initial color is always #42a5f5

### ISSUE THREAD

**Issue by pennadl** [jonbhanson/flutter_native_splash#736]
I'm testing on iOS simulator and the initial splash screen is always #42a5f5, after a few seconds it changes to the color set in my `flutter_splash.yaml` which I used to generate the resources with 
`dart run flutter_native_splash:create --path=flutter_splash.yaml`

I tried to clean the project, rename the yaml file, remove the splash and recreate, but always the same issue.

The yaml file is pretty simple I've only changed the color and added an image, both are loaded after the blue initial screen.

```
flutter_native_splash:
  color: "#161618"
  image: assets/images/logo.png 
```

<img width="1256" alt="image" src="https://github.com/user-attachments/assets/b812298f-c146-4283-8916-1411e8dd8f00">

**Comment by jonbhanson** [comment]
Have you tried powering off the simulator and then powering it back on?

**Comment by pennadl** [comment]
Yes maybe was that, after a while it fixed itself


Il 29 set 2024, 15:26 +0200, Jon Hanson ***@***.***>, ha scritto:
