### ISSUE TITLE
On Android 12  version the icon isn't displayed when launch from the Launcher. But it is shown when launch from Home screen.

### ISSUE THREAD

**Issue by ArmenuhiMkrtchyan** [jonbhanson/flutter_native_splash#738]
Hi all, :wave: I have appropriate issue :interrobang:
Any help will appreciated :pray:

 - On Samsung Galaxy S10 (Android 12) Splash Screen Icon Not Displaying
 - The icon isn't displayed when launch from the Launcher. 
 - But it is shown when launch from Home screen.
 - Issue appears only on the Android 12 version.

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.
