### ISSUE TITLE
App Icon showing in square

### ISSUE THREAD

**Issue by mrsaurabhpatil** [jonbhanson/flutter_native_splash#746]
**Describe the bug**

Thanks for the repo. I've tried importing the splash screen, and running the create command but instead of showing the app logo in regular size, the logo appears zoomed and cropped. I've attached the screenshot for the reference.

![2024-11-05 20_04_45-](https://github.com/user-attachments/assets/005bc04b-d234-470c-9018-19c1a3cba2a3)

**Configuration**

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/logo.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/logo.png

  web: false

**Device (please complete the following information):**
 - Device: [OnePlus Nord]
 - OS: [Android 12]

Thanks for the valuable feedbacks!

**Comment by jonbhanson** [comment]
Can you attach the assets/logos/logo.png image to this ticket? Thanks

**Comment by jonbhanson** [comment]
Closed due to inactivity.  Feel free to reopen if you are still having trouble.

**Comment by mrsaurabhpatil** [comment]
![namaste_gestire](https://github.com/user-attachments/assets/9ebca2d1-700d-4ad4-8ba2-f2ad504da130)
Sorry for the inconvenience, I can't attach the image of the logo, but this is a similar attachment from the client's app. Once available, please look into it.

**Comment by jonbhanson** [comment]
Sorry, but I would need to see the original source image in order to help.

**Comment by mrsaurabhpatil** [comment]
Is there any way that I can share the logo with you in person. As the client has denied to share their logo.

**Comment by jonbhanson** [comment]
You can send the photo to jon@jonhanson.net.

**Comment by jonbhanson** [comment]
@mrsaurabhpatil sure, let me know your email and I will send you a note.

**Comment by mrsaurabhpatil** [comment]
Thanks for the confirmation.

Please note: mr.saurhub@gmail.com.

Thanks

**Comment by jonbhanson** [comment]
@mrsaurabhpatil I received your image in my email.  It is the wrong resolution.  Please read the instructions on this package for information about the correct sizing of the source splash image.

**Comment by mrsaurabhpatil** [comment]
Sure, will try and update the same.
Thanks! 👍
