### ISSUE TITLE
Make flavor generation easier by not having to specify flavors by name

### ISSUE THREAD

**Issue by petcupaula** [jonbhanson/flutter_native_splash#751]
**Is your feature request related to a problem? Please describe.**
It's frustrating that I need to specify the names of the flavors when generating the splash screens for different flavors. 

**Describe the solution you'd like**
Instead of having to do:
`dart run flutter_native_splash:create --flavors development,staging,production`
I would like to be able to do:
`dart run flutter_native_splash:create -f flutter_native_spash*`

**Describe alternatives you've considered**
Currently need to do some manual work and thus need to write some thorough README files and do checks that things are not missed. Could also do some scripts that generate the names and command and then run it. 

**Additional context**
Proposed solution is inspired by the args that `flutter_launcher_icons` takes for flavors setup, which would make things easier.

**Comment by jonbhanson** [comment]
Feel free to add a PR, or @vlazdra may be interested in adding this.

**Comment by vlazdra** [comment]
This should be pretty straightforward, might be a good start as a first issue if you'd like to open a PR @petcupaula ? 😃 

If not, let me know so I can extend this feature. 😃

**Comment by petcupaula** [comment]
@vlazdra Feel free to go ahead with it 😃

**Comment by petcupaula** [comment]
Yes, exactly! A match on all files with the right prefix (flutter_native_splash*) and then splash screens are generated for everything defined in those files.

**Comment by vlazdra** [comment]
Hey @petcupaula I've made the PR for the changes that you desired.

Until Jon responds and approves them (or denies them), if you are willing to help and maybe give some feedback if the changes work, that would be awesome! 😃 

To try out the changes in your project, you can add my fork and branch to your project like so:
```yaml
  flutter_native_splash:
    git:
      url: https://github.com/vlazdra/flutter_native_splash
      ref: generate-all
```

Then do a `flutter pub get` and latter on run the command in your root: `dart run flutter_native_splash:create --all-flavors`

Please make sure you are working with a clean branch in your project. _Do not run_ it if you have uncomited changes on your branch.
