### ISSUE TITLE
What's the difference between image and branding?

### ISSUE THREAD

**Issue by MarkOSullivan94** [jonbhanson/flutter_native_splash#753]
I noticed there are two settings where you can specify an image: 

1. `image` 
2. `branding` 

What is the difference in the two?

**Comment by 0x456d7265** [comment]
> I noticed there are two settings where you can specify an image:
> 
> 1. `image`
> 2. `branding`
> 
> What is the difference in the two?

You can display another image as `branding` at the bottom. It's often used to display a company logo.

Take Instagram for example;

Instagram Logo at the center is `image`
Meta logo at the bottom is `branding`
![image](https://github.com/user-attachments/assets/ffc474b0-924f-41ff-9e8a-eb09f642bbb2)

**Comment by MarkOSullivan94** [comment]
Thank you for the explanation!
