### ISSUE TITLE
[Bug]shift position

### ISSUE THREAD

**Issue by shinriyo** [jonbhanson/flutter_native_splash#86]
I guess it is dependence of Android machine.

Galaxy S10

vertically shift bug

**Comment by shinriyo** [comment]
like this
https://stackoverflow.com/questions/54751605/android-splash-screen-shifts

**Comment by shinriyo** [comment]
`android:windowBackground`
to 
`android:background`
?

**Comment by jonbhanson** [comment]
Can you give instructions on how to reproduce?

**Comment by shinriyo** [comment]
@jonbhanson 
how to reproduce is README's Usage

**Comment by mmmcorpsvit** [comment]
try check: https://github.com/flutter/flutter/issues/46486#issuecomment-760117674

**Comment by jonbhanson** [comment]
@shinriyo I created a new project using the instructions in the readme, but I was not able to reproduce the shift you described.

**Comment by shinriyo** [comment]
do you use Galaxy S10?

**Comment by jonbhanson** [comment]
I don't have a physical Galaxy S10, but I tried it with an emulated S10.

**Comment by shinriyo** [comment]
@jonbhanson It happened in physical Galaxy S10, but I don't have it too.
in the Previous project, a worker had Galaxy S10, but I moved the project I can't try it now.

@mmmcorpsvit 's link may help the problem.

**Comment by jonbhanson** [comment]
@shinriyo thanks for the info.  Since I have not been able to reproduce, I will close this ticket.  Feel free to reopen if you can give steps to reproduce.
