### ISSUE TITLE
Flutter IOS Device Status bar Color? How To Chanage Status Bar Text Color 

### ISSUE THREAD

**Issue by shubhamkatake** [jonbhanson/flutter_native_splash#93]
While Creating App with Flutter I have used "flutter_native_splash 0.1.9" this library, How do I change the status bar text color to black? On IOS Device It is not working.

**Comment by jonbhanson** [comment]
I think this should be resolved by recent updates.  If it is still a problem, feel free to reopen the ticket with a screenshot of the problem.  Thanks.
