### ISSUE TITLE
Lottiefiles native splash screen support 

### ISSUE THREAD

**Issue by LOG-TAG** [jonbhanson/flutter_native_splash#96]
it's easy to put GitHub issues :), I will work on Lottie files integration for this

**Comment by jonbhanson** [comment]
Please feel free to make a pull request if you can add this integration.  Unfortunately I don't have any Lottie files knowledge, so I will not be able to contribute.

**Comment by jonbhanson** [comment]
In order to find out what file formats are most needed by the community, I have opened a single ticket to capture all image format requests.  Please visit (this ticket)[https://github.com/jonbhanson/flutter_native_splash/issues/245] to vote for the image format you need.
