### ISSUE TITLE
[feature] command to remove/uninstall splash

### ISSUE THREAD

**Issue by maico910** [jonbhanson/flutter_native_splash#97]
create commando like:

 ` flutter pub run flutter_native_splash:remove`

to remove splash screen.

#55 
#64 
#82

**Comment by jonbhanson** [comment]
This command has been added in the latest update.

**Comment by SardorbekR** [comment]
This command not removing splash image, I reinstalled app, but still, it shows splash image. So I had to remove images manually(

**Comment by jonbhanson** [comment]
@SardorbekR can you provide more details?  What elements did you remove manually?  Was it Android or iOS?

**Comment by SardorbekR** [comment]
In both OS it did not work. So, I tried this solution: https://github.com/jonbhanson/flutter_native_splash/issues/82#issuecomment-687589067

**Comment by jonbhanson** [comment]
Thanks for the feedback, @SardorbekR.  I am pushing a release to fix this.  👍🏻

**Comment by ffaridi1** [comment]
Not working. No matter what I do the splashscreen is not getting removed.
Could you share the steps to remove manually specially for iOS ?

**Comment by jonbhanson** [comment]
@ffaridi1 if you see your same splash screen, check out this question in the FAQ: [I see a flash of the wrong splash screen on iOS](https://pub.dev/packages/flutter_native_splash#i-see-a-flash-of-the-wrong-splash-screen-on-ios).  Also, it should be noted that the splash screen cannot be removed, only reset to a blank white splash screen.
